// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/sub/message.proto

package sub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StringMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	mi := &file_examples_internal_proto_sub_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_sub_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_sub_message_proto_rawDescGZIP(), []int{0}
}

func (x *StringMessage) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

var File_examples_internal_proto_sub_message_proto protoreflect.FileDescriptor

const file_examples_internal_proto_sub_message_proto_rawDesc = "" +
	"\n" +
	")examples/internal/proto/sub/message.proto\x12\x1bexamples.internal.proto.sub\"%\n" +
	"\rStringMessage\x12\x14\n" +
	"\x05value\x18\x01 \x02(\tR\x05valueBGZEgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/sub"

var (
	file_examples_internal_proto_sub_message_proto_rawDescOnce sync.Once
	file_examples_internal_proto_sub_message_proto_rawDescData []byte
)

func file_examples_internal_proto_sub_message_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_sub_message_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_sub_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_sub_message_proto_rawDesc), len(file_examples_internal_proto_sub_message_proto_rawDesc)))
	})
	return file_examples_internal_proto_sub_message_proto_rawDescData
}

var file_examples_internal_proto_sub_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_internal_proto_sub_message_proto_goTypes = []any{
	(*StringMessage)(nil), // 0: examples.internal.proto.sub.StringMessage
}
var file_examples_internal_proto_sub_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_sub_message_proto_init() }
func file_examples_internal_proto_sub_message_proto_init() {
	if File_examples_internal_proto_sub_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_sub_message_proto_rawDesc), len(file_examples_internal_proto_sub_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_internal_proto_sub_message_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_sub_message_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_sub_message_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_sub_message_proto = out.File
	file_examples_internal_proto_sub_message_proto_goTypes = nil
	file_examples_internal_proto_sub_message_proto_depIdxs = nil
}
