// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/pathenum/path_enum.proto

package pathenum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathEnum int32

const (
	PathEnum_ABC PathEnum = 0
	PathEnum_DEF PathEnum = 1
)

// Enum value maps for PathEnum.
var (
	PathEnum_name = map[int32]string{
		0: "ABC",
		1: "DEF",
	}
	PathEnum_value = map[string]int32{
		"ABC": 0,
		"DEF": 1,
	}
)

func (x PathEnum) Enum() *PathEnum {
	p := new(PathEnum)
	*p = x
	return p
}

func (x PathEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_pathenum_path_enum_proto_enumTypes[0].Descriptor()
}

func (PathEnum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_pathenum_path_enum_proto_enumTypes[0]
}

func (x PathEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathEnum.Descriptor instead.
func (PathEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_pathenum_path_enum_proto_rawDescGZIP(), []int{0}
}

// Ignoring lint warnings as this enum type exist to validate proper functionality
// for projects that don't follow these lint rules.
// buf:lint:ignore ENUM_PASCAL_CASE
type SnakeCaseForImport int32

const (
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	SnakeCaseForImport_value_x SnakeCaseForImport = 0
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	SnakeCaseForImport_value_y SnakeCaseForImport = 1
)

// Enum value maps for SnakeCaseForImport.
var (
	SnakeCaseForImport_name = map[int32]string{
		0: "value_x",
		1: "value_y",
	}
	SnakeCaseForImport_value = map[string]int32{
		"value_x": 0,
		"value_y": 1,
	}
)

func (x SnakeCaseForImport) Enum() *SnakeCaseForImport {
	p := new(SnakeCaseForImport)
	*p = x
	return p
}

func (x SnakeCaseForImport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnakeCaseForImport) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_pathenum_path_enum_proto_enumTypes[1].Descriptor()
}

func (SnakeCaseForImport) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_pathenum_path_enum_proto_enumTypes[1]
}

func (x SnakeCaseForImport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnakeCaseForImport.Descriptor instead.
func (SnakeCaseForImport) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_pathenum_path_enum_proto_rawDescGZIP(), []int{1}
}

type MessagePathEnum_NestedPathEnum int32

const (
	MessagePathEnum_GHI MessagePathEnum_NestedPathEnum = 0
	MessagePathEnum_JKL MessagePathEnum_NestedPathEnum = 1
)

// Enum value maps for MessagePathEnum_NestedPathEnum.
var (
	MessagePathEnum_NestedPathEnum_name = map[int32]string{
		0: "GHI",
		1: "JKL",
	}
	MessagePathEnum_NestedPathEnum_value = map[string]int32{
		"GHI": 0,
		"JKL": 1,
	}
)

func (x MessagePathEnum_NestedPathEnum) Enum() *MessagePathEnum_NestedPathEnum {
	p := new(MessagePathEnum_NestedPathEnum)
	*p = x
	return p
}

func (x MessagePathEnum_NestedPathEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessagePathEnum_NestedPathEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_pathenum_path_enum_proto_enumTypes[2].Descriptor()
}

func (MessagePathEnum_NestedPathEnum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_pathenum_path_enum_proto_enumTypes[2]
}

func (x MessagePathEnum_NestedPathEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessagePathEnum_NestedPathEnum.Descriptor instead.
func (MessagePathEnum_NestedPathEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_pathenum_path_enum_proto_rawDescGZIP(), []int{0, 0}
}

type MessagePathEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePathEnum) Reset() {
	*x = MessagePathEnum{}
	mi := &file_examples_internal_proto_pathenum_path_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePathEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePathEnum) ProtoMessage() {}

func (x *MessagePathEnum) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_pathenum_path_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePathEnum.ProtoReflect.Descriptor instead.
func (*MessagePathEnum) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_pathenum_path_enum_proto_rawDescGZIP(), []int{0}
}

type MessageWithPathEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         PathEnum               `protobuf:"varint,1,opt,name=value,proto3,enum=examples.internal.pathenum.PathEnum" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithPathEnum) Reset() {
	*x = MessageWithPathEnum{}
	mi := &file_examples_internal_proto_pathenum_path_enum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithPathEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithPathEnum) ProtoMessage() {}

func (x *MessageWithPathEnum) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_pathenum_path_enum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithPathEnum.ProtoReflect.Descriptor instead.
func (*MessageWithPathEnum) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_pathenum_path_enum_proto_rawDescGZIP(), []int{1}
}

func (x *MessageWithPathEnum) GetValue() PathEnum {
	if x != nil {
		return x.Value
	}
	return PathEnum_ABC
}

type MessageWithNestedPathEnum struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Value         MessagePathEnum_NestedPathEnum `protobuf:"varint,1,opt,name=value,proto3,enum=examples.internal.pathenum.MessagePathEnum_NestedPathEnum" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithNestedPathEnum) Reset() {
	*x = MessageWithNestedPathEnum{}
	mi := &file_examples_internal_proto_pathenum_path_enum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithNestedPathEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithNestedPathEnum) ProtoMessage() {}

func (x *MessageWithNestedPathEnum) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_pathenum_path_enum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithNestedPathEnum.ProtoReflect.Descriptor instead.
func (*MessageWithNestedPathEnum) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_pathenum_path_enum_proto_rawDescGZIP(), []int{2}
}

func (x *MessageWithNestedPathEnum) GetValue() MessagePathEnum_NestedPathEnum {
	if x != nil {
		return x.Value
	}
	return MessagePathEnum_GHI
}

var File_examples_internal_proto_pathenum_path_enum_proto protoreflect.FileDescriptor

const file_examples_internal_proto_pathenum_path_enum_proto_rawDesc = "" +
	"\n" +
	"0examples/internal/proto/pathenum/path_enum.proto\x12\x1aexamples.internal.pathenum\"5\n" +
	"\x0fMessagePathEnum\"\"\n" +
	"\x0eNestedPathEnum\x12\a\n" +
	"\x03GHI\x10\x00\x12\a\n" +
	"\x03JKL\x10\x01\"Q\n" +
	"\x13MessageWithPathEnum\x12:\n" +
	"\x05value\x18\x01 \x01(\x0e2$.examples.internal.pathenum.PathEnumR\x05value\"m\n" +
	"\x19MessageWithNestedPathEnum\x12P\n" +
	"\x05value\x18\x01 \x01(\x0e2:.examples.internal.pathenum.MessagePathEnum.NestedPathEnumR\x05value*\x1c\n" +
	"\bPathEnum\x12\a\n" +
	"\x03ABC\x10\x00\x12\a\n" +
	"\x03DEF\x10\x01*1\n" +
	"\x15snake_case_for_import\x12\v\n" +
	"\avalue_x\x10\x00\x12\v\n" +
	"\avalue_y\x10\x01BLZJgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/pathenumb\x06proto3"

var (
	file_examples_internal_proto_pathenum_path_enum_proto_rawDescOnce sync.Once
	file_examples_internal_proto_pathenum_path_enum_proto_rawDescData []byte
)

func file_examples_internal_proto_pathenum_path_enum_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_pathenum_path_enum_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_pathenum_path_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_pathenum_path_enum_proto_rawDesc), len(file_examples_internal_proto_pathenum_path_enum_proto_rawDesc)))
	})
	return file_examples_internal_proto_pathenum_path_enum_proto_rawDescData
}

var file_examples_internal_proto_pathenum_path_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_examples_internal_proto_pathenum_path_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_internal_proto_pathenum_path_enum_proto_goTypes = []any{
	(PathEnum)(0),                       // 0: examples.internal.pathenum.PathEnum
	(SnakeCaseForImport)(0),             // 1: examples.internal.pathenum.snake_case_for_import
	(MessagePathEnum_NestedPathEnum)(0), // 2: examples.internal.pathenum.MessagePathEnum.NestedPathEnum
	(*MessagePathEnum)(nil),             // 3: examples.internal.pathenum.MessagePathEnum
	(*MessageWithPathEnum)(nil),         // 4: examples.internal.pathenum.MessageWithPathEnum
	(*MessageWithNestedPathEnum)(nil),   // 5: examples.internal.pathenum.MessageWithNestedPathEnum
}
var file_examples_internal_proto_pathenum_path_enum_proto_depIdxs = []int32{
	0, // 0: examples.internal.pathenum.MessageWithPathEnum.value:type_name -> examples.internal.pathenum.PathEnum
	2, // 1: examples.internal.pathenum.MessageWithNestedPathEnum.value:type_name -> examples.internal.pathenum.MessagePathEnum.NestedPathEnum
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_pathenum_path_enum_proto_init() }
func file_examples_internal_proto_pathenum_path_enum_proto_init() {
	if File_examples_internal_proto_pathenum_path_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_pathenum_path_enum_proto_rawDesc), len(file_examples_internal_proto_pathenum_path_enum_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_internal_proto_pathenum_path_enum_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_pathenum_path_enum_proto_depIdxs,
		EnumInfos:         file_examples_internal_proto_pathenum_path_enum_proto_enumTypes,
		MessageInfos:      file_examples_internal_proto_pathenum_path_enum_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_pathenum_path_enum_proto = out.File
	file_examples_internal_proto_pathenum_path_enum_proto_goTypes = nil
	file_examples_internal_proto_pathenum_path_enum_proto_depIdxs = nil
}
