// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/oneofenum/oneof_enum.proto

package oneofenum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleEnum int32

const (
	ExampleEnum_EXAMPLE_ENUM_UNSPECIFIED ExampleEnum = 0
	ExampleEnum_EXAMPLE_ENUM_FIRST       ExampleEnum = 1
)

// Enum value maps for ExampleEnum.
var (
	ExampleEnum_name = map[int32]string{
		0: "EXAMPLE_ENUM_UNSPECIFIED",
		1: "EXAMPLE_ENUM_FIRST",
	}
	ExampleEnum_value = map[string]int32{
		"EXAMPLE_ENUM_UNSPECIFIED": 0,
		"EXAMPLE_ENUM_FIRST":       1,
	}
)

func (x ExampleEnum) Enum() *ExampleEnum {
	p := new(ExampleEnum)
	*p = x
	return p
}

func (x ExampleEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExampleEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_oneofenum_oneof_enum_proto_enumTypes[0].Descriptor()
}

func (ExampleEnum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_oneofenum_oneof_enum_proto_enumTypes[0]
}

func (x ExampleEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExampleEnum.Descriptor instead.
func (ExampleEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescGZIP(), []int{0}
}

type OneofEnumMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to One:
	//
	//	*OneofEnumMessage_ExampleEnum
	One           isOneofEnumMessage_One `protobuf_oneof:"one"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofEnumMessage) Reset() {
	*x = OneofEnumMessage{}
	mi := &file_examples_internal_proto_oneofenum_oneof_enum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofEnumMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofEnumMessage) ProtoMessage() {}

func (x *OneofEnumMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_oneofenum_oneof_enum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofEnumMessage.ProtoReflect.Descriptor instead.
func (*OneofEnumMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescGZIP(), []int{0}
}

func (x *OneofEnumMessage) GetOne() isOneofEnumMessage_One {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *OneofEnumMessage) GetExampleEnum() ExampleEnum {
	if x != nil {
		if x, ok := x.One.(*OneofEnumMessage_ExampleEnum); ok {
			return x.ExampleEnum
		}
	}
	return ExampleEnum_EXAMPLE_ENUM_UNSPECIFIED
}

type isOneofEnumMessage_One interface {
	isOneofEnumMessage_One()
}

type OneofEnumMessage_ExampleEnum struct {
	ExampleEnum ExampleEnum `protobuf:"varint,1,opt,name=example_enum,json=exampleEnum,proto3,enum=examples.internal.proto.oneofenum.ExampleEnum,oneof"`
}

func (*OneofEnumMessage_ExampleEnum) isOneofEnumMessage_One() {}

var File_examples_internal_proto_oneofenum_oneof_enum_proto protoreflect.FileDescriptor

const file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDesc = "" +
	"\n" +
	"2examples/internal/proto/oneofenum/oneof_enum.proto\x12!examples.internal.proto.oneofenum\"n\n" +
	"\x10OneofEnumMessage\x12S\n" +
	"\fexample_enum\x18\x01 \x01(\x0e2..examples.internal.proto.oneofenum.ExampleEnumH\x00R\vexampleEnumB\x05\n" +
	"\x03one*C\n" +
	"\vExampleEnum\x12\x1c\n" +
	"\x18EXAMPLE_ENUM_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EXAMPLE_ENUM_FIRST\x10\x01BMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/oneofenumb\x06proto3"

var (
	file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescOnce sync.Once
	file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescData []byte
)

func file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDesc), len(file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDesc)))
	})
	return file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDescData
}

var file_examples_internal_proto_oneofenum_oneof_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_internal_proto_oneofenum_oneof_enum_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_internal_proto_oneofenum_oneof_enum_proto_goTypes = []any{
	(ExampleEnum)(0),         // 0: examples.internal.proto.oneofenum.ExampleEnum
	(*OneofEnumMessage)(nil), // 1: examples.internal.proto.oneofenum.OneofEnumMessage
}
var file_examples_internal_proto_oneofenum_oneof_enum_proto_depIdxs = []int32{
	0, // 0: examples.internal.proto.oneofenum.OneofEnumMessage.example_enum:type_name -> examples.internal.proto.oneofenum.ExampleEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_oneofenum_oneof_enum_proto_init() }
func file_examples_internal_proto_oneofenum_oneof_enum_proto_init() {
	if File_examples_internal_proto_oneofenum_oneof_enum_proto != nil {
		return
	}
	file_examples_internal_proto_oneofenum_oneof_enum_proto_msgTypes[0].OneofWrappers = []any{
		(*OneofEnumMessage_ExampleEnum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDesc), len(file_examples_internal_proto_oneofenum_oneof_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_internal_proto_oneofenum_oneof_enum_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_oneofenum_oneof_enum_proto_depIdxs,
		EnumInfos:         file_examples_internal_proto_oneofenum_oneof_enum_proto_enumTypes,
		MessageInfos:      file_examples_internal_proto_oneofenum_oneof_enum_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_oneofenum_oneof_enum_proto = out.File
	file_examples_internal_proto_oneofenum_oneof_enum_proto_goTypes = nil
	file_examples_internal_proto_oneofenum_oneof_enum_proto_depIdxs = nil
}
