// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/helloworld/helloworld.proto

package helloworld

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StrVal        *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=strVal,proto3" json:"strVal,omitempty"`
	FloatVal      *wrapperspb.FloatValue  `protobuf:"bytes,3,opt,name=floatVal,proto3" json:"floatVal,omitempty"`
	DoubleVal     *wrapperspb.DoubleValue `protobuf:"bytes,4,opt,name=doubleVal,proto3" json:"doubleVal,omitempty"`
	BoolVal       *wrapperspb.BoolValue   `protobuf:"bytes,5,opt,name=boolVal,proto3" json:"boolVal,omitempty"`
	BytesVal      *wrapperspb.BytesValue  `protobuf:"bytes,6,opt,name=bytesVal,proto3" json:"bytesVal,omitempty"`
	Int32Val      *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=int32Val,proto3" json:"int32Val,omitempty"`
	Uint32Val     *wrapperspb.UInt32Value `protobuf:"bytes,8,opt,name=uint32Val,proto3" json:"uint32Val,omitempty"`
	Int64Val      *wrapperspb.Int64Value  `protobuf:"bytes,9,opt,name=int64Val,proto3" json:"int64Val,omitempty"`
	Uint64Val     *wrapperspb.UInt64Value `protobuf:"bytes,10,opt,name=uint64Val,proto3" json:"uint64Val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_examples_internal_helloworld_helloworld_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_helloworld_helloworld_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_helloworld_helloworld_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetStrVal() *wrapperspb.StringValue {
	if x != nil {
		return x.StrVal
	}
	return nil
}

func (x *HelloRequest) GetFloatVal() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatVal
	}
	return nil
}

func (x *HelloRequest) GetDoubleVal() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleVal
	}
	return nil
}

func (x *HelloRequest) GetBoolVal() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolVal
	}
	return nil
}

func (x *HelloRequest) GetBytesVal() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesVal
	}
	return nil
}

func (x *HelloRequest) GetInt32Val() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Val
	}
	return nil
}

func (x *HelloRequest) GetUint32Val() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Val
	}
	return nil
}

func (x *HelloRequest) GetInt64Val() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Val
	}
	return nil
}

func (x *HelloRequest) GetUint64Val() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Val
	}
	return nil
}

type HelloReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloReply) Reset() {
	*x = HelloReply{}
	mi := &file_examples_internal_helloworld_helloworld_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReply) ProtoMessage() {}

func (x *HelloReply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_helloworld_helloworld_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReply.ProtoReflect.Descriptor instead.
func (*HelloReply) Descriptor() ([]byte, []int) {
	return file_examples_internal_helloworld_helloworld_proto_rawDescGZIP(), []int{1}
}

func (x *HelloReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_examples_internal_helloworld_helloworld_proto protoreflect.FileDescriptor

const file_examples_internal_helloworld_helloworld_proto_rawDesc = "" +
	"\n" +
	"-examples/internal/helloworld/helloworld.proto\x12\x1cexamples.internal.helloworld\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa6\x04\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x06strVal\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06strVal\x127\n" +
	"\bfloatVal\x18\x03 \x01(\v2\x1b.google.protobuf.FloatValueR\bfloatVal\x12:\n" +
	"\tdoubleVal\x18\x04 \x01(\v2\x1c.google.protobuf.DoubleValueR\tdoubleVal\x124\n" +
	"\aboolVal\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\aboolVal\x127\n" +
	"\bbytesVal\x18\x06 \x01(\v2\x1b.google.protobuf.BytesValueR\bbytesVal\x127\n" +
	"\bint32Val\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\bint32Val\x12:\n" +
	"\tuint32Val\x18\b \x01(\v2\x1c.google.protobuf.UInt32ValueR\tuint32Val\x127\n" +
	"\bint64Val\x18\t \x01(\v2\x1b.google.protobuf.Int64ValueR\bint64Val\x12:\n" +
	"\tuint64Val\x18\n" +
	" \x01(\v2\x1c.google.protobuf.UInt64ValueR\tuint64Val\"&\n" +
	"\n" +
	"HelloReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xff\x02\n" +
	"\aGreeter\x12\xf3\x02\n" +
	"\bSayHello\x12*.examples.internal.helloworld.HelloRequest\x1a(.examples.internal.helloworld.HelloReply\"\x90\x02\x82\xd3\xe4\x93\x02\x89\x02Z\x16\x12\x14/say/strval/{strVal}Z\x1a\x12\x18/say/floatval/{floatVal}Z\x1c\x12\x1a/say/doubleval/{doubleVal}Z\x18\x12\x16/say/boolval/{boolVal}Z\x1a\x12\x18/say/bytesval/{bytesVal}Z\x1a\x12\x18/say/int32val/{int32Val}Z\x1c\x12\x1a/say/uint32val/{uint32Val}Z\x1a\x12\x18/say/int64val/{int64Val}Z\x1c\x12\x1a/say/uint64val/{uint64Val}\x12\v/say/{name}BHZFgithub.com/essapp/grpc-gateway-example/v2/examples/internal/helloworldb\x06proto3"

var (
	file_examples_internal_helloworld_helloworld_proto_rawDescOnce sync.Once
	file_examples_internal_helloworld_helloworld_proto_rawDescData []byte
)

func file_examples_internal_helloworld_helloworld_proto_rawDescGZIP() []byte {
	file_examples_internal_helloworld_helloworld_proto_rawDescOnce.Do(func() {
		file_examples_internal_helloworld_helloworld_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_helloworld_helloworld_proto_rawDesc), len(file_examples_internal_helloworld_helloworld_proto_rawDesc)))
	})
	return file_examples_internal_helloworld_helloworld_proto_rawDescData
}

var file_examples_internal_helloworld_helloworld_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_internal_helloworld_helloworld_proto_goTypes = []any{
	(*HelloRequest)(nil),           // 0: examples.internal.helloworld.HelloRequest
	(*HelloReply)(nil),             // 1: examples.internal.helloworld.HelloReply
	(*wrapperspb.StringValue)(nil), // 2: google.protobuf.StringValue
	(*wrapperspb.FloatValue)(nil),  // 3: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 4: google.protobuf.DoubleValue
	(*wrapperspb.BoolValue)(nil),   // 5: google.protobuf.BoolValue
	(*wrapperspb.BytesValue)(nil),  // 6: google.protobuf.BytesValue
	(*wrapperspb.Int32Value)(nil),  // 7: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil), // 8: google.protobuf.UInt32Value
	(*wrapperspb.Int64Value)(nil),  // 9: google.protobuf.Int64Value
	(*wrapperspb.UInt64Value)(nil), // 10: google.protobuf.UInt64Value
}
var file_examples_internal_helloworld_helloworld_proto_depIdxs = []int32{
	2,  // 0: examples.internal.helloworld.HelloRequest.strVal:type_name -> google.protobuf.StringValue
	3,  // 1: examples.internal.helloworld.HelloRequest.floatVal:type_name -> google.protobuf.FloatValue
	4,  // 2: examples.internal.helloworld.HelloRequest.doubleVal:type_name -> google.protobuf.DoubleValue
	5,  // 3: examples.internal.helloworld.HelloRequest.boolVal:type_name -> google.protobuf.BoolValue
	6,  // 4: examples.internal.helloworld.HelloRequest.bytesVal:type_name -> google.protobuf.BytesValue
	7,  // 5: examples.internal.helloworld.HelloRequest.int32Val:type_name -> google.protobuf.Int32Value
	8,  // 6: examples.internal.helloworld.HelloRequest.uint32Val:type_name -> google.protobuf.UInt32Value
	9,  // 7: examples.internal.helloworld.HelloRequest.int64Val:type_name -> google.protobuf.Int64Value
	10, // 8: examples.internal.helloworld.HelloRequest.uint64Val:type_name -> google.protobuf.UInt64Value
	0,  // 9: examples.internal.helloworld.Greeter.SayHello:input_type -> examples.internal.helloworld.HelloRequest
	1,  // 10: examples.internal.helloworld.Greeter.SayHello:output_type -> examples.internal.helloworld.HelloReply
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_examples_internal_helloworld_helloworld_proto_init() }
func file_examples_internal_helloworld_helloworld_proto_init() {
	if File_examples_internal_helloworld_helloworld_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_helloworld_helloworld_proto_rawDesc), len(file_examples_internal_helloworld_helloworld_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_helloworld_helloworld_proto_goTypes,
		DependencyIndexes: file_examples_internal_helloworld_helloworld_proto_depIdxs,
		MessageInfos:      file_examples_internal_helloworld_helloworld_proto_msgTypes,
	}.Build()
	File_examples_internal_helloworld_helloworld_proto = out.File
	file_examples_internal_helloworld_helloworld_proto_goTypes = nil
	file_examples_internal_helloworld_helloworld_proto_depIdxs = nil
}
