// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/a_bit_of_everything.proto

package examplepb

import (
	oneofenum "github.com/essapp/grpc-gateway-example/v2/examples/internal/proto/oneofenum"
	pathenum "github.com/essapp/grpc-gateway-example/v2/examples/internal/proto/pathenum"
	sub "github.com/essapp/grpc-gateway-example/v2/examples/internal/proto/sub"
	sub2 "github.com/essapp/grpc-gateway-example/v2/examples/internal/proto/sub2"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NumericEnum is one or zero.
type NumericEnum int32

const (
	// ZERO means 0
	NumericEnum_ZERO NumericEnum = 0
	// ONE means 1
	NumericEnum_ONE NumericEnum = 1
)

// Enum value maps for NumericEnum.
var (
	NumericEnum_name = map[int32]string{
		0: "ZERO",
		1: "ONE",
	}
	NumericEnum_value = map[string]int32{
		"ZERO": 0,
		"ONE":  1,
	}
)

func (x NumericEnum) Enum() *NumericEnum {
	p := new(NumericEnum)
	*p = x
	return p
}

func (x NumericEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NumericEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[0].Descriptor()
}

func (NumericEnum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[0]
}

func (x NumericEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NumericEnum.Descriptor instead.
func (NumericEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{0}
}

// Ignoring lint warnings as this enum type exist to validate proper functionality
// for projects that don't follow these lint rules.
// buf:lint:ignore ENUM_PASCAL_CASE
type SnakeCaseEnum int32

const (
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	SnakeCaseEnum_value_c SnakeCaseEnum = 0
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	SnakeCaseEnum_value_d SnakeCaseEnum = 1
)

// Enum value maps for SnakeCaseEnum.
var (
	SnakeCaseEnum_name = map[int32]string{
		0: "value_c",
		1: "value_d",
	}
	SnakeCaseEnum_value = map[string]int32{
		"value_c": 0,
		"value_d": 1,
	}
)

func (x SnakeCaseEnum) Enum() *SnakeCaseEnum {
	p := new(SnakeCaseEnum)
	*p = x
	return p
}

func (x SnakeCaseEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnakeCaseEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[1].Descriptor()
}

func (SnakeCaseEnum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[1]
}

func (x SnakeCaseEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnakeCaseEnum.Descriptor instead.
func (SnakeCaseEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{1}
}

// Ignoring lint warnings as this enum type exist to validate proper functionality
// for projects that don't follow these lint rules.
// buf:lint:ignore ENUM_PASCAL_CASE
type SnakeCase_0Enum int32

const (
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	SnakeCase_0Enum_value_e SnakeCase_0Enum = 0
	// buf:lint:ignore ENUM_VALUE_UPPER_SNAKE_CASE
	SnakeCase_0Enum_value_f SnakeCase_0Enum = 1
)

// Enum value maps for SnakeCase_0Enum.
var (
	SnakeCase_0Enum_name = map[int32]string{
		0: "value_e",
		1: "value_f",
	}
	SnakeCase_0Enum_value = map[string]int32{
		"value_e": 0,
		"value_f": 1,
	}
)

func (x SnakeCase_0Enum) Enum() *SnakeCase_0Enum {
	p := new(SnakeCase_0Enum)
	*p = x
	return p
}

func (x SnakeCase_0Enum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnakeCase_0Enum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[2].Descriptor()
}

func (SnakeCase_0Enum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[2]
}

func (x SnakeCase_0Enum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnakeCase_0Enum.Descriptor instead.
func (SnakeCase_0Enum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{2}
}

// DeepEnum is one or zero.
type ABitOfEverything_Nested_DeepEnum int32

const (
	// FALSE is false.
	ABitOfEverything_Nested_FALSE ABitOfEverything_Nested_DeepEnum = 0
	// TRUE is true.
	ABitOfEverything_Nested_TRUE ABitOfEverything_Nested_DeepEnum = 1
)

// Enum value maps for ABitOfEverything_Nested_DeepEnum.
var (
	ABitOfEverything_Nested_DeepEnum_name = map[int32]string{
		0: "FALSE",
		1: "TRUE",
	}
	ABitOfEverything_Nested_DeepEnum_value = map[string]int32{
		"FALSE": 0,
		"TRUE":  1,
	}
)

func (x ABitOfEverything_Nested_DeepEnum) Enum() *ABitOfEverything_Nested_DeepEnum {
	p := new(ABitOfEverything_Nested_DeepEnum)
	*p = x
	return p
}

func (x ABitOfEverything_Nested_DeepEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ABitOfEverything_Nested_DeepEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[3].Descriptor()
}

func (ABitOfEverything_Nested_DeepEnum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes[3]
}

func (x ABitOfEverything_Nested_DeepEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ABitOfEverything_Nested_DeepEnum.Descriptor instead.
func (ABitOfEverything_Nested_DeepEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{2, 0, 0}
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlationId,proto3" json:"correlationId,omitempty"`
	Error         *ErrorObject           `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ErrorResponse) GetError() *ErrorObject {
	if x != nil {
		return x.Error
	}
	return nil
}

type ErrorObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorObject) Reset() {
	*x = ErrorObject{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorObject) ProtoMessage() {}

func (x *ErrorObject) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorObject.ProtoReflect.Descriptor instead.
func (*ErrorObject) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorObject) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorObject) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Intentionally complicated message type to cover many features of Protobuf.
type ABitOfEverything struct {
	state               protoimpl.MessageState                  `protogen:"open.v1"`
	SingleNested        *ABitOfEverything_Nested                `protobuf:"bytes,25,opt,name=single_nested,json=singleNested,proto3" json:"single_nested,omitempty"`
	Uuid                string                                  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nested              []*ABitOfEverything_Nested              `protobuf:"bytes,2,rep,name=nested,proto3" json:"nested,omitempty"`
	FloatValue          float32                                 `protobuf:"fixed32,3,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue         float64                                 `protobuf:"fixed64,4,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	Int64Value          int64                                   `protobuf:"varint,5,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value         uint64                                  `protobuf:"varint,6,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Int32Value          int32                                   `protobuf:"varint,7,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Fixed64Value        uint64                                  `protobuf:"fixed64,8,opt,name=fixed64_value,json=fixed64Value,proto3" json:"fixed64_value,omitempty"`
	Fixed32Value        uint32                                  `protobuf:"fixed32,9,opt,name=fixed32_value,json=fixed32Value,proto3" json:"fixed32_value,omitempty"`
	BoolValue           bool                                    `protobuf:"varint,10,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue         string                                  `protobuf:"bytes,11,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue          []byte                                  `protobuf:"bytes,29,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	Uint32Value         uint32                                  `protobuf:"varint,13,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	EnumValue           NumericEnum                             `protobuf:"varint,14,opt,name=enum_value,json=enumValue,proto3,enum=examples.internal.proto.examplepb.NumericEnum" json:"enum_value,omitempty"`
	PathEnumValue       pathenum.PathEnum                       `protobuf:"varint,30,opt,name=path_enum_value,json=pathEnumValue,proto3,enum=examples.internal.pathenum.PathEnum" json:"path_enum_value,omitempty"`
	NestedPathEnumValue pathenum.MessagePathEnum_NestedPathEnum `protobuf:"varint,31,opt,name=nested_path_enum_value,json=nestedPathEnumValue,proto3,enum=examples.internal.pathenum.MessagePathEnum_NestedPathEnum" json:"nested_path_enum_value,omitempty"`
	Sfixed32Value       int32                                   `protobuf:"fixed32,15,opt,name=sfixed32_value,json=sfixed32Value,proto3" json:"sfixed32_value,omitempty"`
	Sfixed64Value       int64                                   `protobuf:"fixed64,16,opt,name=sfixed64_value,json=sfixed64Value,proto3" json:"sfixed64_value,omitempty"`
	Sint32Value         int32                                   `protobuf:"zigzag32,17,opt,name=sint32_value,json=sint32Value,proto3" json:"sint32_value,omitempty"`
	Sint64Value         int64                                   `protobuf:"zigzag64,18,opt,name=sint64_value,json=sint64Value,proto3" json:"sint64_value,omitempty"`
	RepeatedStringValue []string                                `protobuf:"bytes,19,rep,name=repeated_string_value,json=repeatedStringValue,proto3" json:"repeated_string_value,omitempty"`
	// Types that are valid to be assigned to OneofValue:
	//
	//	*ABitOfEverything_OneofEmpty
	//	*ABitOfEverything_OneofString
	OneofValue isABitOfEverything_OneofValue `protobuf_oneof:"oneof_value"`
	// map of numeric enum
	MapValue map[string]NumericEnum `protobuf:"bytes,22,rep,name=map_value,json=mapValue,proto3" json:"map_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=examples.internal.proto.examplepb.NumericEnum"`
	// map of string  (This comment is overridden by the field annotation)
	MappedStringValue        map[string]string                   `protobuf:"bytes,23,rep,name=mapped_string_value,json=mappedStringValue,proto3" json:"mapped_string_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MappedNestedValue        map[string]*ABitOfEverything_Nested `protobuf:"bytes,24,rep,name=mapped_nested_value,json=mappedNestedValue,proto3" json:"mapped_nested_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NonConventionalNameValue string                              `protobuf:"bytes,26,opt,name=nonConventionalNameValue,proto3" json:"nonConventionalNameValue,omitempty"`
	TimestampValue           *timestamppb.Timestamp              `protobuf:"bytes,27,opt,name=timestamp_value,json=timestampValue,proto3" json:"timestamp_value,omitempty"`
	// repeated enum value. it is comma-separated in query
	RepeatedEnumValue []NumericEnum `protobuf:"varint,28,rep,packed,name=repeated_enum_value,json=repeatedEnumValue,proto3,enum=examples.internal.proto.examplepb.NumericEnum" json:"repeated_enum_value,omitempty"`
	// repeated numeric enum comment (This comment is overridden by the field annotation)
	RepeatedEnumAnnotation []NumericEnum `protobuf:"varint,32,rep,packed,name=repeated_enum_annotation,json=repeatedEnumAnnotation,proto3,enum=examples.internal.proto.examplepb.NumericEnum" json:"repeated_enum_annotation,omitempty"`
	// numeric enum comment (This comment is overridden by the field annotation)
	EnumValueAnnotation NumericEnum `protobuf:"varint,33,opt,name=enum_value_annotation,json=enumValueAnnotation,proto3,enum=examples.internal.proto.examplepb.NumericEnum" json:"enum_value_annotation,omitempty"`
	// repeated string comment (This comment is overridden by the field annotation)
	RepeatedStringAnnotation []string `protobuf:"bytes,34,rep,name=repeated_string_annotation,json=repeatedStringAnnotation,proto3" json:"repeated_string_annotation,omitempty"`
	// repeated nested object comment (This comment is overridden by the field annotation)
	RepeatedNestedAnnotation []*ABitOfEverything_Nested `protobuf:"bytes,35,rep,name=repeated_nested_annotation,json=repeatedNestedAnnotation,proto3" json:"repeated_nested_annotation,omitempty"`
	// nested object comments (This comment is overridden by the field annotation)
	NestedAnnotation  *ABitOfEverything_Nested `protobuf:"bytes,36,opt,name=nested_annotation,json=nestedAnnotation,proto3" json:"nested_annotation,omitempty"`
	Int64OverrideType int64                    `protobuf:"varint,37,opt,name=int64_override_type,json=int64OverrideType,proto3" json:"int64_override_type,omitempty"`
	// mark a field as required in Open API definition
	RequiredStringViaFieldBehaviorAnnotation string `protobuf:"bytes,38,opt,name=required_string_via_field_behavior_annotation,json=requiredStringViaFieldBehaviorAnnotation,proto3" json:"required_string_via_field_behavior_annotation,omitempty"`
	// mark a field as readonly in Open API definition
	OutputOnlyStringViaFieldBehaviorAnnotation string  `protobuf:"bytes,39,opt,name=output_only_string_via_field_behavior_annotation,json=outputOnlyStringViaFieldBehaviorAnnotation,proto3" json:"output_only_string_via_field_behavior_annotation,omitempty"`
	OptionalStringValue                        *string `protobuf:"bytes,40,opt,name=optional_string_value,json=optionalStringValue,proto3,oneof" json:"optional_string_value,omitempty"`
	// Test openapiv2 generation of repeated fields
	ProductId []string `protobuf:"bytes,41,rep,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	// Test openapiv2 generation of required fields with annotation and jsonschema to reproduce
	OptionalStringField   string `protobuf:"bytes,42,opt,name=optional_string_field,json=optionalStringField,proto3" json:"optional_string_field,omitempty"`
	RequiredStringField_1 string `protobuf:"bytes,43,opt,name=required_string_field_1,json=requiredStringField1,proto3" json:"required_string_field_1,omitempty"`
	RequiredStringField_2 string `protobuf:"bytes,44,opt,name=required_string_field_2,json=requiredStringField2,proto3" json:"required_string_field_2,omitempty"`
	// Test openapiv2 handling of required json_name fields
	RequiredFieldBehaviorJsonName string `protobuf:"bytes,45,opt,name=required_field_behavior_json_name,json=required_field_behavior_json_name_custom,proto3" json:"required_field_behavior_json_name,omitempty"`
	RequiredFieldSchemaJsonName   string `protobuf:"bytes,46,opt,name=required_field_schema_json_name,json=required_field_schema_json_name_custom,proto3" json:"required_field_schema_json_name,omitempty"`
	TrailingOnly                  string `protobuf:"bytes,47,opt,name=trailing_only,json=trailingOnly,proto3" json:"trailing_only,omitempty"`            // Trailing only
	TrailingOnlyDot               string `protobuf:"bytes,48,opt,name=trailing_only_dot,json=trailingOnlyDot,proto3" json:"trailing_only_dot,omitempty"` // Trailing only dot.
	// Leading both
	TrailingBoth string `protobuf:"bytes,49,opt,name=trailing_both,json=trailingBoth,proto3" json:"trailing_both,omitempty"` // Trailing both.
	// Leading multiline
	//
	// This is an example of a multi-line comment.
	TrailingMultiline string `protobuf:"bytes,50,opt,name=trailing_multiline,json=trailingMultiline,proto3" json:"trailing_multiline,omitempty"` // Trailing multiline.
	// Specify a custom format of repeated field items
	Uuids         []string `protobuf:"bytes,51,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABitOfEverything) Reset() {
	*x = ABitOfEverything{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABitOfEverything) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABitOfEverything) ProtoMessage() {}

func (x *ABitOfEverything) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABitOfEverything.ProtoReflect.Descriptor instead.
func (*ABitOfEverything) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{2}
}

func (x *ABitOfEverything) GetSingleNested() *ABitOfEverything_Nested {
	if x != nil {
		return x.SingleNested
	}
	return nil
}

func (x *ABitOfEverything) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *ABitOfEverything) GetFloatValue() float32 {
	if x != nil {
		return x.FloatValue
	}
	return 0
}

func (x *ABitOfEverything) GetDoubleValue() float64 {
	if x != nil {
		return x.DoubleValue
	}
	return 0
}

func (x *ABitOfEverything) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *ABitOfEverything) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *ABitOfEverything) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *ABitOfEverything) GetFixed64Value() uint64 {
	if x != nil {
		return x.Fixed64Value
	}
	return 0
}

func (x *ABitOfEverything) GetFixed32Value() uint32 {
	if x != nil {
		return x.Fixed32Value
	}
	return 0
}

func (x *ABitOfEverything) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

func (x *ABitOfEverything) GetStringValue() string {
	if x != nil {
		return x.StringValue
	}
	return ""
}

func (x *ABitOfEverything) GetBytesValue() []byte {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

func (x *ABitOfEverything) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *ABitOfEverything) GetEnumValue() NumericEnum {
	if x != nil {
		return x.EnumValue
	}
	return NumericEnum_ZERO
}

func (x *ABitOfEverything) GetPathEnumValue() pathenum.PathEnum {
	if x != nil {
		return x.PathEnumValue
	}
	return pathenum.PathEnum(0)
}

func (x *ABitOfEverything) GetNestedPathEnumValue() pathenum.MessagePathEnum_NestedPathEnum {
	if x != nil {
		return x.NestedPathEnumValue
	}
	return pathenum.MessagePathEnum_NestedPathEnum(0)
}

func (x *ABitOfEverything) GetSfixed32Value() int32 {
	if x != nil {
		return x.Sfixed32Value
	}
	return 0
}

func (x *ABitOfEverything) GetSfixed64Value() int64 {
	if x != nil {
		return x.Sfixed64Value
	}
	return 0
}

func (x *ABitOfEverything) GetSint32Value() int32 {
	if x != nil {
		return x.Sint32Value
	}
	return 0
}

func (x *ABitOfEverything) GetSint64Value() int64 {
	if x != nil {
		return x.Sint64Value
	}
	return 0
}

func (x *ABitOfEverything) GetRepeatedStringValue() []string {
	if x != nil {
		return x.RepeatedStringValue
	}
	return nil
}

func (x *ABitOfEverything) GetOneofValue() isABitOfEverything_OneofValue {
	if x != nil {
		return x.OneofValue
	}
	return nil
}

func (x *ABitOfEverything) GetOneofEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.OneofValue.(*ABitOfEverything_OneofEmpty); ok {
			return x.OneofEmpty
		}
	}
	return nil
}

func (x *ABitOfEverything) GetOneofString() string {
	if x != nil {
		if x, ok := x.OneofValue.(*ABitOfEverything_OneofString); ok {
			return x.OneofString
		}
	}
	return ""
}

func (x *ABitOfEverything) GetMapValue() map[string]NumericEnum {
	if x != nil {
		return x.MapValue
	}
	return nil
}

func (x *ABitOfEverything) GetMappedStringValue() map[string]string {
	if x != nil {
		return x.MappedStringValue
	}
	return nil
}

func (x *ABitOfEverything) GetMappedNestedValue() map[string]*ABitOfEverything_Nested {
	if x != nil {
		return x.MappedNestedValue
	}
	return nil
}

func (x *ABitOfEverything) GetNonConventionalNameValue() string {
	if x != nil {
		return x.NonConventionalNameValue
	}
	return ""
}

func (x *ABitOfEverything) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		return x.TimestampValue
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedEnumValue() []NumericEnum {
	if x != nil {
		return x.RepeatedEnumValue
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedEnumAnnotation() []NumericEnum {
	if x != nil {
		return x.RepeatedEnumAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetEnumValueAnnotation() NumericEnum {
	if x != nil {
		return x.EnumValueAnnotation
	}
	return NumericEnum_ZERO
}

func (x *ABitOfEverything) GetRepeatedStringAnnotation() []string {
	if x != nil {
		return x.RepeatedStringAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetRepeatedNestedAnnotation() []*ABitOfEverything_Nested {
	if x != nil {
		return x.RepeatedNestedAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetNestedAnnotation() *ABitOfEverything_Nested {
	if x != nil {
		return x.NestedAnnotation
	}
	return nil
}

func (x *ABitOfEverything) GetInt64OverrideType() int64 {
	if x != nil {
		return x.Int64OverrideType
	}
	return 0
}

func (x *ABitOfEverything) GetRequiredStringViaFieldBehaviorAnnotation() string {
	if x != nil {
		return x.RequiredStringViaFieldBehaviorAnnotation
	}
	return ""
}

func (x *ABitOfEverything) GetOutputOnlyStringViaFieldBehaviorAnnotation() string {
	if x != nil {
		return x.OutputOnlyStringViaFieldBehaviorAnnotation
	}
	return ""
}

func (x *ABitOfEverything) GetOptionalStringValue() string {
	if x != nil && x.OptionalStringValue != nil {
		return *x.OptionalStringValue
	}
	return ""
}

func (x *ABitOfEverything) GetProductId() []string {
	if x != nil {
		return x.ProductId
	}
	return nil
}

func (x *ABitOfEverything) GetOptionalStringField() string {
	if x != nil {
		return x.OptionalStringField
	}
	return ""
}

func (x *ABitOfEverything) GetRequiredStringField_1() string {
	if x != nil {
		return x.RequiredStringField_1
	}
	return ""
}

func (x *ABitOfEverything) GetRequiredStringField_2() string {
	if x != nil {
		return x.RequiredStringField_2
	}
	return ""
}

func (x *ABitOfEverything) GetRequiredFieldBehaviorJsonName() string {
	if x != nil {
		return x.RequiredFieldBehaviorJsonName
	}
	return ""
}

func (x *ABitOfEverything) GetRequiredFieldSchemaJsonName() string {
	if x != nil {
		return x.RequiredFieldSchemaJsonName
	}
	return ""
}

func (x *ABitOfEverything) GetTrailingOnly() string {
	if x != nil {
		return x.TrailingOnly
	}
	return ""
}

func (x *ABitOfEverything) GetTrailingOnlyDot() string {
	if x != nil {
		return x.TrailingOnlyDot
	}
	return ""
}

func (x *ABitOfEverything) GetTrailingBoth() string {
	if x != nil {
		return x.TrailingBoth
	}
	return ""
}

func (x *ABitOfEverything) GetTrailingMultiline() string {
	if x != nil {
		return x.TrailingMultiline
	}
	return ""
}

func (x *ABitOfEverything) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type isABitOfEverything_OneofValue interface {
	isABitOfEverything_OneofValue()
}

type ABitOfEverything_OneofEmpty struct {
	OneofEmpty *emptypb.Empty `protobuf:"bytes,20,opt,name=oneof_empty,json=oneofEmpty,proto3,oneof"`
}

type ABitOfEverything_OneofString struct {
	OneofString string `protobuf:"bytes,21,opt,name=oneof_string,json=oneofString,proto3,oneof"`
}

func (*ABitOfEverything_OneofEmpty) isABitOfEverything_OneofValue() {}

func (*ABitOfEverything_OneofString) isABitOfEverything_OneofValue() {}

// ABitOfEverythingRepeated is used to validate repeated path parameter functionality
type ABitOfEverythingRepeated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repeated values. they are comma-separated in path
	PathRepeatedFloatValue    []float32     `protobuf:"fixed32,1,rep,packed,name=path_repeated_float_value,json=pathRepeatedFloatValue,proto3" json:"path_repeated_float_value,omitempty"`
	PathRepeatedDoubleValue   []float64     `protobuf:"fixed64,2,rep,packed,name=path_repeated_double_value,json=pathRepeatedDoubleValue,proto3" json:"path_repeated_double_value,omitempty"`
	PathRepeatedInt64Value    []int64       `protobuf:"varint,3,rep,packed,name=path_repeated_int64_value,json=pathRepeatedInt64Value,proto3" json:"path_repeated_int64_value,omitempty"`
	PathRepeatedUint64Value   []uint64      `protobuf:"varint,4,rep,packed,name=path_repeated_uint64_value,json=pathRepeatedUint64Value,proto3" json:"path_repeated_uint64_value,omitempty"`
	PathRepeatedInt32Value    []int32       `protobuf:"varint,5,rep,packed,name=path_repeated_int32_value,json=pathRepeatedInt32Value,proto3" json:"path_repeated_int32_value,omitempty"`
	PathRepeatedFixed64Value  []uint64      `protobuf:"fixed64,6,rep,packed,name=path_repeated_fixed64_value,json=pathRepeatedFixed64Value,proto3" json:"path_repeated_fixed64_value,omitempty"`
	PathRepeatedFixed32Value  []uint32      `protobuf:"fixed32,7,rep,packed,name=path_repeated_fixed32_value,json=pathRepeatedFixed32Value,proto3" json:"path_repeated_fixed32_value,omitempty"`
	PathRepeatedBoolValue     []bool        `protobuf:"varint,8,rep,packed,name=path_repeated_bool_value,json=pathRepeatedBoolValue,proto3" json:"path_repeated_bool_value,omitempty"`
	PathRepeatedStringValue   []string      `protobuf:"bytes,9,rep,name=path_repeated_string_value,json=pathRepeatedStringValue,proto3" json:"path_repeated_string_value,omitempty"`
	PathRepeatedBytesValue    [][]byte      `protobuf:"bytes,10,rep,name=path_repeated_bytes_value,json=pathRepeatedBytesValue,proto3" json:"path_repeated_bytes_value,omitempty"`
	PathRepeatedUint32Value   []uint32      `protobuf:"varint,11,rep,packed,name=path_repeated_uint32_value,json=pathRepeatedUint32Value,proto3" json:"path_repeated_uint32_value,omitempty"`
	PathRepeatedEnumValue     []NumericEnum `protobuf:"varint,12,rep,packed,name=path_repeated_enum_value,json=pathRepeatedEnumValue,proto3,enum=examples.internal.proto.examplepb.NumericEnum" json:"path_repeated_enum_value,omitempty"`
	PathRepeatedSfixed32Value []int32       `protobuf:"fixed32,13,rep,packed,name=path_repeated_sfixed32_value,json=pathRepeatedSfixed32Value,proto3" json:"path_repeated_sfixed32_value,omitempty"`
	PathRepeatedSfixed64Value []int64       `protobuf:"fixed64,14,rep,packed,name=path_repeated_sfixed64_value,json=pathRepeatedSfixed64Value,proto3" json:"path_repeated_sfixed64_value,omitempty"`
	PathRepeatedSint32Value   []int32       `protobuf:"zigzag32,15,rep,packed,name=path_repeated_sint32_value,json=pathRepeatedSint32Value,proto3" json:"path_repeated_sint32_value,omitempty"`
	PathRepeatedSint64Value   []int64       `protobuf:"zigzag64,16,rep,packed,name=path_repeated_sint64_value,json=pathRepeatedSint64Value,proto3" json:"path_repeated_sint64_value,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ABitOfEverythingRepeated) Reset() {
	*x = ABitOfEverythingRepeated{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABitOfEverythingRepeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABitOfEverythingRepeated) ProtoMessage() {}

func (x *ABitOfEverythingRepeated) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABitOfEverythingRepeated.ProtoReflect.Descriptor instead.
func (*ABitOfEverythingRepeated) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{3}
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedFloatValue() []float32 {
	if x != nil {
		return x.PathRepeatedFloatValue
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedDoubleValue() []float64 {
	if x != nil {
		return x.PathRepeatedDoubleValue
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedInt64Value() []int64 {
	if x != nil {
		return x.PathRepeatedInt64Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedUint64Value() []uint64 {
	if x != nil {
		return x.PathRepeatedUint64Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedInt32Value() []int32 {
	if x != nil {
		return x.PathRepeatedInt32Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedFixed64Value() []uint64 {
	if x != nil {
		return x.PathRepeatedFixed64Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedFixed32Value() []uint32 {
	if x != nil {
		return x.PathRepeatedFixed32Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedBoolValue() []bool {
	if x != nil {
		return x.PathRepeatedBoolValue
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedStringValue() []string {
	if x != nil {
		return x.PathRepeatedStringValue
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedBytesValue() [][]byte {
	if x != nil {
		return x.PathRepeatedBytesValue
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedUint32Value() []uint32 {
	if x != nil {
		return x.PathRepeatedUint32Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedEnumValue() []NumericEnum {
	if x != nil {
		return x.PathRepeatedEnumValue
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedSfixed32Value() []int32 {
	if x != nil {
		return x.PathRepeatedSfixed32Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedSfixed64Value() []int64 {
	if x != nil {
		return x.PathRepeatedSfixed64Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedSint32Value() []int32 {
	if x != nil {
		return x.PathRepeatedSint32Value
	}
	return nil
}

func (x *ABitOfEverythingRepeated) GetPathRepeatedSint64Value() []int64 {
	if x != nil {
		return x.PathRepeatedSint64Value
	}
	return nil
}

type CheckStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *status.Status         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckStatusResponse) Reset() {
	*x = CheckStatusResponse{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckStatusResponse) ProtoMessage() {}

func (x *CheckStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckStatusResponse.ProtoReflect.Descriptor instead.
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{4}
}

func (x *CheckStatusResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Body struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Body) Reset() {
	*x = Body{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Body) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Body) ProtoMessage() {}

func (x *Body) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Body.ProtoReflect.Descriptor instead.
func (*Body) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{5}
}

func (x *Body) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MessageWithBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *Body                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWithBody) Reset() {
	*x = MessageWithBody{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWithBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWithBody) ProtoMessage() {}

func (x *MessageWithBody) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWithBody.ProtoReflect.Descriptor instead.
func (*MessageWithBody) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{6}
}

func (x *MessageWithBody) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageWithBody) GetData() *Body {
	if x != nil {
		return x.Data
	}
	return nil
}

// UpdateV2Request request for update includes the message and the update mask
type UpdateV2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Abe   *ABitOfEverything      `protobuf:"bytes,1,opt,name=abe,proto3" json:"abe,omitempty"`
	// The paths to update.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateV2Request) Reset() {
	*x = UpdateV2Request{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateV2Request) ProtoMessage() {}

func (x *UpdateV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateV2Request.ProtoReflect.Descriptor instead.
func (*UpdateV2Request) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateV2Request) GetAbe() *ABitOfEverything {
	if x != nil {
		return x.Abe
	}
	return nil
}

func (x *UpdateV2Request) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// An example resource type from AIP-123 used to test the behavior described in
// the CreateBookRequest message.
//
// See: https://google.aip.dev/123
type Book struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource name of the book.
	//
	// Format: `publishers/{publisher}/books/{book}`
	//
	// Example: `publishers/1257894000000000000/books/my-book`
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Output only. The book's ID.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Output only. Creation time of the book.
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Book) Reset() {
	*x = Book{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Book) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Book) ProtoMessage() {}

func (x *Book) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Book.ProtoReflect.Descriptor instead.
func (*Book) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{8}
}

func (x *Book) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Book) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Book) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// A standard Create message from AIP-133 with a user-specified ID.
// The user-specified ID (the `book_id` field in this example) must become a
// query parameter in the OpenAPI spec.
//
// See: https://google.aip.dev/133#user-specified-ids
type CreateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The publisher in which to create the book.
	//
	// Format: `publishers/{publisher}`
	//
	// Example: `publishers/1257894000000000000`
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// The book to create.
	Book *Book `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	// The ID to use for the book.
	//
	// This must start with an alphanumeric character.
	BookId        string `protobuf:"bytes,3,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBookRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *CreateBookRequest) GetBookId() string {
	if x != nil {
		return x.BookId
	}
	return ""
}

// A standard Update message from AIP-134
//
// See: https://google.aip.dev/134#request-message
type UpdateBookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The book to update.
	//
	// The book's `name` field is used to identify the book to be updated.
	// Format: publishers/{publisher}/books/{book}
	Book *Book `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	// The list of fields to be updated.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	// If set to true, and the book is not found, a new book will be created.
	// In this situation, `update_mask` is ignored.
	AllowMissing  bool `protobuf:"varint,3,opt,name=allow_missing,json=allowMissing,proto3" json:"allow_missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateBookRequest) GetBook() *Book {
	if x != nil {
		return x.Book
	}
	return nil
}

func (x *UpdateBookRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateBookRequest) GetAllowMissing() bool {
	if x != nil {
		return x.AllowMissing
	}
	return false
}

type SnakeEnumRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	What          SnakeCaseEnum               `protobuf:"varint,1,opt,name=what,proto3,enum=examples.internal.proto.examplepb.SnakeCaseEnum" json:"what,omitempty"`
	Who           SnakeCase_0Enum             `protobuf:"varint,2,opt,name=who,proto3,enum=examples.internal.proto.examplepb.SnakeCase_0Enum" json:"who,omitempty"`
	Where         pathenum.SnakeCaseForImport `protobuf:"varint,3,opt,name=where,proto3,enum=examples.internal.pathenum.SnakeCaseForImport" json:"where,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnakeEnumRequest) Reset() {
	*x = SnakeEnumRequest{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnakeEnumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeEnumRequest) ProtoMessage() {}

func (x *SnakeEnumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeEnumRequest.ProtoReflect.Descriptor instead.
func (*SnakeEnumRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{11}
}

func (x *SnakeEnumRequest) GetWhat() SnakeCaseEnum {
	if x != nil {
		return x.What
	}
	return SnakeCaseEnum_value_c
}

func (x *SnakeEnumRequest) GetWho() SnakeCase_0Enum {
	if x != nil {
		return x.Who
	}
	return SnakeCase_0Enum_value_e
}

func (x *SnakeEnumRequest) GetWhere() pathenum.SnakeCaseForImport {
	if x != nil {
		return x.Where
	}
	return pathenum.SnakeCaseForImport(0)
}

type SnakeEnumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnakeEnumResponse) Reset() {
	*x = SnakeEnumResponse{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnakeEnumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnakeEnumResponse) ProtoMessage() {}

func (x *SnakeEnumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnakeEnumResponse.ProtoReflect.Descriptor instead.
func (*SnakeEnumResponse) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{12}
}

// Required message type -> OpenAPI
// https://github.com/grpc-ecosystem/grpc-gateway/issues/2837
type RequiredMessageTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Foo           *Foo                   `protobuf:"bytes,2,opt,name=foo,proto3" json:"foo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequiredMessageTypeRequest) Reset() {
	*x = RequiredMessageTypeRequest{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequiredMessageTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequiredMessageTypeRequest) ProtoMessage() {}

func (x *RequiredMessageTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequiredMessageTypeRequest.ProtoReflect.Descriptor instead.
func (*RequiredMessageTypeRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{13}
}

func (x *RequiredMessageTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequiredMessageTypeRequest) GetFoo() *Foo {
	if x != nil {
		return x.Foo
	}
	return nil
}

type Foo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bar           *Bar                   `protobuf:"bytes,1,opt,name=bar,proto3" json:"bar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo) Reset() {
	*x = Foo{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{14}
}

func (x *Foo) GetBar() *Bar {
	if x != nil {
		return x.Bar
	}
	return nil
}

type Bar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{15}
}

func (x *Bar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Nested is nested type.
type ABitOfEverything_Nested struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is nested field.
	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount uint32 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// DeepEnum comment.
	Ok            ABitOfEverything_Nested_DeepEnum `protobuf:"varint,3,opt,name=ok,proto3,enum=examples.internal.proto.examplepb.ABitOfEverything_Nested_DeepEnum" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ABitOfEverything_Nested) Reset() {
	*x = ABitOfEverything_Nested{}
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ABitOfEverything_Nested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ABitOfEverything_Nested) ProtoMessage() {}

func (x *ABitOfEverything_Nested) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ABitOfEverything_Nested.ProtoReflect.Descriptor instead.
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ABitOfEverything_Nested) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ABitOfEverything_Nested) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ABitOfEverything_Nested) GetOk() ABitOfEverything_Nested_DeepEnum {
	if x != nil {
		return x.Ok
	}
	return ABitOfEverything_Nested_FALSE
}

var File_examples_internal_proto_examplepb_a_bit_of_everything_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDesc = "" +
	"\n" +
	";examples/internal/proto/examplepb/a_bit_of_everything.proto\x12!examples.internal.proto.examplepb\x1a2examples/internal/proto/oneofenum/oneof_enum.proto\x1a0examples/internal/proto/pathenum/path_enum.proto\x1a)examples/internal/proto/sub/message.proto\x1a*examples/internal/proto/sub2/message.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x17google/rpc/status.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb9\x02\n" +
	"\rErrorResponse\x12\xe1\x01\n" +
	"\rcorrelationId\x18\x01 \x01(\tB\xba\x01\x92A\xb6\x01*\x10x-correlation-id2+Unique event identifier for server requestsJ&\"2438ac3c-37eb-4902-adef-ed16b4431030\"\x8a\x01E^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$\xa2\x02\x04uuidR\rcorrelationId\x12D\n" +
	"\x05error\x18\x02 \x01(\v2..examples.internal.proto.examplepb.ErrorObjectR\x05error\"\xa0\x01\n" +
	"\vErrorObject\x12@\n" +
	"\x04code\x18\x01 \x01(\x05B,\x92A)*\x04code2\rResponse code\x8a\x01\a^[0-9]$\xa2\x02\aintegerR\x04code\x12O\n" +
	"\amessage\x18\x02 \x01(\tB5\x92A2*\amessage2\x10Response message\x8a\x01\x14^[a-zA-Z0-9]{1, 32}$R\amessage\"\x8e$\n" +
	"\x10ABitOfEverything\x12_\n" +
	"\rsingle_nested\x18\x19 \x01(\v2:.examples.internal.proto.examplepb.ABitOfEverything.NestedR\fsingleNested\x12\x90\x01\n" +
	"\x04uuid\x18\x01 \x01(\tB|\x92Ay\x80\x01\x01\x8a\x01K[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}\xa2\x02\x04uuid\x82\x03\x10\n" +
	"\n" +
	"x-internal\x12\x02 \x01\xca>\v\xfa\x02\buuidNameR\x04uuid\x12R\n" +
	"\x06nested\x18\x02 \x03(\v2:.examples.internal.proto.examplepb.ABitOfEverything.NestedR\x06nested\x12J\n" +
	"\vfloat_value\x18\x03 \x01(\x02B)\x92A&2\x11Float value field:\x030.2\xd2\x01\vfloat_valueR\n" +
	"floatValue\x12!\n" +
	"\fdouble_value\x18\x04 \x01(\x01R\vdoubleValue\x12\x1f\n" +
	"\vint64_value\x18\x05 \x01(\x03R\n" +
	"int64Value\x12!\n" +
	"\fuint64_value\x18\x06 \x01(\x04R\vuint64Value\x12\x1f\n" +
	"\vint32_value\x18\a \x01(\x05R\n" +
	"int32Value\x12#\n" +
	"\rfixed64_value\x18\b \x01(\x06R\ffixed64Value\x12#\n" +
	"\rfixed32_value\x18\t \x01(\aR\ffixed32Value\x12\x1d\n" +
	"\n" +
	"bool_value\x18\n" +
	" \x01(\bR\tboolValue\x12!\n" +
	"\fstring_value\x18\v \x01(\tR\vstringValue\x12\x1f\n" +
	"\vbytes_value\x18\x1d \x01(\fR\n" +
	"bytesValue\x12!\n" +
	"\fuint32_value\x18\r \x01(\rR\vuint32Value\x12M\n" +
	"\n" +
	"enum_value\x18\x0e \x01(\x0e2..examples.internal.proto.examplepb.NumericEnumR\tenumValue\x12L\n" +
	"\x0fpath_enum_value\x18\x1e \x01(\x0e2$.examples.internal.pathenum.PathEnumR\rpathEnumValue\x12o\n" +
	"\x16nested_path_enum_value\x18\x1f \x01(\x0e2:.examples.internal.pathenum.MessagePathEnum.NestedPathEnumR\x13nestedPathEnumValue\x12%\n" +
	"\x0esfixed32_value\x18\x0f \x01(\x0fR\rsfixed32Value\x12%\n" +
	"\x0esfixed64_value\x18\x10 \x01(\x10R\rsfixed64Value\x12!\n" +
	"\fsint32_value\x18\x11 \x01(\x11R\vsint32Value\x12!\n" +
	"\fsint64_value\x18\x12 \x01(\x12R\vsint64Value\x122\n" +
	"\x15repeated_string_value\x18\x13 \x03(\tR\x13repeatedStringValue\x129\n" +
	"\voneof_empty\x18\x14 \x01(\v2\x16.google.protobuf.EmptyH\x00R\n" +
	"oneofEmpty\x12#\n" +
	"\foneof_string\x18\x15 \x01(\tH\x00R\voneofString\x12^\n" +
	"\tmap_value\x18\x16 \x03(\v2A.examples.internal.proto.examplepb.ABitOfEverything.MapValueEntryR\bmapValue\x12\xb0\x01\n" +
	"\x13mapped_string_value\x18\x17 \x03(\v2J.examples.internal.proto.examplepb.ABitOfEverything.MappedStringValueEntryB4\x92A1*\x13Map of string title2\x1aMap of string description.R\x11mappedStringValue\x12z\n" +
	"\x13mapped_nested_value\x18\x18 \x03(\v2J.examples.internal.proto.examplepb.ABitOfEverything.MappedNestedValueEntryR\x11mappedNestedValue\x12:\n" +
	"\x18nonConventionalNameValue\x18\x1a \x01(\tR\x18nonConventionalNameValue\x12C\n" +
	"\x0ftimestamp_value\x18\x1b \x01(\v2\x1a.google.protobuf.TimestampR\x0etimestampValue\x12^\n" +
	"\x13repeated_enum_value\x18\x1c \x03(\x0e2..examples.internal.proto.examplepb.NumericEnumR\x11repeatedEnumValue\x12\xae\x01\n" +
	"\x18repeated_enum_annotation\x18  \x03(\x0e2..examples.internal.proto.examplepb.NumericEnumBD\x92AA*\x1bRepeated numeric enum title2\"Repeated numeric enum description.R\x16repeatedEnumAnnotation\x12\x96\x01\n" +
	"\x15enum_value_annotation\x18! \x01(\x0e2..examples.internal.proto.examplepb.NumericEnumB2\x92A/*\x12Numeric enum title2\x19Numeric enum description.R\x13enumValueAnnotation\x12v\n" +
	"\x1arepeated_string_annotation\x18\" \x03(\tB8\x92A5*\x15Repeated string title2\x1cRepeated string description.R\x18repeatedStringAnnotation\x12\xc0\x01\n" +
	"\x1arepeated_nested_annotation\x18# \x03(\v2:.examples.internal.proto.examplepb.ABitOfEverything.NestedBF\x92AC*\x1cRepeated nested object title2#Repeated nested object description.R\x18repeatedNestedAnnotation\x12\x9d\x01\n" +
	"\x11nested_annotation\x18$ \x01(\v2:.examples.internal.proto.examplepb.ABitOfEverything.NestedB4\x92A1*\x13Nested object title2\x1aNested object description.R\x10nestedAnnotation\x127\n" +
	"\x13int64_override_type\x18% \x01(\x03B\a\x92A\x04\x9a\x02\x01\x03R\x11int64OverrideType\x12d\n" +
	"-required_string_via_field_behavior_annotation\x18& \x01(\tB\x03\xe0A\x02R(requiredStringViaFieldBehaviorAnnotation\x12i\n" +
	"0output_only_string_via_field_behavior_annotation\x18' \x01(\tB\x03\xe0A\x03R*outputOnlyStringViaFieldBehaviorAnnotation\x127\n" +
	"\x15optional_string_value\x18( \x01(\tH\x01R\x13optionalStringValue\x88\x01\x01\x12L\n" +
	"\n" +
	"product_id\x18) \x03(\tB-\x92A*2\x18Only digits are allowed.x\x13\x80\x01\x01\x8a\x01\b^[0-9]+$R\tproductId\x122\n" +
	"\x15optional_string_field\x18* \x01(\tR\x13optionalStringField\x12:\n" +
	"\x17required_string_field_1\x18+ \x01(\tB\x03\xe0A\x02R\x14requiredStringField1\x12:\n" +
	"\x17required_string_field_2\x18, \x01(\tB\x03\xe0A\x02R\x14requiredStringField2\x12X\n" +
	"!required_field_behavior_json_name\x18- \x01(\tB\x03\xe0A\x02R(required_field_behavior_json_name_custom\x12O\n" +
	"\x1frequired_field_schema_json_name\x18. \x01(\tR&required_field_schema_json_name_custom\x12#\n" +
	"\rtrailing_only\x18/ \x01(\tR\ftrailingOnly\x12*\n" +
	"\x11trailing_only_dot\x180 \x01(\tR\x0ftrailingOnlyDot\x12#\n" +
	"\rtrailing_both\x181 \x01(\tR\ftrailingBoth\x12-\n" +
	"\x12trailing_multiline\x182 \x01(\tR\x11trailingMultiline\x12 \n" +
	"\x05uuids\x183 \x03(\tB\n" +
	"\x92A\a\xa2\x02\x04uuidR\x05uuids\x1a\xdb\x01\n" +
	"\x06Nested\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\rR\x06amount\x12o\n" +
	"\x02ok\x18\x03 \x01(\x0e2C.examples.internal.proto.examplepb.ABitOfEverything.Nested.DeepEnumB\x1a\x92A\x172\x15DeepEnum description.R\x02ok\"\x1f\n" +
	"\bDeepEnum\x12\t\n" +
	"\x05FALSE\x10\x00\x12\b\n" +
	"\x04TRUE\x10\x01:\x13\x92A\x102\x0e{\"ok\": \"TRUE\"}\x1ak\n" +
	"\rMapValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\x0e2..examples.internal.proto.examplepb.NumericEnumR\x05value:\x028\x01\x1aD\n" +
	"\x16MappedStringValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a\x80\x01\n" +
	"\x16MappedNestedValueEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12P\n" +
	"\x05value\x18\x02 \x01(\v2:.examples.internal.proto.examplepb.ABitOfEverything.NestedR\x05value:\x028\x01:\xd6\x02\x92A\xd2\x02\n" +
	"\xcc\x01*\x13A bit of everything2JIntentionally complicated message type to cover many features of Protobuf.\xd2\x01\x04uuid\xd2\x01\vint64_value\xd2\x01\fdouble_value\xd2\x01\x1frequired_field_schema_json_name\x82\x03\"\n" +
	"\x19x-a-bit-of-everything-foo\x12\x05\x1a\x03bar*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gateway2){\"int64_value\": 12, \"double_value\": 12.3}B\r\n" +
	"\voneof_valueB\x18\n" +
	"\x16_optional_string_value\"\xfc\b\n" +
	"\x18ABitOfEverythingRepeated\x129\n" +
	"\x19path_repeated_float_value\x18\x01 \x03(\x02R\x16pathRepeatedFloatValue\x12;\n" +
	"\x1apath_repeated_double_value\x18\x02 \x03(\x01R\x17pathRepeatedDoubleValue\x129\n" +
	"\x19path_repeated_int64_value\x18\x03 \x03(\x03R\x16pathRepeatedInt64Value\x12;\n" +
	"\x1apath_repeated_uint64_value\x18\x04 \x03(\x04R\x17pathRepeatedUint64Value\x129\n" +
	"\x19path_repeated_int32_value\x18\x05 \x03(\x05R\x16pathRepeatedInt32Value\x12=\n" +
	"\x1bpath_repeated_fixed64_value\x18\x06 \x03(\x06R\x18pathRepeatedFixed64Value\x12=\n" +
	"\x1bpath_repeated_fixed32_value\x18\a \x03(\aR\x18pathRepeatedFixed32Value\x127\n" +
	"\x18path_repeated_bool_value\x18\b \x03(\bR\x15pathRepeatedBoolValue\x12;\n" +
	"\x1apath_repeated_string_value\x18\t \x03(\tR\x17pathRepeatedStringValue\x129\n" +
	"\x19path_repeated_bytes_value\x18\n" +
	" \x03(\fR\x16pathRepeatedBytesValue\x12;\n" +
	"\x1apath_repeated_uint32_value\x18\v \x03(\rR\x17pathRepeatedUint32Value\x12g\n" +
	"\x18path_repeated_enum_value\x18\f \x03(\x0e2..examples.internal.proto.examplepb.NumericEnumR\x15pathRepeatedEnumValue\x12?\n" +
	"\x1cpath_repeated_sfixed32_value\x18\r \x03(\x0fR\x19pathRepeatedSfixed32Value\x12?\n" +
	"\x1cpath_repeated_sfixed64_value\x18\x0e \x03(\x10R\x19pathRepeatedSfixed64Value\x12;\n" +
	"\x1apath_repeated_sint32_value\x18\x0f \x03(\x11R\x17pathRepeatedSint32Value\x12;\n" +
	"\x1apath_repeated_sint64_value\x18\x10 \x03(\x12R\x17pathRepeatedSint64Value:d\x92Aa2_{\"path_repeated_bool_value\": [true, true, false, true], \"path_repeated_int32_value\": [1, 2, 3]}\"A\n" +
	"\x13CheckStatusResponse\x12*\n" +
	"\x06status\x18\x01 \x01(\v2\x12.google.rpc.StatusR\x06status\"\x1a\n" +
	"\x04Body\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"^\n" +
	"\x0fMessageWithBody\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\x04data\x18\x02 \x01(\v2'.examples.internal.proto.examplepb.BodyR\x04data\"\x95\x01\n" +
	"\x0fUpdateV2Request\x12E\n" +
	"\x03abe\x18\x01 \x01(\v23.examples.internal.proto.examplepb.ABitOfEverythingR\x03abe\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"g\n" +
	"\x04Book\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\x86\x01\n" +
	"\x11CreateBookRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12@\n" +
	"\x04book\x18\x02 \x01(\v2'.examples.internal.proto.examplepb.BookB\x03\xe0A\x02R\x04book\x12\x17\n" +
	"\abook_id\x18\x03 \x01(\tR\x06bookId\"\xb7\x01\n" +
	"\x11UpdateBookRequest\x12@\n" +
	"\x04book\x18\x01 \x01(\v2'.examples.internal.proto.examplepb.BookB\x03\xe0A\x02R\x04book\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12#\n" +
	"\rallow_missing\x18\x03 \x01(\bR\fallowMissing\"\xeb\x01\n" +
	"\x10SnakeEnumRequest\x12F\n" +
	"\x04what\x18\x01 \x01(\x0e22.examples.internal.proto.examplepb.snake_case_enumR\x04what\x12F\n" +
	"\x03who\x18\x02 \x01(\x0e24.examples.internal.proto.examplepb.snake_case_0_enumR\x03who\x12G\n" +
	"\x05where\x18\x03 \x01(\x0e21.examples.internal.pathenum.snake_case_for_importR\x05where\"\x13\n" +
	"\x11SnakeEnumResponse\"p\n" +
	"\x1aRequiredMessageTypeRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12=\n" +
	"\x03foo\x18\x02 \x01(\v2&.examples.internal.proto.examplepb.FooB\x03\xe0A\x02R\x03foo\"D\n" +
	"\x03Foo\x12=\n" +
	"\x03bar\x18\x01 \x01(\v2&.examples.internal.proto.examplepb.BarB\x03\xe0A\x02R\x03bar\"\x1a\n" +
	"\x03Bar\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id*\xd5\x01\n" +
	"\vNumericEnum\x12\b\n" +
	"\x04ZERO\x10\x00\x12\a\n" +
	"\x03ONE\x10\x01\x1a\xb2\x01\x92A\xae\x01\n" +
	"\x1bNumericEnum is one or zero.\x1a\vNumericEnum2V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gateway:\x06\"ZERO\"J\"\n" +
	"\x19x-a-bit-of-everything-foo\x12\x05\x1a\x03bar*+\n" +
	"\x0fsnake_case_enum\x12\v\n" +
	"\avalue_c\x10\x00\x12\v\n" +
	"\avalue_d\x10\x01*-\n" +
	"\x11snake_case_0_enum\x12\v\n" +
	"\avalue_e\x10\x00\x12\v\n" +
	"\avalue_f\x10\x012\xc13\n" +
	"\x17ABitOfEverythingService\x12\xf2\x03\n" +
	"\x06Create\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"\xfd\x02\x82\xd3\xe4\x93\x02\xf6\x02\"\xf3\x02/v1/example/a_bit_of_everything/{float_value}/{double_value}/{int64_value}/separator/{uint64_value}/{int32_value}/{fixed64_value}/{fixed32_value}/{bool_value}/{string_value=strprefix/*}/{uint32_value}/{sfixed32_value}/{sfixed64_value}/{sint32_value}/{sint64_value}/{nonConventionalNameValue}/{enum_value}/{path_enum_value}/{nested_path_enum_value}/{enum_value_annotation}\x12\xa2\x01\n" +
	"\n" +
	"CreateBody\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/example/a_bit_of_everything\x12\x9a\x01\n" +
	"\n" +
	"CreateBook\x124.examples.internal.proto.examplepb.CreateBookRequest\x1a'.examples.internal.proto.examplepb.Book\"-\x82\xd3\xe4\x93\x02':\x04book\"\x1f/v1/{parent=publishers/*}/books\x12\x9f\x01\n" +
	"\n" +
	"UpdateBook\x124.examples.internal.proto.examplepb.UpdateBookRequest\x1a'.examples.internal.proto.examplepb.Book\"2\x82\xd3\xe4\x93\x02,:\x04book2$/v1/{book.name=publishers/*/books/*}\x12\x96\x01\n" +
	"\x06Lookup\x12'.examples.internal.proto.sub2.IdMessage\x1a3.examples.internal.proto.examplepb.ABitOfEverything\".\x82\xd3\xe4\x93\x02(\x12&/v1/example/a_bit_of_everything/{uuid}\x12\xa9\x01\n" +
	"\x06Custom\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"5\x82\xd3\xe4\x93\x02/\"-/v1/example/a_bit_of_everything/{uuid}:custom\x12\xb5\x01\n" +
	"\vDoubleColon\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"<\x82\xd3\xe4\x93\x026\"4/v1/example/a_bit_of_everything/{uuid}:custom:custom\x12\x88\x01\n" +
	"\x06Update\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a\x16.google.protobuf.Empty\"1\x82\xd3\xe4\x93\x02+:\x01*\x1a&/v1/example/a_bit_of_everything/{uuid}\x12\xf6\x01\n" +
	"\bUpdateV2\x122.examples.internal.proto.examplepb.UpdateV2Request\x1a\x16.google.protobuf.Empty\"\x9d\x01\x82\xd3\xe4\x93\x02\x96\x01:\x03abeZ1:\x03abe2*/v2/example/a_bit_of_everything/{abe.uuid}Z0:\x01*2+/v2a/example/a_bit_of_everything/{abe.uuid}\x1a*/v2/example/a_bit_of_everything/{abe.uuid}\x12\xbd\x01\n" +
	"\x06Delete\x12'.examples.internal.proto.sub2.IdMessage\x1a\x16.google.protobuf.Empty\"r\x92AAb)\n" +
	"\x0e\n" +
	"\n" +
	"ApiKeyAuth\x12\x00\n" +
	"\x17\n" +
	"\x06OAuth2\x12\r\n" +
	"\x04read\n" +
	"\x05writej\x14\n" +
	"\x0ex-irreversible\x12\x02 \x01\x82\xd3\xe4\x93\x02(*&/v1/example/a_bit_of_everything/{uuid}\x12\xe5\x01\n" +
	"\bGetQuery\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a\x16.google.protobuf.Empty\"\x8b\x01\x92AT\"N\n" +
	"\x1cFind out more about GetQuery\x12.https://github.com/grpc-ecosystem/grpc-gatewayX\x01b\x00\x82\xd3\xe4\x93\x02.\x12,/v1/example/a_bit_of_everything/query/{uuid}\x12\x8f\x05\n" +
	"\x10GetRepeatedQuery\x12;.examples.internal.proto.examplepb.ABitOfEverythingRepeated\x1a;.examples.internal.proto.examplepb.ABitOfEverythingRepeated\"\x80\x04\x82\xd3\xe4\x93\x02\xf9\x03\x12\xf6\x03/v1/example/a_bit_of_everything_repeated/{path_repeated_float_value}/{path_repeated_double_value}/{path_repeated_int64_value}/{path_repeated_uint64_value}/{path_repeated_int32_value}/{path_repeated_fixed64_value}/{path_repeated_fixed32_value}/{path_repeated_bool_value}/{path_repeated_string_value}/{path_repeated_bytes_value}/{path_repeated_uint32_value}/{path_repeated_enum_value}/{path_repeated_sfixed32_value}/{path_repeated_sfixed64_value}/{path_repeated_sint32_value}/{path_repeated_sint64_value}\x12\x8d\x04\n" +
	"\x04Echo\x12*.examples.internal.proto.sub.StringMessage\x1a*.examples.internal.proto.sub.StringMessage\"\xac\x03\x92A\xc5\x02\n" +
	"\becho rpc\x12\x11Summary: Echo rpc\x1a\x10Description Echo\"D\n" +
	"\x12Find out more Echo\x12.https://github.com/grpc-ecosystem/grpc-gatewayJ9\n" +
	"\x03200\x122\"0\n" +
	"\x10application/json\x12\x1c{\"value\": \"the input value\"}J;\n" +
	"\x03404\x124\n" +
	"*Returned when the resource does not exist.\x12\x06\n" +
	"\x04\x9a\x02\x01\x03JV\n" +
	"\x03503\x12O\n" +
	"6Returned when the resource is temporarily unavailable.*\x15\n" +
	"\bx-number\x12\t\x11\x00\x00\x00\x00\x00\x00Y@\x82\xd3\xe4\x93\x02]Z\x19:\x05value\"\x10/v2/example/echoZ\x12\x12\x10/v2/example/echo\x12,/v1/example/a_bit_of_everything/echo/{value}\x12\xaf\x01\n" +
	"\fDeepPathEcho\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/example/deep_path/{single_nested.name}\x12A\n" +
	"\n" +
	"NoBindings\x12\x19.google.protobuf.Duration\x1a\x16.google.protobuf.Empty\"\x00\x12V\n" +
	"\aTimeout\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v2/example/timeout\x12h\n" +
	"\x10ErrorWithDetails\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v2/example/errorwithdetails\x12\x89\x01\n" +
	"\x12GetMessageWithBody\x122.examples.internal.proto.examplepb.MessageWithBody\x1a\x16.google.protobuf.Empty\"'\x82\xd3\xe4\x93\x02!:\x04data\"\x19/v2/example/withbody/{id}\x12\x85\x01\n" +
	"\x11PostWithEmptyBody\x12'.examples.internal.proto.examplepb.Body\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v2/example/postwithemptybody/{name}\x12\xc8\x01\n" +
	"\x13CheckGetQueryParams\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"G\x82\xd3\xe4\x93\x02A\x12?/v1/example/a_bit_of_everything/params/get/{single_nested.name}\x12\xdc\x01\n" +
	"\x1dCheckNestedEnumGetQueryParams\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"Q\x82\xd3\xe4\x93\x02K\x12I/v1/example/a_bit_of_everything/params/get/nested_enum/{single_nested.ok}\x12\xd3\x01\n" +
	"\x14CheckPostQueryParams\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"Q\x82\xd3\xe4\x93\x02K:\rsingle_nested\":/v1/example/a_bit_of_everything/params/post/{string_value}\x12\xad\x01\n" +
	"\x1bOverwriteRequestContentType\x12'.examples.internal.proto.examplepb.Body\x1a\x16.google.protobuf.Empty\"M\x92A\x182\x16application/x-bar-mime\x82\xd3\xe4\x93\x02,:\x01*\"'/v2/example/overwriterequestcontenttype\x12\x9b\x01\n" +
	"\x1cOverwriteResponseContentType\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.StringValue\"E\x92A\x12:\x10application/text\x82\xd3\xe4\x93\x02*\x12(/v2/example/overwriteresponsecontenttype\x12{\n" +
	"\x15CheckExternalPathEnum\x12/.examples.internal.pathenum.MessageWithPathEnum\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v2/{value}:check\x12\x87\x01\n" +
	"\x1bCheckExternalNestedPathEnum\x125.examples.internal.pathenum.MessageWithNestedPathEnum\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v3/{value}:check\x12~\n" +
	"\vCheckStatus\x12\x16.google.protobuf.Empty\x1a6.examples.internal.proto.examplepb.CheckStatusResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/example/checkStatus\x12\x8d\x01\n" +
	"\x06Exists\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a\x16.google.protobuf.Empty\"6\x82\xd3\xe4\x93\x020B.\n" +
	"\x04HEAD\x12&/v1/example/a_bit_of_everything/{uuid}\x12\x9e\x01\n" +
	"\x14CustomOptionsRequest\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a\x16.google.protobuf.Empty\"9\x82\xd3\xe4\x93\x023B1\n" +
	"\aOPTIONS\x12&/v1/example/a_bit_of_everything/{uuid}\x12\xb1\x01\n" +
	"\fTraceRequest\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"7\x82\xd3\xe4\x93\x021B/\n" +
	"\x05TRACE\x12&/v1/example/a_bit_of_everything/{uuid}\x12\x89\x01\n" +
	"\rPostOneofEnum\x123.examples.internal.proto.oneofenum.OneofEnumMessage\x1a\x16.google.protobuf.Empty\"+\x82\xd3\xe4\x93\x02%:\fexample_enum\"\x15/v1/example/oneofenum\x12\x9c\x01\n" +
	"\x17PostRequiredMessageType\x12=.examples.internal.proto.examplepb.RequiredMessageTypeRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/example/requiredmessagetype\x1a\xd1\x01\x92A\xcd\x01\n" +
	"\x10ABitOfEverything\x12fABitOfEverythingService description -- which should not be used in place of the documentation comment!\x1aQ\n" +
	"\x1fFind out more about EchoService\x12.https://github.com/grpc-ecosystem/grpc-gateway2j\n" +
	"\x14camelCaseServiceName\x12R\n" +
	"\x05Empty\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v2/example/empty2^\n" +
	"\x1cAnotherServiceWithNoBindings\x12>\n" +
	"\n" +
	"NoBindings\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x002\xbb\x01\n" +
	"\x10SnakeEnumService\x12\xa6\x01\n" +
	"\tSnakeEnum\x123.examples.internal.proto.examplepb.SnakeEnumRequest\x1a4.examples.internal.proto.examplepb.SnakeEnumResponse\".\x82\xd3\xe4\x93\x02(\x12&/v1/example/snake/{who}/{what}/{where}B\xb5\f\x92A\xe4\v\x12\xf0\x01\n" +
	"\x13A Bit of Everything\"X\n" +
	"\x14gRPC-Gateway project\x12.https://github.com/grpc-ecosystem/grpc-gateway\x1a\x10none@example.com*X\n" +
	"\x14BSD 3-Clause License\x12@https://github.com/grpc-ecosystem/grpc-gateway/blob/main/LICENSE2\x031.0: \n" +
	"\x15x-something-something\x12\a\x1a\x05yadda*\x03\x01\x02\x042\x10application/json2\x16application/x-foo-mime:\x10application/json:\x16application/x-foo-mimeRP\n" +
	"\x03403\x12I\n" +
	"GReturned when the user does not have permission to access the resource.R;\n" +
	"\x03404\x124\n" +
	"*Returned when the resource does not exist.\x12\x06\n" +
	"\x04\x9a\x02\x01\aRJ\n" +
	"\x03418\x12C\n" +
	"\rI'm a teapot.\x122\n" +
	"0\x1a..examples.internal.proto.examplepb.NumericEnumR\x8e\x02\n" +
	"\x03500\x12\x86\x02\n" +
	"\fServer error\x124\n" +
	"2\x1a0.examples.internal.proto.examplepb.ErrorResponse\x1a\xbf\x01\n" +
	"\x10X-Correlation-Id\x12\xaa\x01\n" +
	"+Unique event identifier for server requests\x12\x06string\x1a\x04uuid2&\"2438ac3c-37eb-4902-adef-ed16b4431030\"jE^[0-9A-F]{8}-[0-9A-F]{4}-4[0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$Z\x97\x03\n" +
	"\xaa\x01\n" +
	"\n" +
	"ApiKeyAuth\x12\x9b\x01\b\x02\x1a\tX-API-Key \x02J`\n" +
	"\x1ex-amazon-apigateway-authorizer\x12>*<\n" +
	")\n" +
	"\x1cauthorizerResultTtlInSeconds\x12\t\x11\x00\x00\x00\x00\x00\x00N@\n" +
	"\x0f\n" +
	"\x04type\x12\a\x1a\x05tokenJ(\n" +
	"\x1cx-amazon-apigateway-authtype\x12\b\x1a\x06oauth2\n" +
	"\x0f\n" +
	"\tBasicAuth\x12\x02\b\x01\n" +
	"\xd6\x01\n" +
	"\x06OAuth2\x12\xcb\x01\b\x03(\x042#https://example.com/oauth/authorize:\x1fhttps://example.com/oauth/tokenB\x7f\n" +
	"C\n" +
	"\x05admin\x12:Grants read and write access to administrative information\n" +
	"\x1a\n" +
	"\x04read\x12\x12Grants read access\n" +
	"\x1c\n" +
	"\x05write\x12\x13Grants write accessb\x1f\n" +
	"\x0e\n" +
	"\n" +
	"ApiKeyAuth\x12\x00\n" +
	"\r\n" +
	"\tBasicAuth\x12\x00b)\n" +
	"\x0e\n" +
	"\n" +
	"ApiKeyAuth\x12\x00\n" +
	"\x17\n" +
	"\x06OAuth2\x12\r\n" +
	"\x04read\n" +
	"\x05writej2\n" +
	"\becho rpc\x12\x14Echo Rpc description\"\x10\n" +
	"\n" +
	"x-traitTag\x12\x02 \x01rI\n" +
	"\x17More about gRPC-Gateway\x12.https://github.com/grpc-ecosystem/grpc-gatewayz(\n" +
	"\x17x-grpc-gateway-baz-list\x12\r2\v\n" +
	"\x05\x1a\x03one\n" +
	"\x02 \x01z\x1b\n" +
	"\x12x-grpc-gateway-foo\x12\x05\x1a\x03barZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDesc), len(file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDescData
}

var file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_examples_internal_proto_examplepb_a_bit_of_everything_proto_goTypes = []any{
	(NumericEnum)(0),                      // 0: examples.internal.proto.examplepb.NumericEnum
	(SnakeCaseEnum)(0),                    // 1: examples.internal.proto.examplepb.snake_case_enum
	(SnakeCase_0Enum)(0),                  // 2: examples.internal.proto.examplepb.snake_case_0_enum
	(ABitOfEverything_Nested_DeepEnum)(0), // 3: examples.internal.proto.examplepb.ABitOfEverything.Nested.DeepEnum
	(*ErrorResponse)(nil),                 // 4: examples.internal.proto.examplepb.ErrorResponse
	(*ErrorObject)(nil),                   // 5: examples.internal.proto.examplepb.ErrorObject
	(*ABitOfEverything)(nil),              // 6: examples.internal.proto.examplepb.ABitOfEverything
	(*ABitOfEverythingRepeated)(nil),      // 7: examples.internal.proto.examplepb.ABitOfEverythingRepeated
	(*CheckStatusResponse)(nil),           // 8: examples.internal.proto.examplepb.CheckStatusResponse
	(*Body)(nil),                          // 9: examples.internal.proto.examplepb.Body
	(*MessageWithBody)(nil),               // 10: examples.internal.proto.examplepb.MessageWithBody
	(*UpdateV2Request)(nil),               // 11: examples.internal.proto.examplepb.UpdateV2Request
	(*Book)(nil),                          // 12: examples.internal.proto.examplepb.Book
	(*CreateBookRequest)(nil),             // 13: examples.internal.proto.examplepb.CreateBookRequest
	(*UpdateBookRequest)(nil),             // 14: examples.internal.proto.examplepb.UpdateBookRequest
	(*SnakeEnumRequest)(nil),              // 15: examples.internal.proto.examplepb.SnakeEnumRequest
	(*SnakeEnumResponse)(nil),             // 16: examples.internal.proto.examplepb.SnakeEnumResponse
	(*RequiredMessageTypeRequest)(nil),    // 17: examples.internal.proto.examplepb.RequiredMessageTypeRequest
	(*Foo)(nil),                           // 18: examples.internal.proto.examplepb.Foo
	(*Bar)(nil),                           // 19: examples.internal.proto.examplepb.Bar
	(*ABitOfEverything_Nested)(nil),       // 20: examples.internal.proto.examplepb.ABitOfEverything.Nested
	nil,                                   // 21: examples.internal.proto.examplepb.ABitOfEverything.MapValueEntry
	nil,                                   // 22: examples.internal.proto.examplepb.ABitOfEverything.MappedStringValueEntry
	nil,                                   // 23: examples.internal.proto.examplepb.ABitOfEverything.MappedNestedValueEntry
	(pathenum.PathEnum)(0),                // 24: examples.internal.pathenum.PathEnum
	(pathenum.MessagePathEnum_NestedPathEnum)(0), // 25: examples.internal.pathenum.MessagePathEnum.NestedPathEnum
	(*emptypb.Empty)(nil),                        // 26: google.protobuf.Empty
	(*timestamppb.Timestamp)(nil),                // 27: google.protobuf.Timestamp
	(*status.Status)(nil),                        // 28: google.rpc.Status
	(*fieldmaskpb.FieldMask)(nil),                // 29: google.protobuf.FieldMask
	(pathenum.SnakeCaseForImport)(0),             // 30: examples.internal.pathenum.snake_case_for_import
	(*sub2.IdMessage)(nil),                       // 31: examples.internal.proto.sub2.IdMessage
	(*sub.StringMessage)(nil),                    // 32: examples.internal.proto.sub.StringMessage
	(*durationpb.Duration)(nil),                  // 33: google.protobuf.Duration
	(*pathenum.MessageWithPathEnum)(nil),         // 34: examples.internal.pathenum.MessageWithPathEnum
	(*pathenum.MessageWithNestedPathEnum)(nil),   // 35: examples.internal.pathenum.MessageWithNestedPathEnum
	(*oneofenum.OneofEnumMessage)(nil),           // 36: examples.internal.proto.oneofenum.OneofEnumMessage
	(*wrapperspb.StringValue)(nil),               // 37: google.protobuf.StringValue
}
var file_examples_internal_proto_examplepb_a_bit_of_everything_proto_depIdxs = []int32{
	5,  // 0: examples.internal.proto.examplepb.ErrorResponse.error:type_name -> examples.internal.proto.examplepb.ErrorObject
	20, // 1: examples.internal.proto.examplepb.ABitOfEverything.single_nested:type_name -> examples.internal.proto.examplepb.ABitOfEverything.Nested
	20, // 2: examples.internal.proto.examplepb.ABitOfEverything.nested:type_name -> examples.internal.proto.examplepb.ABitOfEverything.Nested
	0,  // 3: examples.internal.proto.examplepb.ABitOfEverything.enum_value:type_name -> examples.internal.proto.examplepb.NumericEnum
	24, // 4: examples.internal.proto.examplepb.ABitOfEverything.path_enum_value:type_name -> examples.internal.pathenum.PathEnum
	25, // 5: examples.internal.proto.examplepb.ABitOfEverything.nested_path_enum_value:type_name -> examples.internal.pathenum.MessagePathEnum.NestedPathEnum
	26, // 6: examples.internal.proto.examplepb.ABitOfEverything.oneof_empty:type_name -> google.protobuf.Empty
	21, // 7: examples.internal.proto.examplepb.ABitOfEverything.map_value:type_name -> examples.internal.proto.examplepb.ABitOfEverything.MapValueEntry
	22, // 8: examples.internal.proto.examplepb.ABitOfEverything.mapped_string_value:type_name -> examples.internal.proto.examplepb.ABitOfEverything.MappedStringValueEntry
	23, // 9: examples.internal.proto.examplepb.ABitOfEverything.mapped_nested_value:type_name -> examples.internal.proto.examplepb.ABitOfEverything.MappedNestedValueEntry
	27, // 10: examples.internal.proto.examplepb.ABitOfEverything.timestamp_value:type_name -> google.protobuf.Timestamp
	0,  // 11: examples.internal.proto.examplepb.ABitOfEverything.repeated_enum_value:type_name -> examples.internal.proto.examplepb.NumericEnum
	0,  // 12: examples.internal.proto.examplepb.ABitOfEverything.repeated_enum_annotation:type_name -> examples.internal.proto.examplepb.NumericEnum
	0,  // 13: examples.internal.proto.examplepb.ABitOfEverything.enum_value_annotation:type_name -> examples.internal.proto.examplepb.NumericEnum
	20, // 14: examples.internal.proto.examplepb.ABitOfEverything.repeated_nested_annotation:type_name -> examples.internal.proto.examplepb.ABitOfEverything.Nested
	20, // 15: examples.internal.proto.examplepb.ABitOfEverything.nested_annotation:type_name -> examples.internal.proto.examplepb.ABitOfEverything.Nested
	0,  // 16: examples.internal.proto.examplepb.ABitOfEverythingRepeated.path_repeated_enum_value:type_name -> examples.internal.proto.examplepb.NumericEnum
	28, // 17: examples.internal.proto.examplepb.CheckStatusResponse.status:type_name -> google.rpc.Status
	9,  // 18: examples.internal.proto.examplepb.MessageWithBody.data:type_name -> examples.internal.proto.examplepb.Body
	6,  // 19: examples.internal.proto.examplepb.UpdateV2Request.abe:type_name -> examples.internal.proto.examplepb.ABitOfEverything
	29, // 20: examples.internal.proto.examplepb.UpdateV2Request.update_mask:type_name -> google.protobuf.FieldMask
	27, // 21: examples.internal.proto.examplepb.Book.create_time:type_name -> google.protobuf.Timestamp
	12, // 22: examples.internal.proto.examplepb.CreateBookRequest.book:type_name -> examples.internal.proto.examplepb.Book
	12, // 23: examples.internal.proto.examplepb.UpdateBookRequest.book:type_name -> examples.internal.proto.examplepb.Book
	29, // 24: examples.internal.proto.examplepb.UpdateBookRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 25: examples.internal.proto.examplepb.SnakeEnumRequest.what:type_name -> examples.internal.proto.examplepb.snake_case_enum
	2,  // 26: examples.internal.proto.examplepb.SnakeEnumRequest.who:type_name -> examples.internal.proto.examplepb.snake_case_0_enum
	30, // 27: examples.internal.proto.examplepb.SnakeEnumRequest.where:type_name -> examples.internal.pathenum.snake_case_for_import
	18, // 28: examples.internal.proto.examplepb.RequiredMessageTypeRequest.foo:type_name -> examples.internal.proto.examplepb.Foo
	19, // 29: examples.internal.proto.examplepb.Foo.bar:type_name -> examples.internal.proto.examplepb.Bar
	3,  // 30: examples.internal.proto.examplepb.ABitOfEverything.Nested.ok:type_name -> examples.internal.proto.examplepb.ABitOfEverything.Nested.DeepEnum
	0,  // 31: examples.internal.proto.examplepb.ABitOfEverything.MapValueEntry.value:type_name -> examples.internal.proto.examplepb.NumericEnum
	20, // 32: examples.internal.proto.examplepb.ABitOfEverything.MappedNestedValueEntry.value:type_name -> examples.internal.proto.examplepb.ABitOfEverything.Nested
	6,  // 33: examples.internal.proto.examplepb.ABitOfEverythingService.Create:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 34: examples.internal.proto.examplepb.ABitOfEverythingService.CreateBody:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	13, // 35: examples.internal.proto.examplepb.ABitOfEverythingService.CreateBook:input_type -> examples.internal.proto.examplepb.CreateBookRequest
	14, // 36: examples.internal.proto.examplepb.ABitOfEverythingService.UpdateBook:input_type -> examples.internal.proto.examplepb.UpdateBookRequest
	31, // 37: examples.internal.proto.examplepb.ABitOfEverythingService.Lookup:input_type -> examples.internal.proto.sub2.IdMessage
	6,  // 38: examples.internal.proto.examplepb.ABitOfEverythingService.Custom:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 39: examples.internal.proto.examplepb.ABitOfEverythingService.DoubleColon:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 40: examples.internal.proto.examplepb.ABitOfEverythingService.Update:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	11, // 41: examples.internal.proto.examplepb.ABitOfEverythingService.UpdateV2:input_type -> examples.internal.proto.examplepb.UpdateV2Request
	31, // 42: examples.internal.proto.examplepb.ABitOfEverythingService.Delete:input_type -> examples.internal.proto.sub2.IdMessage
	6,  // 43: examples.internal.proto.examplepb.ABitOfEverythingService.GetQuery:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	7,  // 44: examples.internal.proto.examplepb.ABitOfEverythingService.GetRepeatedQuery:input_type -> examples.internal.proto.examplepb.ABitOfEverythingRepeated
	32, // 45: examples.internal.proto.examplepb.ABitOfEverythingService.Echo:input_type -> examples.internal.proto.sub.StringMessage
	6,  // 46: examples.internal.proto.examplepb.ABitOfEverythingService.DeepPathEcho:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	33, // 47: examples.internal.proto.examplepb.ABitOfEverythingService.NoBindings:input_type -> google.protobuf.Duration
	26, // 48: examples.internal.proto.examplepb.ABitOfEverythingService.Timeout:input_type -> google.protobuf.Empty
	26, // 49: examples.internal.proto.examplepb.ABitOfEverythingService.ErrorWithDetails:input_type -> google.protobuf.Empty
	10, // 50: examples.internal.proto.examplepb.ABitOfEverythingService.GetMessageWithBody:input_type -> examples.internal.proto.examplepb.MessageWithBody
	9,  // 51: examples.internal.proto.examplepb.ABitOfEverythingService.PostWithEmptyBody:input_type -> examples.internal.proto.examplepb.Body
	6,  // 52: examples.internal.proto.examplepb.ABitOfEverythingService.CheckGetQueryParams:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 53: examples.internal.proto.examplepb.ABitOfEverythingService.CheckNestedEnumGetQueryParams:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 54: examples.internal.proto.examplepb.ABitOfEverythingService.CheckPostQueryParams:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	9,  // 55: examples.internal.proto.examplepb.ABitOfEverythingService.OverwriteRequestContentType:input_type -> examples.internal.proto.examplepb.Body
	26, // 56: examples.internal.proto.examplepb.ABitOfEverythingService.OverwriteResponseContentType:input_type -> google.protobuf.Empty
	34, // 57: examples.internal.proto.examplepb.ABitOfEverythingService.CheckExternalPathEnum:input_type -> examples.internal.pathenum.MessageWithPathEnum
	35, // 58: examples.internal.proto.examplepb.ABitOfEverythingService.CheckExternalNestedPathEnum:input_type -> examples.internal.pathenum.MessageWithNestedPathEnum
	26, // 59: examples.internal.proto.examplepb.ABitOfEverythingService.CheckStatus:input_type -> google.protobuf.Empty
	6,  // 60: examples.internal.proto.examplepb.ABitOfEverythingService.Exists:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 61: examples.internal.proto.examplepb.ABitOfEverythingService.CustomOptionsRequest:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 62: examples.internal.proto.examplepb.ABitOfEverythingService.TraceRequest:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	36, // 63: examples.internal.proto.examplepb.ABitOfEverythingService.PostOneofEnum:input_type -> examples.internal.proto.oneofenum.OneofEnumMessage
	17, // 64: examples.internal.proto.examplepb.ABitOfEverythingService.PostRequiredMessageType:input_type -> examples.internal.proto.examplepb.RequiredMessageTypeRequest
	26, // 65: examples.internal.proto.examplepb.camelCaseServiceName.Empty:input_type -> google.protobuf.Empty
	26, // 66: examples.internal.proto.examplepb.AnotherServiceWithNoBindings.NoBindings:input_type -> google.protobuf.Empty
	15, // 67: examples.internal.proto.examplepb.SnakeEnumService.SnakeEnum:input_type -> examples.internal.proto.examplepb.SnakeEnumRequest
	6,  // 68: examples.internal.proto.examplepb.ABitOfEverythingService.Create:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 69: examples.internal.proto.examplepb.ABitOfEverythingService.CreateBody:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	12, // 70: examples.internal.proto.examplepb.ABitOfEverythingService.CreateBook:output_type -> examples.internal.proto.examplepb.Book
	12, // 71: examples.internal.proto.examplepb.ABitOfEverythingService.UpdateBook:output_type -> examples.internal.proto.examplepb.Book
	6,  // 72: examples.internal.proto.examplepb.ABitOfEverythingService.Lookup:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 73: examples.internal.proto.examplepb.ABitOfEverythingService.Custom:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 74: examples.internal.proto.examplepb.ABitOfEverythingService.DoubleColon:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	26, // 75: examples.internal.proto.examplepb.ABitOfEverythingService.Update:output_type -> google.protobuf.Empty
	26, // 76: examples.internal.proto.examplepb.ABitOfEverythingService.UpdateV2:output_type -> google.protobuf.Empty
	26, // 77: examples.internal.proto.examplepb.ABitOfEverythingService.Delete:output_type -> google.protobuf.Empty
	26, // 78: examples.internal.proto.examplepb.ABitOfEverythingService.GetQuery:output_type -> google.protobuf.Empty
	7,  // 79: examples.internal.proto.examplepb.ABitOfEverythingService.GetRepeatedQuery:output_type -> examples.internal.proto.examplepb.ABitOfEverythingRepeated
	32, // 80: examples.internal.proto.examplepb.ABitOfEverythingService.Echo:output_type -> examples.internal.proto.sub.StringMessage
	6,  // 81: examples.internal.proto.examplepb.ABitOfEverythingService.DeepPathEcho:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	26, // 82: examples.internal.proto.examplepb.ABitOfEverythingService.NoBindings:output_type -> google.protobuf.Empty
	26, // 83: examples.internal.proto.examplepb.ABitOfEverythingService.Timeout:output_type -> google.protobuf.Empty
	26, // 84: examples.internal.proto.examplepb.ABitOfEverythingService.ErrorWithDetails:output_type -> google.protobuf.Empty
	26, // 85: examples.internal.proto.examplepb.ABitOfEverythingService.GetMessageWithBody:output_type -> google.protobuf.Empty
	26, // 86: examples.internal.proto.examplepb.ABitOfEverythingService.PostWithEmptyBody:output_type -> google.protobuf.Empty
	6,  // 87: examples.internal.proto.examplepb.ABitOfEverythingService.CheckGetQueryParams:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 88: examples.internal.proto.examplepb.ABitOfEverythingService.CheckNestedEnumGetQueryParams:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	6,  // 89: examples.internal.proto.examplepb.ABitOfEverythingService.CheckPostQueryParams:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	26, // 90: examples.internal.proto.examplepb.ABitOfEverythingService.OverwriteRequestContentType:output_type -> google.protobuf.Empty
	37, // 91: examples.internal.proto.examplepb.ABitOfEverythingService.OverwriteResponseContentType:output_type -> google.protobuf.StringValue
	26, // 92: examples.internal.proto.examplepb.ABitOfEverythingService.CheckExternalPathEnum:output_type -> google.protobuf.Empty
	26, // 93: examples.internal.proto.examplepb.ABitOfEverythingService.CheckExternalNestedPathEnum:output_type -> google.protobuf.Empty
	8,  // 94: examples.internal.proto.examplepb.ABitOfEverythingService.CheckStatus:output_type -> examples.internal.proto.examplepb.CheckStatusResponse
	26, // 95: examples.internal.proto.examplepb.ABitOfEverythingService.Exists:output_type -> google.protobuf.Empty
	26, // 96: examples.internal.proto.examplepb.ABitOfEverythingService.CustomOptionsRequest:output_type -> google.protobuf.Empty
	6,  // 97: examples.internal.proto.examplepb.ABitOfEverythingService.TraceRequest:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	26, // 98: examples.internal.proto.examplepb.ABitOfEverythingService.PostOneofEnum:output_type -> google.protobuf.Empty
	26, // 99: examples.internal.proto.examplepb.ABitOfEverythingService.PostRequiredMessageType:output_type -> google.protobuf.Empty
	26, // 100: examples.internal.proto.examplepb.camelCaseServiceName.Empty:output_type -> google.protobuf.Empty
	26, // 101: examples.internal.proto.examplepb.AnotherServiceWithNoBindings.NoBindings:output_type -> google.protobuf.Empty
	16, // 102: examples.internal.proto.examplepb.SnakeEnumService.SnakeEnum:output_type -> examples.internal.proto.examplepb.SnakeEnumResponse
	68, // [68:103] is the sub-list for method output_type
	33, // [33:68] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_a_bit_of_everything_proto_init() }
func file_examples_internal_proto_examplepb_a_bit_of_everything_proto_init() {
	if File_examples_internal_proto_examplepb_a_bit_of_everything_proto != nil {
		return
	}
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes[2].OneofWrappers = []any{
		(*ABitOfEverything_OneofEmpty)(nil),
		(*ABitOfEverything_OneofString)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDesc), len(file_examples_internal_proto_examplepb_a_bit_of_everything_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_examples_internal_proto_examplepb_a_bit_of_everything_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_a_bit_of_everything_proto_depIdxs,
		EnumInfos:         file_examples_internal_proto_examplepb_a_bit_of_everything_proto_enumTypes,
		MessageInfos:      file_examples_internal_proto_examplepb_a_bit_of_everything_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_a_bit_of_everything_proto = out.File
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_goTypes = nil
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_depIdxs = nil
}
