// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/echo_service.proto

// Echo Service
//
// Echo Service API consists of a single service which returns
// a message.

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Embedded represents a message embedded in SimpleMessage.
type Embedded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mark:
	//
	//	*Embedded_Progress
	//	*Embedded_Note
	Mark          isEmbedded_Mark `protobuf_oneof:"mark"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedded) Reset() {
	*x = Embedded{}
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedded) ProtoMessage() {}

func (x *Embedded) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedded.ProtoReflect.Descriptor instead.
func (*Embedded) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_echo_service_proto_rawDescGZIP(), []int{0}
}

func (x *Embedded) GetMark() isEmbedded_Mark {
	if x != nil {
		return x.Mark
	}
	return nil
}

func (x *Embedded) GetProgress() int64 {
	if x != nil {
		if x, ok := x.Mark.(*Embedded_Progress); ok {
			return x.Progress
		}
	}
	return 0
}

func (x *Embedded) GetNote() string {
	if x != nil {
		if x, ok := x.Mark.(*Embedded_Note); ok {
			return x.Note
		}
	}
	return ""
}

type isEmbedded_Mark interface {
	isEmbedded_Mark()
}

type Embedded_Progress struct {
	Progress int64 `protobuf:"varint,1,opt,name=progress,proto3,oneof"`
}

type Embedded_Note struct {
	Note string `protobuf:"bytes,2,opt,name=note,proto3,oneof"`
}

func (*Embedded_Progress) isEmbedded_Mark() {}

func (*Embedded_Note) isEmbedded_Mark() {}

type NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NId           string                 `protobuf:"bytes,1,opt,name=n_id,json=nId,proto3" json:"n_id,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_echo_service_proto_rawDescGZIP(), []int{1}
}

func (x *NestedMessage) GetNId() string {
	if x != nil {
		return x.NId
	}
	return ""
}

func (x *NestedMessage) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

// SimpleMessage represents a simple message sent to the Echo service.
type SimpleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num int64  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	// Types that are valid to be assigned to Code:
	//
	//	*SimpleMessage_LineNum
	//	*SimpleMessage_Lang
	Code   isSimpleMessage_Code `protobuf_oneof:"code"`
	Status *Embedded            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Ext:
	//
	//	*SimpleMessage_En
	//	*SimpleMessage_No
	Ext           isSimpleMessage_Ext `protobuf_oneof:"ext"`
	ResourceId    string              `protobuf:"bytes,8,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	NId           *NestedMessage      `protobuf:"bytes,9,opt,name=n_id,json=nId,proto3" json:"n_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_echo_service_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SimpleMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *SimpleMessage) GetCode() isSimpleMessage_Code {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *SimpleMessage) GetLineNum() int64 {
	if x != nil {
		if x, ok := x.Code.(*SimpleMessage_LineNum); ok {
			return x.LineNum
		}
	}
	return 0
}

func (x *SimpleMessage) GetLang() string {
	if x != nil {
		if x, ok := x.Code.(*SimpleMessage_Lang); ok {
			return x.Lang
		}
	}
	return ""
}

func (x *SimpleMessage) GetStatus() *Embedded {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *SimpleMessage) GetExt() isSimpleMessage_Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *SimpleMessage) GetEn() int64 {
	if x != nil {
		if x, ok := x.Ext.(*SimpleMessage_En); ok {
			return x.En
		}
	}
	return 0
}

func (x *SimpleMessage) GetNo() *Embedded {
	if x != nil {
		if x, ok := x.Ext.(*SimpleMessage_No); ok {
			return x.No
		}
	}
	return nil
}

func (x *SimpleMessage) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SimpleMessage) GetNId() *NestedMessage {
	if x != nil {
		return x.NId
	}
	return nil
}

type isSimpleMessage_Code interface {
	isSimpleMessage_Code()
}

type SimpleMessage_LineNum struct {
	LineNum int64 `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3,oneof"`
}

type SimpleMessage_Lang struct {
	Lang string `protobuf:"bytes,4,opt,name=lang,proto3,oneof"`
}

func (*SimpleMessage_LineNum) isSimpleMessage_Code() {}

func (*SimpleMessage_Lang) isSimpleMessage_Code() {}

type isSimpleMessage_Ext interface {
	isSimpleMessage_Ext()
}

type SimpleMessage_En struct {
	En int64 `protobuf:"varint,6,opt,name=en,proto3,oneof"`
}

type SimpleMessage_No struct {
	No *Embedded `protobuf:"bytes,7,opt,name=no,proto3,oneof"`
}

func (*SimpleMessage_En) isSimpleMessage_Ext() {}

func (*SimpleMessage_No) isSimpleMessage_Ext() {}

// DynamicMessage represents a message which can have its structure
// built dynamically using Struct and Values.
type DynamicMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StructField   *structpb.Struct       `protobuf:"bytes,1,opt,name=struct_field,json=structField,proto3" json:"struct_field,omitempty"`
	ValueField    *structpb.Value        `protobuf:"bytes,2,opt,name=value_field,json=valueField,proto3" json:"value_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicMessage) Reset() {
	*x = DynamicMessage{}
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMessage) ProtoMessage() {}

func (x *DynamicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMessage.ProtoReflect.Descriptor instead.
func (*DynamicMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_echo_service_proto_rawDescGZIP(), []int{3}
}

func (x *DynamicMessage) GetStructField() *structpb.Struct {
	if x != nil {
		return x.StructField
	}
	return nil
}

func (x *DynamicMessage) GetValueField() *structpb.Value {
	if x != nil {
		return x.ValueField
	}
	return nil
}

type DynamicMessageUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *DynamicMessage        `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamicMessageUpdate) Reset() {
	*x = DynamicMessageUpdate{}
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicMessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicMessageUpdate) ProtoMessage() {}

func (x *DynamicMessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicMessageUpdate.ProtoReflect.Descriptor instead.
func (*DynamicMessageUpdate) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_echo_service_proto_rawDescGZIP(), []int{4}
}

func (x *DynamicMessageUpdate) GetBody() *DynamicMessage {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *DynamicMessageUpdate) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

var File_examples_internal_proto_examplepb_echo_service_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_echo_service_proto_rawDesc = "" +
	"\n" +
	"4examples/internal/proto/examplepb/echo_service.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1cgoogle/protobuf/struct.proto\"F\n" +
	"\bEmbedded\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\x03H\x00R\bprogress\x12\x14\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04noteB\x06\n" +
	"\x04mark\"4\n" +
	"\rNestedMessage\x12\x11\n" +
	"\x04n_id\x18\x01 \x01(\tR\x03nId\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\"\xef\x02\n" +
	"\rSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x1b\n" +
	"\bline_num\x18\x03 \x01(\x03H\x00R\alineNum\x12\x14\n" +
	"\x04lang\x18\x04 \x01(\tH\x00R\x04lang\x12C\n" +
	"\x06status\x18\x05 \x01(\v2+.examples.internal.proto.examplepb.EmbeddedR\x06status\x12\x10\n" +
	"\x02en\x18\x06 \x01(\x03H\x01R\x02en\x12=\n" +
	"\x02no\x18\a \x01(\v2+.examples.internal.proto.examplepb.EmbeddedH\x01R\x02no\x12\x1f\n" +
	"\vresource_id\x18\b \x01(\tR\n" +
	"resourceId\x12C\n" +
	"\x04n_id\x18\t \x01(\v20.examples.internal.proto.examplepb.NestedMessageR\x03nIdB\x06\n" +
	"\x04codeB\x05\n" +
	"\x03ext\"\x85\x01\n" +
	"\x0eDynamicMessage\x12:\n" +
	"\fstruct_field\x18\x01 \x01(\v2\x17.google.protobuf.StructR\vstructField\x127\n" +
	"\vvalue_field\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\n" +
	"valueField\"\x9a\x01\n" +
	"\x14DynamicMessageUpdate\x12E\n" +
	"\x04body\x18\x01 \x01(\v21.examples.internal.proto.examplepb.DynamicMessageR\x04body\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask2\x93\b\n" +
	"\vEchoService\x12\xf4\x02\n" +
	"\x04Echo\x120.examples.internal.proto.examplepb.SimpleMessage\x1a0.examples.internal.proto.examplepb.SimpleMessage\"\x87\x02\x82\xd3\xe4\x93\x02\x80\x02Z\x1d\x12\x1b/v1/example/echo/{id}/{num}Z$\x12\"/v1/example/echo/{id}/{num}/{lang}Z1\x12//v1/example/echo1/{id}/{line_num}/{status.note}Z\x1d\x12\x1b/v1/example/echo2/{no.note}Z)\x12'/v1/example/echo/resource/{resource_id}Z%\x12#/v1/example/echo/nested/{n_id.n_id}\"\x15/v1/example/echo/{id}\x12\xb2\x01\n" +
	"\bEchoBody\x120.examples.internal.proto.examplepb.SimpleMessage\x1a0.examples.internal.proto.examplepb.SimpleMessage\"B\x82\xd3\xe4\x93\x02<:\x01*Z :\x02no\x1a\x1a/v1/example/echo_body/{id}\"\x15/v1/example/echo_body\x12\x91\x01\n" +
	"\n" +
	"EchoDelete\x120.examples.internal.proto.examplepb.SimpleMessage\x1a0.examples.internal.proto.examplepb.SimpleMessage\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/example/echo_delete\x12\xa3\x01\n" +
	"\tEchoPatch\x127.examples.internal.proto.examplepb.DynamicMessageUpdate\x1a7.examples.internal.proto.examplepb.DynamicMessageUpdate\"$\x82\xd3\xe4\x93\x02\x1e:\x04body2\x16/v1/example/echo_patch\x12\x9d\x01\n" +
	"\x10EchoUnauthorized\x120.examples.internal.proto.examplepb.SimpleMessage\x1a0.examples.internal.proto.examplepb.SimpleMessage\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/example/echo_unauthorizedBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_echo_service_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_echo_service_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_echo_service_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_echo_service_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_echo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_echo_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_echo_service_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_echo_service_proto_rawDescData
}

var file_examples_internal_proto_examplepb_echo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examples_internal_proto_examplepb_echo_service_proto_goTypes = []any{
	(*Embedded)(nil),              // 0: examples.internal.proto.examplepb.Embedded
	(*NestedMessage)(nil),         // 1: examples.internal.proto.examplepb.NestedMessage
	(*SimpleMessage)(nil),         // 2: examples.internal.proto.examplepb.SimpleMessage
	(*DynamicMessage)(nil),        // 3: examples.internal.proto.examplepb.DynamicMessage
	(*DynamicMessageUpdate)(nil),  // 4: examples.internal.proto.examplepb.DynamicMessageUpdate
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
	(*structpb.Value)(nil),        // 6: google.protobuf.Value
	(*fieldmaskpb.FieldMask)(nil), // 7: google.protobuf.FieldMask
}
var file_examples_internal_proto_examplepb_echo_service_proto_depIdxs = []int32{
	0,  // 0: examples.internal.proto.examplepb.SimpleMessage.status:type_name -> examples.internal.proto.examplepb.Embedded
	0,  // 1: examples.internal.proto.examplepb.SimpleMessage.no:type_name -> examples.internal.proto.examplepb.Embedded
	1,  // 2: examples.internal.proto.examplepb.SimpleMessage.n_id:type_name -> examples.internal.proto.examplepb.NestedMessage
	5,  // 3: examples.internal.proto.examplepb.DynamicMessage.struct_field:type_name -> google.protobuf.Struct
	6,  // 4: examples.internal.proto.examplepb.DynamicMessage.value_field:type_name -> google.protobuf.Value
	3,  // 5: examples.internal.proto.examplepb.DynamicMessageUpdate.body:type_name -> examples.internal.proto.examplepb.DynamicMessage
	7,  // 6: examples.internal.proto.examplepb.DynamicMessageUpdate.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 7: examples.internal.proto.examplepb.EchoService.Echo:input_type -> examples.internal.proto.examplepb.SimpleMessage
	2,  // 8: examples.internal.proto.examplepb.EchoService.EchoBody:input_type -> examples.internal.proto.examplepb.SimpleMessage
	2,  // 9: examples.internal.proto.examplepb.EchoService.EchoDelete:input_type -> examples.internal.proto.examplepb.SimpleMessage
	4,  // 10: examples.internal.proto.examplepb.EchoService.EchoPatch:input_type -> examples.internal.proto.examplepb.DynamicMessageUpdate
	2,  // 11: examples.internal.proto.examplepb.EchoService.EchoUnauthorized:input_type -> examples.internal.proto.examplepb.SimpleMessage
	2,  // 12: examples.internal.proto.examplepb.EchoService.Echo:output_type -> examples.internal.proto.examplepb.SimpleMessage
	2,  // 13: examples.internal.proto.examplepb.EchoService.EchoBody:output_type -> examples.internal.proto.examplepb.SimpleMessage
	2,  // 14: examples.internal.proto.examplepb.EchoService.EchoDelete:output_type -> examples.internal.proto.examplepb.SimpleMessage
	4,  // 15: examples.internal.proto.examplepb.EchoService.EchoPatch:output_type -> examples.internal.proto.examplepb.DynamicMessageUpdate
	2,  // 16: examples.internal.proto.examplepb.EchoService.EchoUnauthorized:output_type -> examples.internal.proto.examplepb.SimpleMessage
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_echo_service_proto_init() }
func file_examples_internal_proto_examplepb_echo_service_proto_init() {
	if File_examples_internal_proto_examplepb_echo_service_proto != nil {
		return
	}
	file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[0].OneofWrappers = []any{
		(*Embedded_Progress)(nil),
		(*Embedded_Note)(nil),
	}
	file_examples_internal_proto_examplepb_echo_service_proto_msgTypes[2].OneofWrappers = []any{
		(*SimpleMessage_LineNum)(nil),
		(*SimpleMessage_Lang)(nil),
		(*SimpleMessage_En)(nil),
		(*SimpleMessage_No)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_echo_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_echo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_echo_service_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_echo_service_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_echo_service_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_echo_service_proto = out.File
	file_examples_internal_proto_examplepb_echo_service_proto_goTypes = nil
	file_examples_internal_proto_examplepb_echo_service_proto_depIdxs = nil
}
