// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/enum_with_single_value.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnumWithSingleValue is an enum with a single value. Since it has just a single value
// the `enum` field should be omitted in the generated OpenAPI spec for the type when
// the omit_enum_default_value option is set to true.
type EnumWithSingleValue int32

const (
	EnumWithSingleValue_ENUM_WITH_SINGLE_VALUE_UNSPECIFIED EnumWithSingleValue = 0
)

// Enum value maps for EnumWithSingleValue.
var (
	EnumWithSingleValue_name = map[int32]string{
		0: "ENUM_WITH_SINGLE_VALUE_UNSPECIFIED",
	}
	EnumWithSingleValue_value = map[string]int32{
		"ENUM_WITH_SINGLE_VALUE_UNSPECIFIED": 0,
	}
)

func (x EnumWithSingleValue) Enum() *EnumWithSingleValue {
	p := new(EnumWithSingleValue)
	*p = x
	return p
}

func (x EnumWithSingleValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumWithSingleValue) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_enum_with_single_value_proto_enumTypes[0].Descriptor()
}

func (EnumWithSingleValue) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_enum_with_single_value_proto_enumTypes[0]
}

func (x EnumWithSingleValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumWithSingleValue.Descriptor instead.
func (EnumWithSingleValue) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescGZIP(), []int{0}
}

type EnumWithSingleValueServiceEchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         EnumWithSingleValue    `protobuf:"varint,1,opt,name=value,proto3,enum=examples.internal.proto.examplepb.EnumWithSingleValue" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumWithSingleValueServiceEchoRequest) Reset() {
	*x = EnumWithSingleValueServiceEchoRequest{}
	mi := &file_examples_internal_proto_examplepb_enum_with_single_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumWithSingleValueServiceEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumWithSingleValueServiceEchoRequest) ProtoMessage() {}

func (x *EnumWithSingleValueServiceEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_enum_with_single_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumWithSingleValueServiceEchoRequest.ProtoReflect.Descriptor instead.
func (*EnumWithSingleValueServiceEchoRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescGZIP(), []int{0}
}

func (x *EnumWithSingleValueServiceEchoRequest) GetValue() EnumWithSingleValue {
	if x != nil {
		return x.Value
	}
	return EnumWithSingleValue_ENUM_WITH_SINGLE_VALUE_UNSPECIFIED
}

type EnumWithSingleValueServiceEchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumWithSingleValueServiceEchoResponse) Reset() {
	*x = EnumWithSingleValueServiceEchoResponse{}
	mi := &file_examples_internal_proto_examplepb_enum_with_single_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumWithSingleValueServiceEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumWithSingleValueServiceEchoResponse) ProtoMessage() {}

func (x *EnumWithSingleValueServiceEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_enum_with_single_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumWithSingleValueServiceEchoResponse.ProtoReflect.Descriptor instead.
func (*EnumWithSingleValueServiceEchoResponse) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescGZIP(), []int{1}
}

var File_examples_internal_proto_examplepb_enum_with_single_value_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDesc = "" +
	"\n" +
	">examples/internal/proto/examplepb/enum_with_single_value.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\"u\n" +
	"%EnumWithSingleValueServiceEchoRequest\x12L\n" +
	"\x05value\x18\x01 \x01(\x0e26.examples.internal.proto.examplepb.EnumWithSingleValueR\x05value\"(\n" +
	"&EnumWithSingleValueServiceEchoResponse*=\n" +
	"\x13EnumWithSingleValue\x12&\n" +
	"\"ENUM_WITH_SINGLE_VALUE_UNSPECIFIED\x10\x002\xee\x01\n" +
	"\x1aEnumWithSingleValueService\x12\xcf\x01\n" +
	"\x04Echo\x12H.examples.internal.proto.examplepb.EnumWithSingleValueServiceEchoRequest\x1aI.examples.internal.proto.examplepb.EnumWithSingleValueServiceEchoResponse\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/v1/example/enum-with-single-value/echoBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDesc), len(file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDescData
}

var file_examples_internal_proto_examplepb_enum_with_single_value_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_internal_proto_examplepb_enum_with_single_value_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_internal_proto_examplepb_enum_with_single_value_proto_goTypes = []any{
	(EnumWithSingleValue)(0),                       // 0: examples.internal.proto.examplepb.EnumWithSingleValue
	(*EnumWithSingleValueServiceEchoRequest)(nil),  // 1: examples.internal.proto.examplepb.EnumWithSingleValueServiceEchoRequest
	(*EnumWithSingleValueServiceEchoResponse)(nil), // 2: examples.internal.proto.examplepb.EnumWithSingleValueServiceEchoResponse
}
var file_examples_internal_proto_examplepb_enum_with_single_value_proto_depIdxs = []int32{
	0, // 0: examples.internal.proto.examplepb.EnumWithSingleValueServiceEchoRequest.value:type_name -> examples.internal.proto.examplepb.EnumWithSingleValue
	1, // 1: examples.internal.proto.examplepb.EnumWithSingleValueService.Echo:input_type -> examples.internal.proto.examplepb.EnumWithSingleValueServiceEchoRequest
	2, // 2: examples.internal.proto.examplepb.EnumWithSingleValueService.Echo:output_type -> examples.internal.proto.examplepb.EnumWithSingleValueServiceEchoResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_enum_with_single_value_proto_init() }
func file_examples_internal_proto_examplepb_enum_with_single_value_proto_init() {
	if File_examples_internal_proto_examplepb_enum_with_single_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDesc), len(file_examples_internal_proto_examplepb_enum_with_single_value_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_enum_with_single_value_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_enum_with_single_value_proto_depIdxs,
		EnumInfos:         file_examples_internal_proto_examplepb_enum_with_single_value_proto_enumTypes,
		MessageInfos:      file_examples_internal_proto_examplepb_enum_with_single_value_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_enum_with_single_value_proto = out.File
	file_examples_internal_proto_examplepb_enum_with_single_value_proto_goTypes = nil
	file_examples_internal_proto_examplepb_enum_with_single_value_proto_depIdxs = nil
}
