// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/excess_body.proto

// Excess Body Service
// Used to test server context cancellation with Unary and ServerStream methods
// when client sends more data than expected.

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_examples_internal_proto_examplepb_excess_body_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_excess_body_proto_rawDesc = "" +
	"\n" +
	"3examples/internal/proto/examplepb/excess_body.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\xb9\x03\n" +
	"\x11ExcessBodyService\x12Y\n" +
	"\tNoBodyRpc\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x14/rpc/excess-body/rpc\x12g\n" +
	"\x12NoBodyServerStream\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/rpc/excess-body/stream0\x01\x12h\n" +
	"\vWithBodyRpc\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/rpc/excess-body/rpc/with-body\x12v\n" +
	"\x14WithBodyServerStream\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\",\x82\xd3\xe4\x93\x02&:\x01*\"!/rpc/excess-body/stream/with-body0\x01BMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var file_examples_internal_proto_examplepb_excess_body_proto_goTypes = []any{
	(*emptypb.Empty)(nil), // 0: google.protobuf.Empty
}
var file_examples_internal_proto_examplepb_excess_body_proto_depIdxs = []int32{
	0, // 0: examples.internal.proto.examplepb.ExcessBodyService.NoBodyRpc:input_type -> google.protobuf.Empty
	0, // 1: examples.internal.proto.examplepb.ExcessBodyService.NoBodyServerStream:input_type -> google.protobuf.Empty
	0, // 2: examples.internal.proto.examplepb.ExcessBodyService.WithBodyRpc:input_type -> google.protobuf.Empty
	0, // 3: examples.internal.proto.examplepb.ExcessBodyService.WithBodyServerStream:input_type -> google.protobuf.Empty
	0, // 4: examples.internal.proto.examplepb.ExcessBodyService.NoBodyRpc:output_type -> google.protobuf.Empty
	0, // 5: examples.internal.proto.examplepb.ExcessBodyService.NoBodyServerStream:output_type -> google.protobuf.Empty
	0, // 6: examples.internal.proto.examplepb.ExcessBodyService.WithBodyRpc:output_type -> google.protobuf.Empty
	0, // 7: examples.internal.proto.examplepb.ExcessBodyService.WithBodyServerStream:output_type -> google.protobuf.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_excess_body_proto_init() }
func file_examples_internal_proto_examplepb_excess_body_proto_init() {
	if File_examples_internal_proto_examplepb_excess_body_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_excess_body_proto_rawDesc), len(file_examples_internal_proto_examplepb_excess_body_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_excess_body_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_excess_body_proto_depIdxs,
	}.Build()
	File_examples_internal_proto_examplepb_excess_body_proto = out.File
	file_examples_internal_proto_examplepb_excess_body_proto_goTypes = nil
	file_examples_internal_proto_examplepb_excess_body_proto_depIdxs = nil
}
