// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/flow_combination.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyProto) Reset() {
	*x = EmptyProto{}
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyProto) ProtoMessage() {}

func (x *EmptyProto) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyProto.ProtoReflect.Descriptor instead.
func (*EmptyProto) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_flow_combination_proto_rawDescGZIP(), []int{0}
}

type NonEmptyProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             string                 `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C             string                 `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonEmptyProto) Reset() {
	*x = NonEmptyProto{}
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonEmptyProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonEmptyProto) ProtoMessage() {}

func (x *NonEmptyProto) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonEmptyProto.ProtoReflect.Descriptor instead.
func (*NonEmptyProto) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_flow_combination_proto_rawDescGZIP(), []int{1}
}

func (x *NonEmptyProto) GetA() string {
	if x != nil {
		return x.A
	}
	return ""
}

func (x *NonEmptyProto) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *NonEmptyProto) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

type UnaryProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Str           string                 `protobuf:"bytes,1,opt,name=str,proto3" json:"str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnaryProto) Reset() {
	*x = UnaryProto{}
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnaryProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryProto) ProtoMessage() {}

func (x *UnaryProto) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryProto.ProtoReflect.Descriptor instead.
func (*UnaryProto) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_flow_combination_proto_rawDescGZIP(), []int{2}
}

func (x *UnaryProto) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

type NestedProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *UnaryProto            `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	C             string                 `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedProto) Reset() {
	*x = NestedProto{}
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedProto) ProtoMessage() {}

func (x *NestedProto) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedProto.ProtoReflect.Descriptor instead.
func (*NestedProto) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_flow_combination_proto_rawDescGZIP(), []int{3}
}

func (x *NestedProto) GetA() *UnaryProto {
	if x != nil {
		return x.A
	}
	return nil
}

func (x *NestedProto) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

func (x *NestedProto) GetC() string {
	if x != nil {
		return x.C
	}
	return ""
}

type SingleNestedProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             *UnaryProto            `protobuf:"bytes,1,opt,name=a,proto3" json:"a,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleNestedProto) Reset() {
	*x = SingleNestedProto{}
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleNestedProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleNestedProto) ProtoMessage() {}

func (x *SingleNestedProto) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleNestedProto.ProtoReflect.Descriptor instead.
func (*SingleNestedProto) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_flow_combination_proto_rawDescGZIP(), []int{4}
}

func (x *SingleNestedProto) GetA() *UnaryProto {
	if x != nil {
		return x.A
	}
	return nil
}

var File_examples_internal_proto_examplepb_flow_combination_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_flow_combination_proto_rawDesc = "" +
	"\n" +
	"8examples/internal/proto/examplepb/flow_combination.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\"\f\n" +
	"\n" +
	"EmptyProto\"9\n" +
	"\rNonEmptyProto\x12\f\n" +
	"\x01a\x18\x01 \x01(\tR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\tR\x01c\"\x1e\n" +
	"\n" +
	"UnaryProto\x12\x10\n" +
	"\x03str\x18\x01 \x01(\tR\x03str\"f\n" +
	"\vNestedProto\x12;\n" +
	"\x01a\x18\x01 \x01(\v2-.examples.internal.proto.examplepb.UnaryProtoR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\x12\f\n" +
	"\x01c\x18\x03 \x01(\tR\x01c\"P\n" +
	"\x11SingleNestedProto\x12;\n" +
	"\x01a\x18\x01 \x01(\v2-.examples.internal.proto.examplepb.UnaryProtoR\x01a2\xf9\x0f\n" +
	"\x0fFlowCombination\x12\x83\x01\n" +
	"\vRpcEmptyRpc\x12-.examples.internal.proto.examplepb.EmptyProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"\x16\x82\xd3\xe4\x93\x02\x10\"\x0e/rpc/empty/rpc\x12\x8b\x01\n" +
	"\x0eRpcEmptyStream\x12-.examples.internal.proto.examplepb.EmptyProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/rpc/empty/stream0\x01\x12\x8b\x01\n" +
	"\x0eStreamEmptyRpc\x12-.examples.internal.proto.examplepb.EmptyProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"\x19\x82\xd3\xe4\x93\x02\x13\"\x11/stream/empty/rpc(\x01\x12\x93\x01\n" +
	"\x11StreamEmptyStream\x12-.examples.internal.proto.examplepb.EmptyProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x14/stream/empty/stream(\x010\x01\x12\xb1\x02\n" +
	"\n" +
	"RpcBodyRpc\x120.examples.internal.proto.examplepb.NonEmptyProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"\xc1\x01\x82\xd3\xe4\x93\x02\xba\x01:\x01*Z\x1b\"\x19/rpc/path/{a}/{b}/{c}/rpcZ\x10\"\x0e/rpc/query/rpcZ\x1f:\x01c\"\x1a/rpc/body/path/{a}/{b}/rpcZ\x18:\x01c\"\x13/rpc/body/query/rpcZ!:\x01c\"\x1c/rpc/body/path/{a}/query/rpcZ\x19\"\x17/rpc/path/{a}/query/rpc\"\r/rpc/body/rpc\x12\xa3\x01\n" +
	"\x16RpcPathSingleNestedRpc\x124.examples.internal.proto.examplepb.SingleNestedProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"$\x82\xd3\xe4\x93\x02\x1e\"\x1c/rpc/path-nested/{a.str}/rpc\x12\xe3\x01\n" +
	"\x10RpcPathNestedRpc\x12..examples.internal.proto.examplepb.NestedProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"p\x82\xd3\xe4\x93\x02j:\x01cZ\x1f\"\x1d/rpc/path-nested1/{a.str}/rpcZ\":\x01c\"\x1d/rpc/path-nested2/{a.str}/rpc\" /rpc/path-nested/{a.str}/{b}/rpc\x12\xcb\x02\n" +
	"\rRpcBodyStream\x120.examples.internal.proto.examplepb.NonEmptyProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"\xd6\x01\x82\xd3\xe4\x93\x02\xcf\x01:\x01*Z\x1e\"\x1c/rpc/path/{a}/{b}/{c}/streamZ\x13\"\x11/rpc/query/streamZ\":\x01c\"\x1d/rpc/body/path/{a}/{b}/streamZ\x1b:\x01c\"\x16/rpc/body/query/streamZ$:\x01c\"\x1f/rpc/body/path/{a}/query/streamZ\x1c\"\x1a/rpc/path/{a}/query/stream\"\x10/rpc/body/stream0\x01\x12\xab\x01\n" +
	"\x19RpcPathSingleNestedStream\x124.examples.internal.proto.examplepb.SingleNestedProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"'\x82\xd3\xe4\x93\x02!\"\x1f/rpc/path-nested/{a.str}/stream0\x01\x12\xf1\x01\n" +
	"\x13RpcPathNestedStream\x12..examples.internal.proto.examplepb.NestedProto\x1a-.examples.internal.proto.examplepb.EmptyProto\"y\x82\xd3\xe4\x93\x02s:\x01cZ\"\" /rpc/path-nested1/{a.str}/streamZ%:\x01c\" /rpc/path-nested2/{a.str}/stream\"#/rpc/path-nested/{a.str}/{b}/stream0\x01BMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_flow_combination_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_flow_combination_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_flow_combination_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_flow_combination_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_flow_combination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_flow_combination_proto_rawDesc), len(file_examples_internal_proto_examplepb_flow_combination_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_flow_combination_proto_rawDescData
}

var file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_examples_internal_proto_examplepb_flow_combination_proto_goTypes = []any{
	(*EmptyProto)(nil),        // 0: examples.internal.proto.examplepb.EmptyProto
	(*NonEmptyProto)(nil),     // 1: examples.internal.proto.examplepb.NonEmptyProto
	(*UnaryProto)(nil),        // 2: examples.internal.proto.examplepb.UnaryProto
	(*NestedProto)(nil),       // 3: examples.internal.proto.examplepb.NestedProto
	(*SingleNestedProto)(nil), // 4: examples.internal.proto.examplepb.SingleNestedProto
}
var file_examples_internal_proto_examplepb_flow_combination_proto_depIdxs = []int32{
	2,  // 0: examples.internal.proto.examplepb.NestedProto.a:type_name -> examples.internal.proto.examplepb.UnaryProto
	2,  // 1: examples.internal.proto.examplepb.SingleNestedProto.a:type_name -> examples.internal.proto.examplepb.UnaryProto
	0,  // 2: examples.internal.proto.examplepb.FlowCombination.RpcEmptyRpc:input_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 3: examples.internal.proto.examplepb.FlowCombination.RpcEmptyStream:input_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 4: examples.internal.proto.examplepb.FlowCombination.StreamEmptyRpc:input_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 5: examples.internal.proto.examplepb.FlowCombination.StreamEmptyStream:input_type -> examples.internal.proto.examplepb.EmptyProto
	1,  // 6: examples.internal.proto.examplepb.FlowCombination.RpcBodyRpc:input_type -> examples.internal.proto.examplepb.NonEmptyProto
	4,  // 7: examples.internal.proto.examplepb.FlowCombination.RpcPathSingleNestedRpc:input_type -> examples.internal.proto.examplepb.SingleNestedProto
	3,  // 8: examples.internal.proto.examplepb.FlowCombination.RpcPathNestedRpc:input_type -> examples.internal.proto.examplepb.NestedProto
	1,  // 9: examples.internal.proto.examplepb.FlowCombination.RpcBodyStream:input_type -> examples.internal.proto.examplepb.NonEmptyProto
	4,  // 10: examples.internal.proto.examplepb.FlowCombination.RpcPathSingleNestedStream:input_type -> examples.internal.proto.examplepb.SingleNestedProto
	3,  // 11: examples.internal.proto.examplepb.FlowCombination.RpcPathNestedStream:input_type -> examples.internal.proto.examplepb.NestedProto
	0,  // 12: examples.internal.proto.examplepb.FlowCombination.RpcEmptyRpc:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 13: examples.internal.proto.examplepb.FlowCombination.RpcEmptyStream:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 14: examples.internal.proto.examplepb.FlowCombination.StreamEmptyRpc:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 15: examples.internal.proto.examplepb.FlowCombination.StreamEmptyStream:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 16: examples.internal.proto.examplepb.FlowCombination.RpcBodyRpc:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 17: examples.internal.proto.examplepb.FlowCombination.RpcPathSingleNestedRpc:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 18: examples.internal.proto.examplepb.FlowCombination.RpcPathNestedRpc:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 19: examples.internal.proto.examplepb.FlowCombination.RpcBodyStream:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 20: examples.internal.proto.examplepb.FlowCombination.RpcPathSingleNestedStream:output_type -> examples.internal.proto.examplepb.EmptyProto
	0,  // 21: examples.internal.proto.examplepb.FlowCombination.RpcPathNestedStream:output_type -> examples.internal.proto.examplepb.EmptyProto
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_flow_combination_proto_init() }
func file_examples_internal_proto_examplepb_flow_combination_proto_init() {
	if File_examples_internal_proto_examplepb_flow_combination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_flow_combination_proto_rawDesc), len(file_examples_internal_proto_examplepb_flow_combination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_flow_combination_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_flow_combination_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_flow_combination_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_flow_combination_proto = out.File
	file_examples_internal_proto_examplepb_flow_combination_proto_goTypes = nil
	file_examples_internal_proto_examplepb_flow_combination_proto_depIdxs = nil
}
