// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/generate_unbound_methods.proto

// Generate Unannotated Methods Echo Service
// Similar to echo_service.proto but without annotations and without external configuration.
//
// Generate Unannotated Methods Echo Service API consists of a single service which returns
// a message.

package examplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateUnboundMethodsSimpleMessage represents a simple message sent to the unannotated GenerateUnboundMethodsEchoService service.
type GenerateUnboundMethodsSimpleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id            string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num           int64                `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Duration      *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUnboundMethodsSimpleMessage) Reset() {
	*x = GenerateUnboundMethodsSimpleMessage{}
	mi := &file_examples_internal_proto_examplepb_generate_unbound_methods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUnboundMethodsSimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUnboundMethodsSimpleMessage) ProtoMessage() {}

func (x *GenerateUnboundMethodsSimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_generate_unbound_methods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUnboundMethodsSimpleMessage.ProtoReflect.Descriptor instead.
func (*GenerateUnboundMethodsSimpleMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUnboundMethodsSimpleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerateUnboundMethodsSimpleMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GenerateUnboundMethodsSimpleMessage) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_examples_internal_proto_examplepb_generate_unbound_methods_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDesc = "" +
	"\n" +
	"@examples/internal/proto/examplepb/generate_unbound_methods.proto\x12!examples.internal.proto.examplepb\x1a\x1egoogle/protobuf/duration.proto\"~\n" +
	"#GenerateUnboundMethodsSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration2\xf8\x03\n" +
	"!GenerateUnboundMethodsEchoService\x12\x96\x01\n" +
	"\x04Echo\x12F.examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage\x1aF.examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage\x12\x9a\x01\n" +
	"\bEchoBody\x12F.examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage\x1aF.examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage\x12\x9c\x01\n" +
	"\n" +
	"EchoDelete\x12F.examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage\x1aF.examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessageBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDesc), len(file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDescData
}

var file_examples_internal_proto_examplepb_generate_unbound_methods_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_internal_proto_examplepb_generate_unbound_methods_proto_goTypes = []any{
	(*GenerateUnboundMethodsSimpleMessage)(nil), // 0: examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage
	(*durationpb.Duration)(nil),                 // 1: google.protobuf.Duration
}
var file_examples_internal_proto_examplepb_generate_unbound_methods_proto_depIdxs = []int32{
	1, // 0: examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage.duration:type_name -> google.protobuf.Duration
	0, // 1: examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService.Echo:input_type -> examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage
	0, // 2: examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService.EchoBody:input_type -> examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage
	0, // 3: examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService.EchoDelete:input_type -> examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage
	0, // 4: examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService.Echo:output_type -> examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage
	0, // 5: examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService.EchoBody:output_type -> examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage
	0, // 6: examples.internal.proto.examplepb.GenerateUnboundMethodsEchoService.EchoDelete:output_type -> examples.internal.proto.examplepb.GenerateUnboundMethodsSimpleMessage
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_generate_unbound_methods_proto_init() }
func file_examples_internal_proto_examplepb_generate_unbound_methods_proto_init() {
	if File_examples_internal_proto_examplepb_generate_unbound_methods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDesc), len(file_examples_internal_proto_examplepb_generate_unbound_methods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_generate_unbound_methods_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_generate_unbound_methods_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_generate_unbound_methods_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_generate_unbound_methods_proto = out.File
	file_examples_internal_proto_examplepb_generate_unbound_methods_proto_goTypes = nil
	file_examples_internal_proto_examplepb_generate_unbound_methods_proto_depIdxs = nil
}
