// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/generated_input.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_examples_internal_proto_examplepb_generated_input_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_generated_input_proto_rawDesc = "" +
	"\n" +
	"7examples/internal/proto/examplepb/generated_input.proto\x12!examples.internal.proto.examplepb\x1a;examples/internal/proto/examplepb/a_bit_of_everything.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\xa7\x01\n" +
	"\x10GeneratedService\x12\x92\x01\n" +
	"\x06Create\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a\x16.google.protobuf.Empty\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/example/a_bit_of_everything/generated_createBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var file_examples_internal_proto_examplepb_generated_input_proto_goTypes = []any{
	(*ABitOfEverything)(nil), // 0: examples.internal.proto.examplepb.ABitOfEverything
	(*emptypb.Empty)(nil),    // 1: google.protobuf.Empty
}
var file_examples_internal_proto_examplepb_generated_input_proto_depIdxs = []int32{
	0, // 0: examples.internal.proto.examplepb.GeneratedService.Create:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	1, // 1: examples.internal.proto.examplepb.GeneratedService.Create:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_generated_input_proto_init() }
func file_examples_internal_proto_examplepb_generated_input_proto_init() {
	if File_examples_internal_proto_examplepb_generated_input_proto != nil {
		return
	}
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_generated_input_proto_rawDesc), len(file_examples_internal_proto_examplepb_generated_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_generated_input_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_generated_input_proto_depIdxs,
	}.Build()
	File_examples_internal_proto_examplepb_generated_input_proto = out.File
	file_examples_internal_proto_examplepb_generated_input_proto_goTypes = nil
	file_examples_internal_proto_examplepb_generated_input_proto_depIdxs = nil
}
