// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/non_standard_names.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NonStandardMessage has oddly named fields.
type NonStandardMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num           int64                     `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	LineNum       int64                     `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	LangIdent     string                    `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	STATUS        string                    `protobuf:"bytes,5,opt,name=STATUS,proto3" json:"STATUS,omitempty"`
	En_GB         int64                     `protobuf:"varint,6,opt,name=en_GB,json=enGB,proto3" json:"en_GB,omitempty"`
	No            string                    `protobuf:"bytes,7,opt,name=no,proto3" json:"no,omitempty"`
	Thing         *NonStandardMessage_Thing `protobuf:"bytes,8,opt,name=thing,proto3" json:"thing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage) Reset() {
	*x = NonStandardMessage{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage) ProtoMessage() {}

func (x *NonStandardMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage.ProtoReflect.Descriptor instead.
func (*NonStandardMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{0}
}

func (x *NonStandardMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NonStandardMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NonStandardMessage) GetLineNum() int64 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *NonStandardMessage) GetLangIdent() string {
	if x != nil {
		return x.LangIdent
	}
	return ""
}

func (x *NonStandardMessage) GetSTATUS() string {
	if x != nil {
		return x.STATUS
	}
	return ""
}

func (x *NonStandardMessage) GetEn_GB() int64 {
	if x != nil {
		return x.En_GB
	}
	return 0
}

func (x *NonStandardMessage) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *NonStandardMessage) GetThing() *NonStandardMessage_Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

type NonStandardUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *NonStandardMessage    `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardUpdateRequest) Reset() {
	*x = NonStandardUpdateRequest{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardUpdateRequest) ProtoMessage() {}

func (x *NonStandardUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardUpdateRequest.ProtoReflect.Descriptor instead.
func (*NonStandardUpdateRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{1}
}

func (x *NonStandardUpdateRequest) GetBody() *NonStandardMessage {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NonStandardUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// NonStandardMessageWithJSONNames maps odd field names to odd JSON names for maximum confusion.
type NonStandardMessageWithJSONNames struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id            string                                 `protobuf:"bytes,1,opt,name=id,json=ID,proto3" json:"id,omitempty"`
	Num           int64                                  `protobuf:"varint,2,opt,name=Num,proto3" json:"Num,omitempty"`
	LineNum       int64                                  `protobuf:"varint,3,opt,name=line_num,json=LineNum,proto3" json:"line_num,omitempty"`
	LangIdent     string                                 `protobuf:"bytes,4,opt,name=langIdent,proto3" json:"langIdent,omitempty"`
	STATUS        string                                 `protobuf:"bytes,5,opt,name=STATUS,json=status,proto3" json:"STATUS,omitempty"`
	En_GB         int64                                  `protobuf:"varint,6,opt,name=en_GB,json=En_GB,proto3" json:"en_GB,omitempty"`
	No            string                                 `protobuf:"bytes,7,opt,name=no,json=yes,proto3" json:"no,omitempty"`
	Thing         *NonStandardMessageWithJSONNames_Thing `protobuf:"bytes,8,opt,name=thing,json=Thingy,proto3" json:"thing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames) Reset() {
	*x = NonStandardMessageWithJSONNames{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{2}
}

func (x *NonStandardMessageWithJSONNames) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetLineNum() int64 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetLangIdent() string {
	if x != nil {
		return x.LangIdent
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetSTATUS() string {
	if x != nil {
		return x.STATUS
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetEn_GB() int64 {
	if x != nil {
		return x.En_GB
	}
	return 0
}

func (x *NonStandardMessageWithJSONNames) GetNo() string {
	if x != nil {
		return x.No
	}
	return ""
}

func (x *NonStandardMessageWithJSONNames) GetThing() *NonStandardMessageWithJSONNames_Thing {
	if x != nil {
		return x.Thing
	}
	return nil
}

type NonStandardWithJSONNamesUpdateRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Body          *NonStandardMessageWithJSONNames `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask           `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardWithJSONNamesUpdateRequest) Reset() {
	*x = NonStandardWithJSONNamesUpdateRequest{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardWithJSONNamesUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardWithJSONNamesUpdateRequest) ProtoMessage() {}

func (x *NonStandardWithJSONNamesUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardWithJSONNamesUpdateRequest.ProtoReflect.Descriptor instead.
func (*NonStandardWithJSONNamesUpdateRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{3}
}

func (x *NonStandardWithJSONNamesUpdateRequest) GetBody() *NonStandardMessageWithJSONNames {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *NonStandardWithJSONNamesUpdateRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type NonStandardMessage_Thing struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	SubThing      *NonStandardMessage_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,proto3" json:"subThing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage_Thing) Reset() {
	*x = NonStandardMessage_Thing{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage_Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage_Thing) ProtoMessage() {}

func (x *NonStandardMessage_Thing) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage_Thing.ProtoReflect.Descriptor instead.
func (*NonStandardMessage_Thing) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{0, 0}
}

func (x *NonStandardMessage_Thing) GetSubThing() *NonStandardMessage_Thing_SubThing {
	if x != nil {
		return x.SubThing
	}
	return nil
}

type NonStandardMessage_Thing_SubThing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubValue      string                 `protobuf:"bytes,1,opt,name=sub_value,json=subValue,proto3" json:"sub_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessage_Thing_SubThing) Reset() {
	*x = NonStandardMessage_Thing_SubThing{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessage_Thing_SubThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessage_Thing_SubThing) ProtoMessage() {}

func (x *NonStandardMessage_Thing_SubThing) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessage_Thing_SubThing.ProtoReflect.Descriptor instead.
func (*NonStandardMessage_Thing_SubThing) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *NonStandardMessage_Thing_SubThing) GetSubValue() string {
	if x != nil {
		return x.SubValue
	}
	return ""
}

type NonStandardMessageWithJSONNames_Thing struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	SubThing      *NonStandardMessageWithJSONNames_Thing_SubThing `protobuf:"bytes,1,opt,name=subThing,json=SubThing,proto3" json:"subThing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames_Thing) Reset() {
	*x = NonStandardMessageWithJSONNames_Thing{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames_Thing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames_Thing) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames_Thing) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames_Thing.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames_Thing) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{2, 0}
}

func (x *NonStandardMessageWithJSONNames_Thing) GetSubThing() *NonStandardMessageWithJSONNames_Thing_SubThing {
	if x != nil {
		return x.SubThing
	}
	return nil
}

type NonStandardMessageWithJSONNames_Thing_SubThing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubValue      string                 `protobuf:"bytes,1,opt,name=sub_value,json=sub_Value,proto3" json:"sub_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) Reset() {
	*x = NonStandardMessageWithJSONNames_Thing_SubThing{}
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonStandardMessageWithJSONNames_Thing_SubThing) ProtoMessage() {}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonStandardMessageWithJSONNames_Thing_SubThing.ProtoReflect.Descriptor instead.
func (*NonStandardMessageWithJSONNames_Thing_SubThing) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *NonStandardMessageWithJSONNames_Thing_SubThing) GetSubValue() string {
	if x != nil {
		return x.SubValue
	}
	return ""
}

var File_examples_internal_proto_examplepb_non_standard_names_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_non_standard_names_proto_rawDesc = "" +
	"\n" +
	":examples/internal/proto/examplepb/non_standard_names.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\"\x94\x03\n" +
	"\x12NonStandardMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x19\n" +
	"\bline_num\x18\x03 \x01(\x03R\alineNum\x12\x1c\n" +
	"\tlangIdent\x18\x04 \x01(\tR\tlangIdent\x12\x16\n" +
	"\x06STATUS\x18\x05 \x01(\tR\x06STATUS\x12\x13\n" +
	"\x05en_GB\x18\x06 \x01(\x03R\x04enGB\x12\x0e\n" +
	"\x02no\x18\a \x01(\tR\x02no\x12Q\n" +
	"\x05thing\x18\b \x01(\v2;.examples.internal.proto.examplepb.NonStandardMessage.ThingR\x05thing\x1a\x92\x01\n" +
	"\x05Thing\x12`\n" +
	"\bsubThing\x18\x01 \x01(\v2D.examples.internal.proto.examplepb.NonStandardMessage.Thing.SubThingR\bsubThing\x1a'\n" +
	"\bSubThing\x12\x1b\n" +
	"\tsub_value\x18\x01 \x01(\tR\bsubValue\"\xa2\x01\n" +
	"\x18NonStandardUpdateRequest\x12I\n" +
	"\x04body\x18\x01 \x01(\v25.examples.internal.proto.examplepb.NonStandardMessageR\x04body\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"\xbf\x03\n" +
	"\x1fNonStandardMessageWithJSONNames\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02ID\x12\x10\n" +
	"\x03Num\x18\x02 \x01(\x03R\x03Num\x12\x19\n" +
	"\bline_num\x18\x03 \x01(\x03R\aLineNum\x12\x1c\n" +
	"\tlangIdent\x18\x04 \x01(\tR\tlangIdent\x12\x16\n" +
	"\x06STATUS\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05en_GB\x18\x06 \x01(\x03R\x05En_GB\x12\x0f\n" +
	"\x02no\x18\a \x01(\tR\x03yes\x12_\n" +
	"\x05thing\x18\b \x01(\v2H.examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.ThingR\x06Thingy\x1a\xa0\x01\n" +
	"\x05Thing\x12m\n" +
	"\bsubThing\x18\x01 \x01(\v2Q.examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.Thing.SubThingR\bSubThing\x1a(\n" +
	"\bSubThing\x12\x1c\n" +
	"\tsub_value\x18\x01 \x01(\tR\tsub_Value\"\xbc\x01\n" +
	"%NonStandardWithJSONNamesUpdateRequest\x12V\n" +
	"\x04body\x18\x01 \x01(\v2B.examples.internal.proto.examplepb.NonStandardMessageWithJSONNamesR\x04body\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask2\xa7\x03\n" +
	"\x12NonStandardService\x12\xab\x01\n" +
	"\x06Update\x12;.examples.internal.proto.examplepb.NonStandardUpdateRequest\x1a5.examples.internal.proto.examplepb.NonStandardMessage\"-\x82\xd3\xe4\x93\x02':\x04body2\x1f/v1/example/non_standard/update\x12\xe2\x01\n" +
	"\x13UpdateWithJSONNames\x12H.examples.internal.proto.examplepb.NonStandardWithJSONNamesUpdateRequest\x1aB.examples.internal.proto.examplepb.NonStandardMessageWithJSONNames\"=\x82\xd3\xe4\x93\x027:\x04body2//v1/example/non_standard/update_with_json_namesBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_non_standard_names_proto_rawDesc), len(file_examples_internal_proto_examplepb_non_standard_names_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_non_standard_names_proto_rawDescData
}

var file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_examples_internal_proto_examplepb_non_standard_names_proto_goTypes = []any{
	(*NonStandardMessage)(nil),                             // 0: examples.internal.proto.examplepb.NonStandardMessage
	(*NonStandardUpdateRequest)(nil),                       // 1: examples.internal.proto.examplepb.NonStandardUpdateRequest
	(*NonStandardMessageWithJSONNames)(nil),                // 2: examples.internal.proto.examplepb.NonStandardMessageWithJSONNames
	(*NonStandardWithJSONNamesUpdateRequest)(nil),          // 3: examples.internal.proto.examplepb.NonStandardWithJSONNamesUpdateRequest
	(*NonStandardMessage_Thing)(nil),                       // 4: examples.internal.proto.examplepb.NonStandardMessage.Thing
	(*NonStandardMessage_Thing_SubThing)(nil),              // 5: examples.internal.proto.examplepb.NonStandardMessage.Thing.SubThing
	(*NonStandardMessageWithJSONNames_Thing)(nil),          // 6: examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.Thing
	(*NonStandardMessageWithJSONNames_Thing_SubThing)(nil), // 7: examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.Thing.SubThing
	(*fieldmaskpb.FieldMask)(nil),                          // 8: google.protobuf.FieldMask
}
var file_examples_internal_proto_examplepb_non_standard_names_proto_depIdxs = []int32{
	4,  // 0: examples.internal.proto.examplepb.NonStandardMessage.thing:type_name -> examples.internal.proto.examplepb.NonStandardMessage.Thing
	0,  // 1: examples.internal.proto.examplepb.NonStandardUpdateRequest.body:type_name -> examples.internal.proto.examplepb.NonStandardMessage
	8,  // 2: examples.internal.proto.examplepb.NonStandardUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	6,  // 3: examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.thing:type_name -> examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.Thing
	2,  // 4: examples.internal.proto.examplepb.NonStandardWithJSONNamesUpdateRequest.body:type_name -> examples.internal.proto.examplepb.NonStandardMessageWithJSONNames
	8,  // 5: examples.internal.proto.examplepb.NonStandardWithJSONNamesUpdateRequest.update_mask:type_name -> google.protobuf.FieldMask
	5,  // 6: examples.internal.proto.examplepb.NonStandardMessage.Thing.subThing:type_name -> examples.internal.proto.examplepb.NonStandardMessage.Thing.SubThing
	7,  // 7: examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.Thing.subThing:type_name -> examples.internal.proto.examplepb.NonStandardMessageWithJSONNames.Thing.SubThing
	1,  // 8: examples.internal.proto.examplepb.NonStandardService.Update:input_type -> examples.internal.proto.examplepb.NonStandardUpdateRequest
	3,  // 9: examples.internal.proto.examplepb.NonStandardService.UpdateWithJSONNames:input_type -> examples.internal.proto.examplepb.NonStandardWithJSONNamesUpdateRequest
	0,  // 10: examples.internal.proto.examplepb.NonStandardService.Update:output_type -> examples.internal.proto.examplepb.NonStandardMessage
	2,  // 11: examples.internal.proto.examplepb.NonStandardService.UpdateWithJSONNames:output_type -> examples.internal.proto.examplepb.NonStandardMessageWithJSONNames
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_non_standard_names_proto_init() }
func file_examples_internal_proto_examplepb_non_standard_names_proto_init() {
	if File_examples_internal_proto_examplepb_non_standard_names_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_non_standard_names_proto_rawDesc), len(file_examples_internal_proto_examplepb_non_standard_names_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_non_standard_names_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_non_standard_names_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_non_standard_names_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_non_standard_names_proto = out.File
	file_examples_internal_proto_examplepb_non_standard_names_proto_goTypes = nil
	file_examples_internal_proto_examplepb_non_standard_names_proto_depIdxs = nil
}
