// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/openapi_merge_a.proto

// Merging Services
//
// This is an example of merging two proto files.

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InMessageA represents a message to ServiceA and ServiceC.
type InMessageA struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Here is the explanation about InMessageA.values
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InMessageA) Reset() {
	*x = InMessageA{}
	mi := &file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InMessageA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMessageA) ProtoMessage() {}

func (x *InMessageA) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMessageA.ProtoReflect.Descriptor instead.
func (*InMessageA) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescGZIP(), []int{0}
}

func (x *InMessageA) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// OutMessageA represents a message returned from ServiceA.
type OutMessageA struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Here is the explanation about OutMessageA.value
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutMessageA) Reset() {
	*x = OutMessageA{}
	mi := &file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutMessageA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessageA) ProtoMessage() {}

func (x *OutMessageA) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessageA.ProtoReflect.Descriptor instead.
func (*OutMessageA) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescGZIP(), []int{1}
}

func (x *OutMessageA) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// OutMessageC represents a message returned from ServiceC.
type OutMessageC struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Here is the explanation about OutMessageC.value
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutMessageC) Reset() {
	*x = OutMessageC{}
	mi := &file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutMessageC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessageC) ProtoMessage() {}

func (x *OutMessageC) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessageC.ProtoReflect.Descriptor instead.
func (*OutMessageC) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescGZIP(), []int{2}
}

func (x *OutMessageC) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_examples_internal_proto_examplepb_openapi_merge_a_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDesc = "" +
	"\n" +
	"7examples/internal/proto/examplepb/openapi_merge_a.proto\x12\x1bexamples.internal.examplepb\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\n" +
	"InMessageA\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"#\n" +
	"\vOutMessageA\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"#\n" +
	"\vOutMessageC\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2\x82\x02\n" +
	"\bServiceA\x12z\n" +
	"\tMethodOne\x12'.examples.internal.examplepb.InMessageA\x1a(.examples.internal.examplepb.OutMessageA\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/example/a/1\x12z\n" +
	"\tMethodTwo\x12(.examples.internal.examplepb.OutMessageA\x1a'.examples.internal.examplepb.InMessageA\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/example/a/22\x82\x02\n" +
	"\bServiceC\x12z\n" +
	"\tMethodOne\x12'.examples.internal.examplepb.InMessageA\x1a(.examples.internal.examplepb.OutMessageC\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/example/c/1\x12z\n" +
	"\tMethodTwo\x12(.examples.internal.examplepb.OutMessageA\x1a'.examples.internal.examplepb.InMessageA\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/example/c/2BMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDesc), len(file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDescData
}

var file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_internal_proto_examplepb_openapi_merge_a_proto_goTypes = []any{
	(*InMessageA)(nil),  // 0: examples.internal.examplepb.InMessageA
	(*OutMessageA)(nil), // 1: examples.internal.examplepb.OutMessageA
	(*OutMessageC)(nil), // 2: examples.internal.examplepb.OutMessageC
}
var file_examples_internal_proto_examplepb_openapi_merge_a_proto_depIdxs = []int32{
	0, // 0: examples.internal.examplepb.ServiceA.MethodOne:input_type -> examples.internal.examplepb.InMessageA
	1, // 1: examples.internal.examplepb.ServiceA.MethodTwo:input_type -> examples.internal.examplepb.OutMessageA
	0, // 2: examples.internal.examplepb.ServiceC.MethodOne:input_type -> examples.internal.examplepb.InMessageA
	1, // 3: examples.internal.examplepb.ServiceC.MethodTwo:input_type -> examples.internal.examplepb.OutMessageA
	1, // 4: examples.internal.examplepb.ServiceA.MethodOne:output_type -> examples.internal.examplepb.OutMessageA
	0, // 5: examples.internal.examplepb.ServiceA.MethodTwo:output_type -> examples.internal.examplepb.InMessageA
	2, // 6: examples.internal.examplepb.ServiceC.MethodOne:output_type -> examples.internal.examplepb.OutMessageC
	0, // 7: examples.internal.examplepb.ServiceC.MethodTwo:output_type -> examples.internal.examplepb.InMessageA
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_openapi_merge_a_proto_init() }
func file_examples_internal_proto_examplepb_openapi_merge_a_proto_init() {
	if File_examples_internal_proto_examplepb_openapi_merge_a_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDesc), len(file_examples_internal_proto_examplepb_openapi_merge_a_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_examples_internal_proto_examplepb_openapi_merge_a_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_openapi_merge_a_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_openapi_merge_a_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_openapi_merge_a_proto = out.File
	file_examples_internal_proto_examplepb_openapi_merge_a_proto_goTypes = nil
	file_examples_internal_proto_examplepb_openapi_merge_a_proto_depIdxs = nil
}
