// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/openapi_merge_b.proto

// Merging Services
//
// This is an example of merging two proto files.

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InMessageB represents a message to ServiceB.
type InMessageB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Here is the explanation about InMessageB.values
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InMessageB) Reset() {
	*x = InMessageB{}
	mi := &file_examples_internal_proto_examplepb_openapi_merge_b_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InMessageB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMessageB) ProtoMessage() {}

func (x *InMessageB) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_openapi_merge_b_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMessageB.ProtoReflect.Descriptor instead.
func (*InMessageB) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescGZIP(), []int{0}
}

func (x *InMessageB) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// OutMessageB represents a message returned from ServiceB.
type OutMessageB struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Here is the explanation about OutMessageB.value
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutMessageB) Reset() {
	*x = OutMessageB{}
	mi := &file_examples_internal_proto_examplepb_openapi_merge_b_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutMessageB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessageB) ProtoMessage() {}

func (x *OutMessageB) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_openapi_merge_b_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessageB.ProtoReflect.Descriptor instead.
func (*OutMessageB) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescGZIP(), []int{1}
}

func (x *OutMessageB) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_examples_internal_proto_examplepb_openapi_merge_b_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDesc = "" +
	"\n" +
	"7examples/internal/proto/examplepb/openapi_merge_b.proto\x12\x1bexamples.internal.examplepb\x1a\x1cgoogle/api/annotations.proto\"\"\n" +
	"\n" +
	"InMessageB\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"%\n" +
	"\vOutMessageB\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values2\x82\x02\n" +
	"\bServiceB\x12z\n" +
	"\tMethodOne\x12'.examples.internal.examplepb.InMessageB\x1a(.examples.internal.examplepb.OutMessageB\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/example/b/1\x12z\n" +
	"\tMethodTwo\x12(.examples.internal.examplepb.OutMessageB\x1a'.examples.internal.examplepb.InMessageB\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/example/b/2BMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDesc), len(file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDescData
}

var file_examples_internal_proto_examplepb_openapi_merge_b_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_internal_proto_examplepb_openapi_merge_b_proto_goTypes = []any{
	(*InMessageB)(nil),  // 0: examples.internal.examplepb.InMessageB
	(*OutMessageB)(nil), // 1: examples.internal.examplepb.OutMessageB
}
var file_examples_internal_proto_examplepb_openapi_merge_b_proto_depIdxs = []int32{
	0, // 0: examples.internal.examplepb.ServiceB.MethodOne:input_type -> examples.internal.examplepb.InMessageB
	1, // 1: examples.internal.examplepb.ServiceB.MethodTwo:input_type -> examples.internal.examplepb.OutMessageB
	1, // 2: examples.internal.examplepb.ServiceB.MethodOne:output_type -> examples.internal.examplepb.OutMessageB
	0, // 3: examples.internal.examplepb.ServiceB.MethodTwo:output_type -> examples.internal.examplepb.InMessageB
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_openapi_merge_b_proto_init() }
func file_examples_internal_proto_examplepb_openapi_merge_b_proto_init() {
	if File_examples_internal_proto_examplepb_openapi_merge_b_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDesc), len(file_examples_internal_proto_examplepb_openapi_merge_b_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_openapi_merge_b_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_openapi_merge_b_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_openapi_merge_b_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_openapi_merge_b_proto = out.File
	file_examples_internal_proto_examplepb_openapi_merge_b_proto_goTypes = nil
	file_examples_internal_proto_examplepb_openapi_merge_b_proto_depIdxs = nil
}
