// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/remove_internal_comment.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Foo2Request (-- This comment should be excluded from OpenAPI output --)
type Foo2Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Username.
	// (-- This comment should be excluded
	// from OpenAPI output --)
	// Same row, single line break doesn't count on markdown.
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// Password.
	// (-- This comment should be excluded
	// from OpenAPI output --)
	//
	// New row.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo2Request) Reset() {
	*x = Foo2Request{}
	mi := &file_examples_internal_proto_examplepb_remove_internal_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo2Request) ProtoMessage() {}

func (x *Foo2Request) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_remove_internal_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo2Request.ProtoReflect.Descriptor instead.
func (*Foo2Request) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Foo2Request) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Foo2Request) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// (-- This comment should be excluded from OpenAPI output --)
type Foo2Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Foo2Reply) Reset() {
	*x = Foo2Reply{}
	mi := &file_examples_internal_proto_examplepb_remove_internal_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Foo2Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo2Reply) ProtoMessage() {}

func (x *Foo2Reply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_remove_internal_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo2Reply.ProtoReflect.Descriptor instead.
func (*Foo2Reply) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescGZIP(), []int{1}
}

var File_examples_internal_proto_examplepb_remove_internal_comment_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDesc = "" +
	"\n" +
	"?examples/internal/proto/examplepb/remove_internal_comment.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\"E\n" +
	"\vFoo2Request\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\v\n" +
	"\tFoo2Reply2\x90\x01\n" +
	"\vFoo2Service\x12\x80\x01\n" +
	"\x04Foo2\x12..examples.internal.proto.examplepb.Foo2Request\x1a,.examples.internal.proto.examplepb.Foo2Reply\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/example/fooBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDesc), len(file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDescData
}

var file_examples_internal_proto_examplepb_remove_internal_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_internal_proto_examplepb_remove_internal_comment_proto_goTypes = []any{
	(*Foo2Request)(nil), // 0: examples.internal.proto.examplepb.Foo2Request
	(*Foo2Reply)(nil),   // 1: examples.internal.proto.examplepb.Foo2Reply
}
var file_examples_internal_proto_examplepb_remove_internal_comment_proto_depIdxs = []int32{
	0, // 0: examples.internal.proto.examplepb.Foo2Service.Foo2:input_type -> examples.internal.proto.examplepb.Foo2Request
	1, // 1: examples.internal.proto.examplepb.Foo2Service.Foo2:output_type -> examples.internal.proto.examplepb.Foo2Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_remove_internal_comment_proto_init() }
func file_examples_internal_proto_examplepb_remove_internal_comment_proto_init() {
	if File_examples_internal_proto_examplepb_remove_internal_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDesc), len(file_examples_internal_proto_examplepb_remove_internal_comment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_remove_internal_comment_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_remove_internal_comment_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_remove_internal_comment_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_remove_internal_comment_proto = out.File
	file_examples_internal_proto_examplepb_remove_internal_comment_proto_goTypes = nil
	file_examples_internal_proto_examplepb_remove_internal_comment_proto_depIdxs = nil
}
