// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/response_body_service.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RepeatedResponseBodyOut_Response_ResponseType int32

const (
	// UNKNOWN
	RepeatedResponseBodyOut_Response_UNKNOWN RepeatedResponseBodyOut_Response_ResponseType = 0
	// A is 1
	RepeatedResponseBodyOut_Response_A RepeatedResponseBodyOut_Response_ResponseType = 1
	// B is 2
	RepeatedResponseBodyOut_Response_B RepeatedResponseBodyOut_Response_ResponseType = 2
)

// Enum value maps for RepeatedResponseBodyOut_Response_ResponseType.
var (
	RepeatedResponseBodyOut_Response_ResponseType_name = map[int32]string{
		0: "UNKNOWN",
		1: "A",
		2: "B",
	}
	RepeatedResponseBodyOut_Response_ResponseType_value = map[string]int32{
		"UNKNOWN": 0,
		"A":       1,
		"B":       2,
	}
)

func (x RepeatedResponseBodyOut_Response_ResponseType) Enum() *RepeatedResponseBodyOut_Response_ResponseType {
	p := new(RepeatedResponseBodyOut_Response_ResponseType)
	*p = x
	return p
}

func (x RepeatedResponseBodyOut_Response_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepeatedResponseBodyOut_Response_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_response_body_service_proto_enumTypes[0].Descriptor()
}

func (RepeatedResponseBodyOut_Response_ResponseType) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_response_body_service_proto_enumTypes[0]
}

func (x RepeatedResponseBodyOut_Response_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepeatedResponseBodyOut_Response_ResponseType.Descriptor instead.
func (RepeatedResponseBodyOut_Response_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{2, 0, 0}
}

type ResponseBodyIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBodyIn) Reset() {
	*x = ResponseBodyIn{}
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyIn) ProtoMessage() {}

func (x *ResponseBodyIn) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyIn.ProtoReflect.Descriptor instead.
func (*ResponseBodyIn) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseBodyIn) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ResponseBodyOut struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Response      *ResponseBodyOut_Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBodyOut) Reset() {
	*x = ResponseBodyOut{}
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyOut) ProtoMessage() {}

func (x *ResponseBodyOut) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyOut.ProtoReflect.Descriptor instead.
func (*ResponseBodyOut) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseBodyOut) GetResponse() *ResponseBodyOut_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type RepeatedResponseBodyOut struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Response      []*RepeatedResponseBodyOut_Response `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedResponseBodyOut) Reset() {
	*x = RepeatedResponseBodyOut{}
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedResponseBodyOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponseBodyOut) ProtoMessage() {}

func (x *RepeatedResponseBodyOut) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponseBodyOut.ProtoReflect.Descriptor instead.
func (*RepeatedResponseBodyOut) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{2}
}

func (x *RepeatedResponseBodyOut) GetResponse() []*RepeatedResponseBodyOut_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type RepeatedResponseStrings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedResponseStrings) Reset() {
	*x = RepeatedResponseStrings{}
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedResponseStrings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponseStrings) ProtoMessage() {}

func (x *RepeatedResponseStrings) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponseStrings.ProtoReflect.Descriptor instead.
func (*RepeatedResponseStrings) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{3}
}

func (x *RepeatedResponseStrings) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type ResponseBodyValue struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ResponseBodyValue string                 `protobuf:"bytes,1,opt,name=response_body_value,json=responseBodyValue,proto3" json:"response_body_value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResponseBodyValue) Reset() {
	*x = ResponseBodyValue{}
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyValue) ProtoMessage() {}

func (x *ResponseBodyValue) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyValue.ProtoReflect.Descriptor instead.
func (*ResponseBodyValue) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseBodyValue) GetResponseBodyValue() string {
	if x != nil {
		return x.ResponseBodyValue
	}
	return ""
}

type ResponseBodyOut_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBodyOut_Response) Reset() {
	*x = ResponseBodyOut_Response{}
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBodyOut_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBodyOut_Response) ProtoMessage() {}

func (x *ResponseBodyOut_Response) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBodyOut_Response.ProtoReflect.Descriptor instead.
func (*ResponseBodyOut_Response) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ResponseBodyOut_Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RepeatedResponseBodyOut_Response struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Data          string                                        `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Type          RepeatedResponseBodyOut_Response_ResponseType `protobuf:"varint,3,opt,name=type,proto3,enum=examples.internal.proto.examplepb.RepeatedResponseBodyOut_Response_ResponseType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatedResponseBodyOut_Response) Reset() {
	*x = RepeatedResponseBodyOut_Response{}
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatedResponseBodyOut_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatedResponseBodyOut_Response) ProtoMessage() {}

func (x *RepeatedResponseBodyOut_Response) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatedResponseBodyOut_Response.ProtoReflect.Descriptor instead.
func (*RepeatedResponseBodyOut_Response) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RepeatedResponseBodyOut_Response) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *RepeatedResponseBodyOut_Response) GetType() RepeatedResponseBodyOut_Response_ResponseType {
	if x != nil {
		return x.Type
	}
	return RepeatedResponseBodyOut_Response_UNKNOWN
}

var File_examples_internal_proto_examplepb_response_body_service_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_response_body_service_proto_rawDesc = "" +
	"\n" +
	"=examples/internal/proto/examplepb/response_body_service.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\x0eResponseBodyIn\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\x8a\x01\n" +
	"\x0fResponseBodyOut\x12W\n" +
	"\bresponse\x18\x02 \x01(\v2;.examples.internal.proto.examplepb.ResponseBodyOut.ResponseR\bresponse\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\xac\x02\n" +
	"\x17RepeatedResponseBodyOut\x12_\n" +
	"\bresponse\x18\x02 \x03(\v2C.examples.internal.proto.examplepb.RepeatedResponseBodyOut.ResponseR\bresponse\x1a\xaf\x01\n" +
	"\bResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12d\n" +
	"\x04type\x18\x03 \x01(\x0e2P.examples.internal.proto.examplepb.RepeatedResponseBodyOut.Response.ResponseTypeR\x04type\")\n" +
	"\fResponseType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x05\n" +
	"\x01A\x10\x01\x12\x05\n" +
	"\x01B\x10\x02\"1\n" +
	"\x17RepeatedResponseStrings\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"C\n" +
	"\x11ResponseBodyValue\x12.\n" +
	"\x13response_body_value\x18\x01 \x01(\tR\x11responseBodyValue2\x8b\a\n" +
	"\x13ResponseBodyService\x12\xa0\x01\n" +
	"\x0fGetResponseBody\x121.examples.internal.proto.examplepb.ResponseBodyIn\x1a2.examples.internal.proto.examplepb.ResponseBodyOut\"&\x82\xd3\xe4\x93\x02 b\bresponse\x12\x14/responsebody/{data}\x12\xad\x01\n" +
	"\x12ListResponseBodies\x121.examples.internal.proto.examplepb.ResponseBodyIn\x1a:.examples.internal.proto.examplepb.RepeatedResponseBodyOut\"(\x82\xd3\xe4\x93\x02\"b\bresponse\x12\x16/responsebodies/{data}\x12\xad\x01\n" +
	"\x13ListResponseStrings\x121.examples.internal.proto.examplepb.ResponseBodyIn\x1a:.examples.internal.proto.examplepb.RepeatedResponseStrings\"'\x82\xd3\xe4\x93\x02!b\x06values\x12\x17/responsestrings/{data}\x12\xaf\x01\n" +
	"\x15GetResponseBodyStream\x121.examples.internal.proto.examplepb.ResponseBodyIn\x1a2.examples.internal.proto.examplepb.ResponseBodyOut\"-\x82\xd3\xe4\x93\x02'b\bresponse\x12\x1b/responsebody/stream/{data}0\x01\x12\xbe\x01\n" +
	"\x17GetResponseBodySameName\x121.examples.internal.proto.examplepb.ResponseBodyIn\x1a4.examples.internal.proto.examplepb.ResponseBodyValue\":\x82\xd3\xe4\x93\x024b\x13response_body_value\x12\x1d/responsebody/samename/{data}BMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_response_body_service_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_response_body_service_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_response_body_service_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_response_body_service_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_response_body_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_response_body_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_response_body_service_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_response_body_service_proto_rawDescData
}

var file_examples_internal_proto_examplepb_response_body_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_examples_internal_proto_examplepb_response_body_service_proto_goTypes = []any{
	(RepeatedResponseBodyOut_Response_ResponseType)(0), // 0: examples.internal.proto.examplepb.RepeatedResponseBodyOut.Response.ResponseType
	(*ResponseBodyIn)(nil),                             // 1: examples.internal.proto.examplepb.ResponseBodyIn
	(*ResponseBodyOut)(nil),                            // 2: examples.internal.proto.examplepb.ResponseBodyOut
	(*RepeatedResponseBodyOut)(nil),                    // 3: examples.internal.proto.examplepb.RepeatedResponseBodyOut
	(*RepeatedResponseStrings)(nil),                    // 4: examples.internal.proto.examplepb.RepeatedResponseStrings
	(*ResponseBodyValue)(nil),                          // 5: examples.internal.proto.examplepb.ResponseBodyValue
	(*ResponseBodyOut_Response)(nil),                   // 6: examples.internal.proto.examplepb.ResponseBodyOut.Response
	(*RepeatedResponseBodyOut_Response)(nil),           // 7: examples.internal.proto.examplepb.RepeatedResponseBodyOut.Response
}
var file_examples_internal_proto_examplepb_response_body_service_proto_depIdxs = []int32{
	6, // 0: examples.internal.proto.examplepb.ResponseBodyOut.response:type_name -> examples.internal.proto.examplepb.ResponseBodyOut.Response
	7, // 1: examples.internal.proto.examplepb.RepeatedResponseBodyOut.response:type_name -> examples.internal.proto.examplepb.RepeatedResponseBodyOut.Response
	0, // 2: examples.internal.proto.examplepb.RepeatedResponseBodyOut.Response.type:type_name -> examples.internal.proto.examplepb.RepeatedResponseBodyOut.Response.ResponseType
	1, // 3: examples.internal.proto.examplepb.ResponseBodyService.GetResponseBody:input_type -> examples.internal.proto.examplepb.ResponseBodyIn
	1, // 4: examples.internal.proto.examplepb.ResponseBodyService.ListResponseBodies:input_type -> examples.internal.proto.examplepb.ResponseBodyIn
	1, // 5: examples.internal.proto.examplepb.ResponseBodyService.ListResponseStrings:input_type -> examples.internal.proto.examplepb.ResponseBodyIn
	1, // 6: examples.internal.proto.examplepb.ResponseBodyService.GetResponseBodyStream:input_type -> examples.internal.proto.examplepb.ResponseBodyIn
	1, // 7: examples.internal.proto.examplepb.ResponseBodyService.GetResponseBodySameName:input_type -> examples.internal.proto.examplepb.ResponseBodyIn
	2, // 8: examples.internal.proto.examplepb.ResponseBodyService.GetResponseBody:output_type -> examples.internal.proto.examplepb.ResponseBodyOut
	3, // 9: examples.internal.proto.examplepb.ResponseBodyService.ListResponseBodies:output_type -> examples.internal.proto.examplepb.RepeatedResponseBodyOut
	4, // 10: examples.internal.proto.examplepb.ResponseBodyService.ListResponseStrings:output_type -> examples.internal.proto.examplepb.RepeatedResponseStrings
	2, // 11: examples.internal.proto.examplepb.ResponseBodyService.GetResponseBodyStream:output_type -> examples.internal.proto.examplepb.ResponseBodyOut
	5, // 12: examples.internal.proto.examplepb.ResponseBodyService.GetResponseBodySameName:output_type -> examples.internal.proto.examplepb.ResponseBodyValue
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_response_body_service_proto_init() }
func file_examples_internal_proto_examplepb_response_body_service_proto_init() {
	if File_examples_internal_proto_examplepb_response_body_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_response_body_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_response_body_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_response_body_service_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_response_body_service_proto_depIdxs,
		EnumInfos:         file_examples_internal_proto_examplepb_response_body_service_proto_enumTypes,
		MessageInfos:      file_examples_internal_proto_examplepb_response_body_service_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_response_body_service_proto = out.File
	file_examples_internal_proto_examplepb_response_body_service_proto_goTypes = nil
	file_examples_internal_proto_examplepb_response_body_service_proto_depIdxs = nil
}
