// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/stream.proto

package examplepb

import (
	sub "github.com/essapp/grpc-gateway-example/v2/examples/internal/proto/sub"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         bool                   `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_examples_internal_proto_examplepb_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Options) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

var File_examples_internal_proto_examplepb_stream_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_stream_proto_rawDesc = "" +
	"\n" +
	".examples/internal/proto/examplepb/stream.proto\x12!examples.internal.proto.examplepb\x1a;examples/internal/proto/examplepb/a_bit_of_everything.proto\x1a)examples/internal/proto/sub/message.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x1f\n" +
	"\aOptions\x12\x14\n" +
	"\x05error\x18\x01 \x01(\bR\x05error2\xc4\x05\n" +
	"\rStreamService\x12\x8c\x01\n" +
	"\n" +
	"BulkCreate\x123.examples.internal.proto.examplepb.ABitOfEverything\x1a\x16.google.protobuf.Empty\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/example/a_bit_of_everything/bulk(\x01\x12\x92\x01\n" +
	"\x04List\x12*.examples.internal.proto.examplepb.Options\x1a3.examples.internal.proto.examplepb.ABitOfEverything\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/example/a_bit_of_everything0\x01\x12\x97\x01\n" +
	"\bBulkEcho\x12*.examples.internal.proto.sub.StringMessage\x1a*.examples.internal.proto.sub.StringMessage\"/\x82\xd3\xe4\x93\x02):\x01*\"$/v1/example/a_bit_of_everything/echo(\x010\x01\x12\x86\x01\n" +
	"\x10BulkEchoDuration\x12\x19.google.protobuf.Duration\x1a\x19.google.protobuf.Duration\"8\x82\xd3\xe4\x93\x022:\x01*\"-/v1/example/a_bit_of_everything/echo_duration(\x010\x01\x12l\n" +
	"\bDownload\x12*.examples.internal.proto.examplepb.Options\x1a\x14.google.api.HttpBody\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/example/download0\x01BMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_stream_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_stream_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_stream_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_stream_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_stream_proto_rawDesc), len(file_examples_internal_proto_examplepb_stream_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_stream_proto_rawDescData
}

var file_examples_internal_proto_examplepb_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_internal_proto_examplepb_stream_proto_goTypes = []any{
	(*Options)(nil),             // 0: examples.internal.proto.examplepb.Options
	(*ABitOfEverything)(nil),    // 1: examples.internal.proto.examplepb.ABitOfEverything
	(*sub.StringMessage)(nil),   // 2: examples.internal.proto.sub.StringMessage
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
	(*emptypb.Empty)(nil),       // 4: google.protobuf.Empty
	(*httpbody.HttpBody)(nil),   // 5: google.api.HttpBody
}
var file_examples_internal_proto_examplepb_stream_proto_depIdxs = []int32{
	1, // 0: examples.internal.proto.examplepb.StreamService.BulkCreate:input_type -> examples.internal.proto.examplepb.ABitOfEverything
	0, // 1: examples.internal.proto.examplepb.StreamService.List:input_type -> examples.internal.proto.examplepb.Options
	2, // 2: examples.internal.proto.examplepb.StreamService.BulkEcho:input_type -> examples.internal.proto.sub.StringMessage
	3, // 3: examples.internal.proto.examplepb.StreamService.BulkEchoDuration:input_type -> google.protobuf.Duration
	0, // 4: examples.internal.proto.examplepb.StreamService.Download:input_type -> examples.internal.proto.examplepb.Options
	4, // 5: examples.internal.proto.examplepb.StreamService.BulkCreate:output_type -> google.protobuf.Empty
	1, // 6: examples.internal.proto.examplepb.StreamService.List:output_type -> examples.internal.proto.examplepb.ABitOfEverything
	2, // 7: examples.internal.proto.examplepb.StreamService.BulkEcho:output_type -> examples.internal.proto.sub.StringMessage
	3, // 8: examples.internal.proto.examplepb.StreamService.BulkEchoDuration:output_type -> google.protobuf.Duration
	5, // 9: examples.internal.proto.examplepb.StreamService.Download:output_type -> google.api.HttpBody
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_stream_proto_init() }
func file_examples_internal_proto_examplepb_stream_proto_init() {
	if File_examples_internal_proto_examplepb_stream_proto != nil {
		return
	}
	file_examples_internal_proto_examplepb_a_bit_of_everything_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_stream_proto_rawDesc), len(file_examples_internal_proto_examplepb_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_stream_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_stream_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_stream_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_stream_proto = out.File
	file_examples_internal_proto_examplepb_stream_proto_goTypes = nil
	file_examples_internal_proto_examplepb_stream_proto_depIdxs = nil
}
