// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/unannotated_echo_service.proto

// Unannotated Echo Service
// Similar to echo_service.proto but without annotations. See
// unannotated_echo_service.yaml for the equivalent of the annotations in
// gRPC API configuration format.
//
// Echo Service API consists of a single service which returns
// a message.

package examplepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Embedded represents a message embedded in SimpleMessage.
type UnannotatedEmbedded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mark:
	//
	//	*UnannotatedEmbedded_Progress
	//	*UnannotatedEmbedded_Note
	Mark          isUnannotatedEmbedded_Mark `protobuf_oneof:"mark"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnannotatedEmbedded) Reset() {
	*x = UnannotatedEmbedded{}
	mi := &file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnannotatedEmbedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnannotatedEmbedded) ProtoMessage() {}

func (x *UnannotatedEmbedded) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnannotatedEmbedded.ProtoReflect.Descriptor instead.
func (*UnannotatedEmbedded) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescGZIP(), []int{0}
}

func (x *UnannotatedEmbedded) GetMark() isUnannotatedEmbedded_Mark {
	if x != nil {
		return x.Mark
	}
	return nil
}

func (x *UnannotatedEmbedded) GetProgress() int64 {
	if x != nil {
		if x, ok := x.Mark.(*UnannotatedEmbedded_Progress); ok {
			return x.Progress
		}
	}
	return 0
}

func (x *UnannotatedEmbedded) GetNote() string {
	if x != nil {
		if x, ok := x.Mark.(*UnannotatedEmbedded_Note); ok {
			return x.Note
		}
	}
	return ""
}

type isUnannotatedEmbedded_Mark interface {
	isUnannotatedEmbedded_Mark()
}

type UnannotatedEmbedded_Progress struct {
	Progress int64 `protobuf:"varint,1,opt,name=progress,proto3,oneof"`
}

type UnannotatedEmbedded_Note struct {
	Note string `protobuf:"bytes,2,opt,name=note,proto3,oneof"`
}

func (*UnannotatedEmbedded_Progress) isUnannotatedEmbedded_Mark() {}

func (*UnannotatedEmbedded_Note) isUnannotatedEmbedded_Mark() {}

type UnannotatedNestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NId           string                 `protobuf:"bytes,1,opt,name=n_id,json=nId,proto3" json:"n_id,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnannotatedNestedMessage) Reset() {
	*x = UnannotatedNestedMessage{}
	mi := &file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnannotatedNestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnannotatedNestedMessage) ProtoMessage() {}

func (x *UnannotatedNestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnannotatedNestedMessage.ProtoReflect.Descriptor instead.
func (*UnannotatedNestedMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescGZIP(), []int{1}
}

func (x *UnannotatedNestedMessage) GetNId() string {
	if x != nil {
		return x.NId
	}
	return ""
}

func (x *UnannotatedNestedMessage) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

// UnannotatedSimpleMessage represents a simple message sent to the unannotated Echo service.
type UnannotatedSimpleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id       string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num      int64                `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	Duration *durationpb.Duration `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	// Types that are valid to be assigned to Code:
	//
	//	*UnannotatedSimpleMessage_LineNum
	//	*UnannotatedSimpleMessage_Lang
	Code   isUnannotatedSimpleMessage_Code `protobuf_oneof:"code"`
	Status *UnannotatedEmbedded            `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Ext:
	//
	//	*UnannotatedSimpleMessage_En
	//	*UnannotatedSimpleMessage_No
	Ext           isUnannotatedSimpleMessage_Ext `protobuf_oneof:"ext"`
	ResourceId    string                         `protobuf:"bytes,9,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	NId           *UnannotatedNestedMessage      `protobuf:"bytes,10,opt,name=n_id,json=nId,proto3" json:"n_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnannotatedSimpleMessage) Reset() {
	*x = UnannotatedSimpleMessage{}
	mi := &file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnannotatedSimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnannotatedSimpleMessage) ProtoMessage() {}

func (x *UnannotatedSimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnannotatedSimpleMessage.ProtoReflect.Descriptor instead.
func (*UnannotatedSimpleMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescGZIP(), []int{2}
}

func (x *UnannotatedSimpleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UnannotatedSimpleMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *UnannotatedSimpleMessage) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *UnannotatedSimpleMessage) GetCode() isUnannotatedSimpleMessage_Code {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *UnannotatedSimpleMessage) GetLineNum() int64 {
	if x != nil {
		if x, ok := x.Code.(*UnannotatedSimpleMessage_LineNum); ok {
			return x.LineNum
		}
	}
	return 0
}

func (x *UnannotatedSimpleMessage) GetLang() string {
	if x != nil {
		if x, ok := x.Code.(*UnannotatedSimpleMessage_Lang); ok {
			return x.Lang
		}
	}
	return ""
}

func (x *UnannotatedSimpleMessage) GetStatus() *UnannotatedEmbedded {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UnannotatedSimpleMessage) GetExt() isUnannotatedSimpleMessage_Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *UnannotatedSimpleMessage) GetEn() int64 {
	if x != nil {
		if x, ok := x.Ext.(*UnannotatedSimpleMessage_En); ok {
			return x.En
		}
	}
	return 0
}

func (x *UnannotatedSimpleMessage) GetNo() *UnannotatedEmbedded {
	if x != nil {
		if x, ok := x.Ext.(*UnannotatedSimpleMessage_No); ok {
			return x.No
		}
	}
	return nil
}

func (x *UnannotatedSimpleMessage) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UnannotatedSimpleMessage) GetNId() *UnannotatedNestedMessage {
	if x != nil {
		return x.NId
	}
	return nil
}

type isUnannotatedSimpleMessage_Code interface {
	isUnannotatedSimpleMessage_Code()
}

type UnannotatedSimpleMessage_LineNum struct {
	LineNum int64 `protobuf:"varint,4,opt,name=line_num,json=lineNum,proto3,oneof"`
}

type UnannotatedSimpleMessage_Lang struct {
	Lang string `protobuf:"bytes,5,opt,name=lang,proto3,oneof"`
}

func (*UnannotatedSimpleMessage_LineNum) isUnannotatedSimpleMessage_Code() {}

func (*UnannotatedSimpleMessage_Lang) isUnannotatedSimpleMessage_Code() {}

type isUnannotatedSimpleMessage_Ext interface {
	isUnannotatedSimpleMessage_Ext()
}

type UnannotatedSimpleMessage_En struct {
	En int64 `protobuf:"varint,7,opt,name=en,proto3,oneof"`
}

type UnannotatedSimpleMessage_No struct {
	No *UnannotatedEmbedded `protobuf:"bytes,8,opt,name=no,proto3,oneof"`
}

func (*UnannotatedSimpleMessage_En) isUnannotatedSimpleMessage_Ext() {}

func (*UnannotatedSimpleMessage_No) isUnannotatedSimpleMessage_Ext() {}

var File_examples_internal_proto_examplepb_unannotated_echo_service_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDesc = "" +
	"\n" +
	"@examples/internal/proto/examplepb/unannotated_echo_service.proto\x12!examples.internal.proto.examplepb\x1a\x1egoogle/protobuf/duration.proto\"Q\n" +
	"\x13UnannotatedEmbedded\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\x03H\x00R\bprogress\x12\x14\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04noteB\x06\n" +
	"\x04mark\"?\n" +
	"\x18UnannotatedNestedMessage\x12\x11\n" +
	"\x04n_id\x18\x01 \x01(\tR\x03nId\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\"\xd2\x03\n" +
	"\x18UnannotatedSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12\x1b\n" +
	"\bline_num\x18\x04 \x01(\x03H\x00R\alineNum\x12\x14\n" +
	"\x04lang\x18\x05 \x01(\tH\x00R\x04lang\x12N\n" +
	"\x06status\x18\x06 \x01(\v26.examples.internal.proto.examplepb.UnannotatedEmbeddedR\x06status\x12\x10\n" +
	"\x02en\x18\a \x01(\x03H\x01R\x02en\x12H\n" +
	"\x02no\x18\b \x01(\v26.examples.internal.proto.examplepb.UnannotatedEmbeddedH\x01R\x02no\x12\x1f\n" +
	"\vresource_id\x18\t \x01(\tR\n" +
	"resourceId\x12N\n" +
	"\x04n_id\x18\n" +
	" \x01(\v2;.examples.internal.proto.examplepb.UnannotatedNestedMessageR\x03nIdB\x06\n" +
	"\x04codeB\x05\n" +
	"\x03ext2\xb4\x04\n" +
	"\x16UnannotatedEchoService\x12\x80\x01\n" +
	"\x04Echo\x12;.examples.internal.proto.examplepb.UnannotatedSimpleMessage\x1a;.examples.internal.proto.examplepb.UnannotatedSimpleMessage\x12\x84\x01\n" +
	"\bEchoBody\x12;.examples.internal.proto.examplepb.UnannotatedSimpleMessage\x1a;.examples.internal.proto.examplepb.UnannotatedSimpleMessage\x12\x86\x01\n" +
	"\n" +
	"EchoDelete\x12;.examples.internal.proto.examplepb.UnannotatedSimpleMessage\x1a;.examples.internal.proto.examplepb.UnannotatedSimpleMessage\x12\x86\x01\n" +
	"\n" +
	"EchoNested\x12;.examples.internal.proto.examplepb.UnannotatedSimpleMessage\x1a;.examples.internal.proto.examplepb.UnannotatedSimpleMessageBWZUgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepb;examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDescData
}

var file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_internal_proto_examplepb_unannotated_echo_service_proto_goTypes = []any{
	(*UnannotatedEmbedded)(nil),      // 0: examples.internal.proto.examplepb.UnannotatedEmbedded
	(*UnannotatedNestedMessage)(nil), // 1: examples.internal.proto.examplepb.UnannotatedNestedMessage
	(*UnannotatedSimpleMessage)(nil), // 2: examples.internal.proto.examplepb.UnannotatedSimpleMessage
	(*durationpb.Duration)(nil),      // 3: google.protobuf.Duration
}
var file_examples_internal_proto_examplepb_unannotated_echo_service_proto_depIdxs = []int32{
	3, // 0: examples.internal.proto.examplepb.UnannotatedSimpleMessage.duration:type_name -> google.protobuf.Duration
	0, // 1: examples.internal.proto.examplepb.UnannotatedSimpleMessage.status:type_name -> examples.internal.proto.examplepb.UnannotatedEmbedded
	0, // 2: examples.internal.proto.examplepb.UnannotatedSimpleMessage.no:type_name -> examples.internal.proto.examplepb.UnannotatedEmbedded
	1, // 3: examples.internal.proto.examplepb.UnannotatedSimpleMessage.n_id:type_name -> examples.internal.proto.examplepb.UnannotatedNestedMessage
	2, // 4: examples.internal.proto.examplepb.UnannotatedEchoService.Echo:input_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	2, // 5: examples.internal.proto.examplepb.UnannotatedEchoService.EchoBody:input_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	2, // 6: examples.internal.proto.examplepb.UnannotatedEchoService.EchoDelete:input_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	2, // 7: examples.internal.proto.examplepb.UnannotatedEchoService.EchoNested:input_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	2, // 8: examples.internal.proto.examplepb.UnannotatedEchoService.Echo:output_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	2, // 9: examples.internal.proto.examplepb.UnannotatedEchoService.EchoBody:output_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	2, // 10: examples.internal.proto.examplepb.UnannotatedEchoService.EchoDelete:output_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	2, // 11: examples.internal.proto.examplepb.UnannotatedEchoService.EchoNested:output_type -> examples.internal.proto.examplepb.UnannotatedSimpleMessage
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_unannotated_echo_service_proto_init() }
func file_examples_internal_proto_examplepb_unannotated_echo_service_proto_init() {
	if File_examples_internal_proto_examplepb_unannotated_echo_service_proto != nil {
		return
	}
	file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[0].OneofWrappers = []any{
		(*UnannotatedEmbedded_Progress)(nil),
		(*UnannotatedEmbedded_Note)(nil),
	}
	file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes[2].OneofWrappers = []any{
		(*UnannotatedSimpleMessage_LineNum)(nil),
		(*UnannotatedSimpleMessage_Lang)(nil),
		(*UnannotatedSimpleMessage_En)(nil),
		(*UnannotatedSimpleMessage_No)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_unannotated_echo_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_unannotated_echo_service_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_unannotated_echo_service_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_unannotated_echo_service_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_unannotated_echo_service_proto = out.File
	file_examples_internal_proto_examplepb_unannotated_echo_service_proto_goTypes = nil
	file_examples_internal_proto_examplepb_unannotated_echo_service_proto_depIdxs = nil
}
