// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/use_go_template.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The entered username
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// The entered password
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_use_go_template_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Message string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Whether you have access or not
	Access        bool `protobuf:"varint,2,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_use_go_template_proto_rawDescGZIP(), []int{1}
}

func (x *LoginReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginReply) GetAccess() bool {
	if x != nil {
		return x.Access
	}
	return false
}

type LogoutRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time the logout was registered
	Timeoflogout string `protobuf:"bytes,1,opt,name=timeoflogout,proto3" json:"timeoflogout,omitempty"`
	// This is the title
	//
	// This is the "Description" of field test
	// you can use as many newlines as you want
	//
	// it will still format the same in the table
	Test int32 `protobuf:"varint,2,opt,name=test,proto3" json:"test,omitempty"`
	// This is an array
	//
	// It displays that using [] in front of the type
	Stringarray   []string `protobuf:"bytes,3,rep,name=stringarray,proto3" json:"stringarray,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_use_go_template_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetTimeoflogout() string {
	if x != nil {
		return x.Timeoflogout
	}
	return ""
}

func (x *LogoutRequest) GetTest() int32 {
	if x != nil {
		return x.Test
	}
	return 0
}

func (x *LogoutRequest) GetStringarray() []string {
	if x != nil {
		return x.Stringarray
	}
	return nil
}

type LogoutReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message that tells you whether your
	// logout was successful or not
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_use_go_template_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_examples_internal_proto_examplepb_use_go_template_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_use_go_template_proto_rawDesc = "" +
	"\n" +
	"7examples/internal/proto/examplepb/use_go_template.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\n" +
	"LoginReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06access\x18\x02 \x01(\bR\x06access\"i\n" +
	"\rLogoutRequest\x12\"\n" +
	"\ftimeoflogout\x18\x01 \x01(\tR\ftimeoflogout\x12\x12\n" +
	"\x04test\x18\x02 \x01(\x05R\x04test\x12 \n" +
	"\vstringarray\x18\x03 \x03(\tR\vstringarray\"'\n" +
	"\vLogoutReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xa2\x02\n" +
	"\fLoginService\x12\x85\x01\n" +
	"\x05Login\x12/.examples.internal.proto.examplepb.LoginRequest\x1a-.examples.internal.proto.examplepb.LoginReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/example/login\x12\x89\x01\n" +
	"\x06Logout\x120.examples.internal.proto.examplepb.LogoutRequest\x1a..examples.internal.proto.examplepb.LogoutReply\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/example/logoutBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_use_go_template_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_use_go_template_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_use_go_template_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_use_go_template_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_use_go_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_use_go_template_proto_rawDesc), len(file_examples_internal_proto_examplepb_use_go_template_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_use_go_template_proto_rawDescData
}

var file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_internal_proto_examplepb_use_go_template_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: examples.internal.proto.examplepb.LoginRequest
	(*LoginReply)(nil),    // 1: examples.internal.proto.examplepb.LoginReply
	(*LogoutRequest)(nil), // 2: examples.internal.proto.examplepb.LogoutRequest
	(*LogoutReply)(nil),   // 3: examples.internal.proto.examplepb.LogoutReply
}
var file_examples_internal_proto_examplepb_use_go_template_proto_depIdxs = []int32{
	0, // 0: examples.internal.proto.examplepb.LoginService.Login:input_type -> examples.internal.proto.examplepb.LoginRequest
	2, // 1: examples.internal.proto.examplepb.LoginService.Logout:input_type -> examples.internal.proto.examplepb.LogoutRequest
	1, // 2: examples.internal.proto.examplepb.LoginService.Login:output_type -> examples.internal.proto.examplepb.LoginReply
	3, // 3: examples.internal.proto.examplepb.LoginService.Logout:output_type -> examples.internal.proto.examplepb.LogoutReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_use_go_template_proto_init() }
func file_examples_internal_proto_examplepb_use_go_template_proto_init() {
	if File_examples_internal_proto_examplepb_use_go_template_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_use_go_template_proto_rawDesc), len(file_examples_internal_proto_examplepb_use_go_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_use_go_template_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_use_go_template_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_use_go_template_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_use_go_template_proto = out.File
	file_examples_internal_proto_examplepb_use_go_template_proto_goTypes = nil
	file_examples_internal_proto_examplepb_use_go_template_proto_depIdxs = nil
}
