// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/visibility_rule_echo_service.proto

// Visibility Rule Echo Service
// Similar to echo_service.proto but with annotations to change visibility
// of services, methods, fields and enum values.
//
// `google.api.VisibilityRule` annotations are added to customize where they are generated.
// Combined with the option `visibility_restriction_selectors` overlapping rules will appear in the OpenAPI output.
// Elements without `google.api.VisibilityRule` annotations will appear as usual in the generated output.
//
// These restrictions and selectors are completely arbitrary and you can define whatever values or hierarchies you want.
// In this example `INTERNAL`, `PREVIEW` are used, but `INTERNAL`, `ALPHA`, `BETA`, `RELEASED`, or anything else could be used if you wish.

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnumInPreviewMethod doesn't define its own visibility restrictions,
// but is only included in a method marked as "PREVIEW", so it will only
// appear if `visibility_restriction_selectors` include "PREVIEW".
type VisibilityRuleEnumInPreviewMethod int32

const (
	VisibilityRuleEnumInPreviewMethod_VISIBILITY_RULE_ENUM_IN_PREVIEW_METHOD_UNSPECIFIED VisibilityRuleEnumInPreviewMethod = 0
)

// Enum value maps for VisibilityRuleEnumInPreviewMethod.
var (
	VisibilityRuleEnumInPreviewMethod_name = map[int32]string{
		0: "VISIBILITY_RULE_ENUM_IN_PREVIEW_METHOD_UNSPECIFIED",
	}
	VisibilityRuleEnumInPreviewMethod_value = map[string]int32{
		"VISIBILITY_RULE_ENUM_IN_PREVIEW_METHOD_UNSPECIFIED": 0,
	}
)

func (x VisibilityRuleEnumInPreviewMethod) Enum() *VisibilityRuleEnumInPreviewMethod {
	p := new(VisibilityRuleEnumInPreviewMethod)
	*p = x
	return p
}

func (x VisibilityRuleEnumInPreviewMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityRuleEnumInPreviewMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes[0].Descriptor()
}

func (VisibilityRuleEnumInPreviewMethod) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes[0]
}

func (x VisibilityRuleEnumInPreviewMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityRuleEnumInPreviewMethod.Descriptor instead.
func (VisibilityRuleEnumInPreviewMethod) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP(), []int{0}
}

type VisibilityRuleSimpleMessage_VisibilityEnum int32

const (
	VisibilityRuleSimpleMessage_VISIBILITY_ENUM_UNSPECIFIED VisibilityRuleSimpleMessage_VisibilityEnum = 0
	VisibilityRuleSimpleMessage_VISIBILITY_ENUM_VISIBLE     VisibilityRuleSimpleMessage_VisibilityEnum = 1
	VisibilityRuleSimpleMessage_VISIBILITY_ENUM_INTERNAL    VisibilityRuleSimpleMessage_VisibilityEnum = 2
	VisibilityRuleSimpleMessage_VISIBILITY_ENUM_PREVIEW     VisibilityRuleSimpleMessage_VisibilityEnum = 3
)

// Enum value maps for VisibilityRuleSimpleMessage_VisibilityEnum.
var (
	VisibilityRuleSimpleMessage_VisibilityEnum_name = map[int32]string{
		0: "VISIBILITY_ENUM_UNSPECIFIED",
		1: "VISIBILITY_ENUM_VISIBLE",
		2: "VISIBILITY_ENUM_INTERNAL",
		3: "VISIBILITY_ENUM_PREVIEW",
	}
	VisibilityRuleSimpleMessage_VisibilityEnum_value = map[string]int32{
		"VISIBILITY_ENUM_UNSPECIFIED": 0,
		"VISIBILITY_ENUM_VISIBLE":     1,
		"VISIBILITY_ENUM_INTERNAL":    2,
		"VISIBILITY_ENUM_PREVIEW":     3,
	}
)

func (x VisibilityRuleSimpleMessage_VisibilityEnum) Enum() *VisibilityRuleSimpleMessage_VisibilityEnum {
	p := new(VisibilityRuleSimpleMessage_VisibilityEnum)
	*p = x
	return p
}

func (x VisibilityRuleSimpleMessage_VisibilityEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityRuleSimpleMessage_VisibilityEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes[1].Descriptor()
}

func (VisibilityRuleSimpleMessage_VisibilityEnum) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes[1]
}

func (x VisibilityRuleSimpleMessage_VisibilityEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityRuleSimpleMessage_VisibilityEnum.Descriptor instead.
func (VisibilityRuleSimpleMessage_VisibilityEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP(), []int{1, 0}
}

type VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault int32

const (
	VisibilityRuleSimpleMessage_VISIBILITY_ENUM_HIDDEN_DEFAULT_UNSPECIFIED VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault = 0
	VisibilityRuleSimpleMessage_VISIBILITY_ENUM_HIDDEN_DEFAULT_VISIBLE     VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault = 1
)

// Enum value maps for VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault.
var (
	VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault_name = map[int32]string{
		0: "VISIBILITY_ENUM_HIDDEN_DEFAULT_UNSPECIFIED",
		1: "VISIBILITY_ENUM_HIDDEN_DEFAULT_VISIBLE",
	}
	VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault_value = map[string]int32{
		"VISIBILITY_ENUM_HIDDEN_DEFAULT_UNSPECIFIED": 0,
		"VISIBILITY_ENUM_HIDDEN_DEFAULT_VISIBLE":     1,
	}
)

func (x VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault) Enum() *VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault {
	p := new(VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault)
	*p = x
	return p
}

func (x VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes[2].Descriptor()
}

func (VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault) Type() protoreflect.EnumType {
	return &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes[2]
}

func (x VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault.Descriptor instead.
func (VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault) EnumDescriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP(), []int{1, 1}
}

// Embedded represents a message embedded in SimpleMessage.
type VisibilityRuleEmbedded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mark:
	//
	//	*VisibilityRuleEmbedded_Progress
	//	*VisibilityRuleEmbedded_Note
	//	*VisibilityRuleEmbedded_InternalField
	//	*VisibilityRuleEmbedded_PreviewField
	Mark          isVisibilityRuleEmbedded_Mark `protobuf_oneof:"mark"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityRuleEmbedded) Reset() {
	*x = VisibilityRuleEmbedded{}
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityRuleEmbedded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityRuleEmbedded) ProtoMessage() {}

func (x *VisibilityRuleEmbedded) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityRuleEmbedded.ProtoReflect.Descriptor instead.
func (*VisibilityRuleEmbedded) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP(), []int{0}
}

func (x *VisibilityRuleEmbedded) GetMark() isVisibilityRuleEmbedded_Mark {
	if x != nil {
		return x.Mark
	}
	return nil
}

func (x *VisibilityRuleEmbedded) GetProgress() int64 {
	if x != nil {
		if x, ok := x.Mark.(*VisibilityRuleEmbedded_Progress); ok {
			return x.Progress
		}
	}
	return 0
}

func (x *VisibilityRuleEmbedded) GetNote() string {
	if x != nil {
		if x, ok := x.Mark.(*VisibilityRuleEmbedded_Note); ok {
			return x.Note
		}
	}
	return ""
}

func (x *VisibilityRuleEmbedded) GetInternalField() string {
	if x != nil {
		if x, ok := x.Mark.(*VisibilityRuleEmbedded_InternalField); ok {
			return x.InternalField
		}
	}
	return ""
}

func (x *VisibilityRuleEmbedded) GetPreviewField() string {
	if x != nil {
		if x, ok := x.Mark.(*VisibilityRuleEmbedded_PreviewField); ok {
			return x.PreviewField
		}
	}
	return ""
}

type isVisibilityRuleEmbedded_Mark interface {
	isVisibilityRuleEmbedded_Mark()
}

type VisibilityRuleEmbedded_Progress struct {
	Progress int64 `protobuf:"varint,1,opt,name=progress,proto3,oneof"`
}

type VisibilityRuleEmbedded_Note struct {
	Note string `protobuf:"bytes,2,opt,name=note,proto3,oneof"`
}

type VisibilityRuleEmbedded_InternalField struct {
	InternalField string `protobuf:"bytes,3,opt,name=internal_field,json=internalField,proto3,oneof"`
}

type VisibilityRuleEmbedded_PreviewField struct {
	PreviewField string `protobuf:"bytes,4,opt,name=preview_field,json=previewField,proto3,oneof"`
}

func (*VisibilityRuleEmbedded_Progress) isVisibilityRuleEmbedded_Mark() {}

func (*VisibilityRuleEmbedded_Note) isVisibilityRuleEmbedded_Mark() {}

func (*VisibilityRuleEmbedded_InternalField) isVisibilityRuleEmbedded_Mark() {}

func (*VisibilityRuleEmbedded_PreviewField) isVisibilityRuleEmbedded_Mark() {}

// SimpleMessage represents a simple message sent to the Echo service.
type VisibilityRuleSimpleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Num int64  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	// Types that are valid to be assigned to Code:
	//
	//	*VisibilityRuleSimpleMessage_LineNum
	//	*VisibilityRuleSimpleMessage_Lang
	Code   isVisibilityRuleSimpleMessage_Code `protobuf_oneof:"code"`
	Status *VisibilityRuleEmbedded            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Types that are valid to be assigned to Ext:
	//
	//	*VisibilityRuleSimpleMessage_En
	//	*VisibilityRuleSimpleMessage_No
	Ext                isVisibilityRuleSimpleMessage_Ext                       `protobuf_oneof:"ext"`
	InternalField      string                                                  `protobuf:"bytes,8,opt,name=internal_field,json=internalField,proto3" json:"internal_field,omitempty"`
	PreviewField       string                                                  `protobuf:"bytes,9,opt,name=preview_field,json=previewField,proto3" json:"preview_field,omitempty"`
	AnEnum             VisibilityRuleSimpleMessage_VisibilityEnum              `protobuf:"varint,10,opt,name=an_enum,json=anEnum,proto3,enum=examples.internal.proto.examplepb.VisibilityRuleSimpleMessage_VisibilityEnum" json:"an_enum,omitempty"`
	AhiddenDefaultEnum VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault `protobuf:"varint,11,opt,name=ahidden_default_enum,json=ahiddenDefaultEnum,proto3,enum=examples.internal.proto.examplepb.VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault" json:"ahidden_default_enum,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VisibilityRuleSimpleMessage) Reset() {
	*x = VisibilityRuleSimpleMessage{}
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityRuleSimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityRuleSimpleMessage) ProtoMessage() {}

func (x *VisibilityRuleSimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityRuleSimpleMessage.ProtoReflect.Descriptor instead.
func (*VisibilityRuleSimpleMessage) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP(), []int{1}
}

func (x *VisibilityRuleSimpleMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VisibilityRuleSimpleMessage) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *VisibilityRuleSimpleMessage) GetCode() isVisibilityRuleSimpleMessage_Code {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *VisibilityRuleSimpleMessage) GetLineNum() int64 {
	if x != nil {
		if x, ok := x.Code.(*VisibilityRuleSimpleMessage_LineNum); ok {
			return x.LineNum
		}
	}
	return 0
}

func (x *VisibilityRuleSimpleMessage) GetLang() string {
	if x != nil {
		if x, ok := x.Code.(*VisibilityRuleSimpleMessage_Lang); ok {
			return x.Lang
		}
	}
	return ""
}

func (x *VisibilityRuleSimpleMessage) GetStatus() *VisibilityRuleEmbedded {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VisibilityRuleSimpleMessage) GetExt() isVisibilityRuleSimpleMessage_Ext {
	if x != nil {
		return x.Ext
	}
	return nil
}

func (x *VisibilityRuleSimpleMessage) GetEn() int64 {
	if x != nil {
		if x, ok := x.Ext.(*VisibilityRuleSimpleMessage_En); ok {
			return x.En
		}
	}
	return 0
}

func (x *VisibilityRuleSimpleMessage) GetNo() *VisibilityRuleEmbedded {
	if x != nil {
		if x, ok := x.Ext.(*VisibilityRuleSimpleMessage_No); ok {
			return x.No
		}
	}
	return nil
}

func (x *VisibilityRuleSimpleMessage) GetInternalField() string {
	if x != nil {
		return x.InternalField
	}
	return ""
}

func (x *VisibilityRuleSimpleMessage) GetPreviewField() string {
	if x != nil {
		return x.PreviewField
	}
	return ""
}

func (x *VisibilityRuleSimpleMessage) GetAnEnum() VisibilityRuleSimpleMessage_VisibilityEnum {
	if x != nil {
		return x.AnEnum
	}
	return VisibilityRuleSimpleMessage_VISIBILITY_ENUM_UNSPECIFIED
}

func (x *VisibilityRuleSimpleMessage) GetAhiddenDefaultEnum() VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault {
	if x != nil {
		return x.AhiddenDefaultEnum
	}
	return VisibilityRuleSimpleMessage_VISIBILITY_ENUM_HIDDEN_DEFAULT_UNSPECIFIED
}

type isVisibilityRuleSimpleMessage_Code interface {
	isVisibilityRuleSimpleMessage_Code()
}

type VisibilityRuleSimpleMessage_LineNum struct {
	LineNum int64 `protobuf:"varint,3,opt,name=line_num,json=lineNum,proto3,oneof"`
}

type VisibilityRuleSimpleMessage_Lang struct {
	Lang string `protobuf:"bytes,4,opt,name=lang,proto3,oneof"`
}

func (*VisibilityRuleSimpleMessage_LineNum) isVisibilityRuleSimpleMessage_Code() {}

func (*VisibilityRuleSimpleMessage_Lang) isVisibilityRuleSimpleMessage_Code() {}

type isVisibilityRuleSimpleMessage_Ext interface {
	isVisibilityRuleSimpleMessage_Ext()
}

type VisibilityRuleSimpleMessage_En struct {
	En int64 `protobuf:"varint,6,opt,name=en,proto3,oneof"`
}

type VisibilityRuleSimpleMessage_No struct {
	No *VisibilityRuleEmbedded `protobuf:"bytes,7,opt,name=no,proto3,oneof"`
}

func (*VisibilityRuleSimpleMessage_En) isVisibilityRuleSimpleMessage_Ext() {}

func (*VisibilityRuleSimpleMessage_No) isVisibilityRuleSimpleMessage_Ext() {}

// MessageInPreviewMethod doesn't define its own visibility restrictions,
// but is only included in a method marked as "PREVIEW", so it will only
// appear if `visibility_restriction_selectors` include "PREVIEW".
type VisibilityRuleMessageInPreviewMethod struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Id            string                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubMessage    *VisibilityRuleSubMessageInPreviewMethod `protobuf:"bytes,2,opt,name=sub_message,json=subMessage,proto3" json:"sub_message,omitempty"`
	Enum          VisibilityRuleEnumInPreviewMethod        `protobuf:"varint,3,opt,name=enum,proto3,enum=examples.internal.proto.examplepb.VisibilityRuleEnumInPreviewMethod" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityRuleMessageInPreviewMethod) Reset() {
	*x = VisibilityRuleMessageInPreviewMethod{}
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityRuleMessageInPreviewMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityRuleMessageInPreviewMethod) ProtoMessage() {}

func (x *VisibilityRuleMessageInPreviewMethod) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityRuleMessageInPreviewMethod.ProtoReflect.Descriptor instead.
func (*VisibilityRuleMessageInPreviewMethod) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP(), []int{2}
}

func (x *VisibilityRuleMessageInPreviewMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VisibilityRuleMessageInPreviewMethod) GetSubMessage() *VisibilityRuleSubMessageInPreviewMethod {
	if x != nil {
		return x.SubMessage
	}
	return nil
}

func (x *VisibilityRuleMessageInPreviewMethod) GetEnum() VisibilityRuleEnumInPreviewMethod {
	if x != nil {
		return x.Enum
	}
	return VisibilityRuleEnumInPreviewMethod_VISIBILITY_RULE_ENUM_IN_PREVIEW_METHOD_UNSPECIFIED
}

// SubMessageInPreviewMethod doesn't define its own visibility restrictions,
// but is only included in a method marked as "PREVIEW", so it will only
// appear if `visibility_restriction_selectors` include "PREVIEW".
type VisibilityRuleSubMessageInPreviewMethod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisibilityRuleSubMessageInPreviewMethod) Reset() {
	*x = VisibilityRuleSubMessageInPreviewMethod{}
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisibilityRuleSubMessageInPreviewMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisibilityRuleSubMessageInPreviewMethod) ProtoMessage() {}

func (x *VisibilityRuleSubMessageInPreviewMethod) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisibilityRuleSubMessageInPreviewMethod.ProtoReflect.Descriptor instead.
func (*VisibilityRuleSubMessageInPreviewMethod) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP(), []int{3}
}

func (x *VisibilityRuleSubMessageInPreviewMethod) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_examples_internal_proto_examplepb_visibility_rule_echo_service_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDesc = "" +
	"\n" +
	"Dexamples/internal/proto/examplepb/visibility_rule_echo_service.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/api/visibility.proto\"\xd0\x01\n" +
	"\x16VisibilityRuleEmbedded\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\x03H\x00R\bprogress\x12\x14\n" +
	"\x04note\x18\x02 \x01(\tH\x00R\x04note\x129\n" +
	"\x0einternal_field\x18\x03 \x01(\tB\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNALH\x00R\rinternalField\x12?\n" +
	"\rpreview_field\x18\x04 \x01(\tB\x18\xfa\xd2\xe4\x93\x02\x12\x12\x10INTERNAL,PREVIEWH\x00R\fpreviewFieldB\x06\n" +
	"\x04mark\"\xe8\a\n" +
	"\x1bVisibilityRuleSimpleMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\x12\x1b\n" +
	"\bline_num\x18\x03 \x01(\x03H\x00R\alineNum\x12\x14\n" +
	"\x04lang\x18\x04 \x01(\tH\x00R\x04lang\x12Q\n" +
	"\x06status\x18\x05 \x01(\v29.examples.internal.proto.examplepb.VisibilityRuleEmbeddedR\x06status\x12\x10\n" +
	"\x02en\x18\x06 \x01(\x03H\x01R\x02en\x12K\n" +
	"\x02no\x18\a \x01(\v29.examples.internal.proto.examplepb.VisibilityRuleEmbeddedH\x01R\x02no\x127\n" +
	"\x0einternal_field\x18\b \x01(\tB\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNALR\rinternalField\x12=\n" +
	"\rpreview_field\x18\t \x01(\tB\x18\xfa\xd2\xe4\x93\x02\x12\x12\x10INTERNAL,PREVIEWR\fpreviewField\x12f\n" +
	"\aan_enum\x18\n" +
	" \x01(\x0e2M.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.VisibilityEnumR\x06anEnum\x12\x8c\x01\n" +
	"\x14ahidden_default_enum\x18\v \x01(\x0e2Z.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.VisibilityEnumHiddenDefaultR\x12ahiddenDefaultEnum\"\xb5\x01\n" +
	"\x0eVisibilityEnum\x12\x1f\n" +
	"\x1bVISIBILITY_ENUM_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VISIBILITY_ENUM_VISIBLE\x10\x01\x12.\n" +
	"\x18VISIBILITY_ENUM_INTERNAL\x10\x02\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x125\n" +
	"\x17VISIBILITY_ENUM_PREVIEW\x10\x03\x1a\x18\xfa\xd2\xe4\x93\x02\x12\x12\x10INTERNAL,PREVIEW\"\x8b\x01\n" +
	"\x1bVisibilityEnumHiddenDefault\x12@\n" +
	"*VISIBILITY_ENUM_HIDDEN_DEFAULT_UNSPECIFIED\x10\x00\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x12*\n" +
	"&VISIBILITY_ENUM_HIDDEN_DEFAULT_VISIBLE\x10\x01B\x06\n" +
	"\x04codeB\x05\n" +
	"\x03ext\"\xfd\x01\n" +
	"$VisibilityRuleMessageInPreviewMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12k\n" +
	"\vsub_message\x18\x02 \x01(\v2J.examples.internal.proto.examplepb.VisibilityRuleSubMessageInPreviewMethodR\n" +
	"subMessage\x12X\n" +
	"\x04enum\x18\x03 \x01(\x0e2D.examples.internal.proto.examplepb.VisibilityRuleEnumInPreviewMethodR\x04enum\"9\n" +
	"'VisibilityRuleSubMessageInPreviewMethod\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*[\n" +
	"!VisibilityRuleEnumInPreviewMethod\x126\n" +
	"2VISIBILITY_RULE_ENUM_IN_PREVIEW_METHOD_UNSPECIFIED\x10\x002\xb3\x06\n" +
	"\x19VisibilityRuleEchoService\x12\xa5\x01\n" +
	"\x04Echo\x12>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\x1a>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x15/v1/example/echo/{id}\x12\xc1\x01\n" +
	"\fEchoInternal\x12>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\x1a>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\"1\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/example/echo_internal\x12\xc7\x01\n" +
	"\vEchoPreview\x12>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\x1aG.examples.internal.proto.examplepb.VisibilityRuleMessageInPreviewMethod\"/\xfa\xd2\xe4\x93\x02\t\x12\aPREVIEW\x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/example/echo_preview\x12\xdf\x01\n" +
	"\x16EchoInternalAndPreview\x12>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\x1a>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\"E\xfa\xd2\xe4\x93\x02\x12\x12\x10INTERNAL,PREVIEW\x82\xd3\xe4\x93\x02'\x12%/v1/example/echo_internal_and_preview2\xe6\x01\n" +
	"!VisibilityRuleInternalEchoService\x12\xae\x01\n" +
	"\x04Echo\x12>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\x1a>.examples.internal.proto.examplepb.VisibilityRuleSimpleMessage\"&\x82\xd3\xe4\x93\x02 \"\x1e/v1/example/internal/echo/{id}\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNALBWZUgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepb;examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDescData
}

var file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_goTypes = []any{
	(VisibilityRuleEnumInPreviewMethod)(0),                       // 0: examples.internal.proto.examplepb.VisibilityRuleEnumInPreviewMethod
	(VisibilityRuleSimpleMessage_VisibilityEnum)(0),              // 1: examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.VisibilityEnum
	(VisibilityRuleSimpleMessage_VisibilityEnumHiddenDefault)(0), // 2: examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.VisibilityEnumHiddenDefault
	(*VisibilityRuleEmbedded)(nil),                               // 3: examples.internal.proto.examplepb.VisibilityRuleEmbedded
	(*VisibilityRuleSimpleMessage)(nil),                          // 4: examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	(*VisibilityRuleMessageInPreviewMethod)(nil),                 // 5: examples.internal.proto.examplepb.VisibilityRuleMessageInPreviewMethod
	(*VisibilityRuleSubMessageInPreviewMethod)(nil),              // 6: examples.internal.proto.examplepb.VisibilityRuleSubMessageInPreviewMethod
}
var file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_depIdxs = []int32{
	3,  // 0: examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.status:type_name -> examples.internal.proto.examplepb.VisibilityRuleEmbedded
	3,  // 1: examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.no:type_name -> examples.internal.proto.examplepb.VisibilityRuleEmbedded
	1,  // 2: examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.an_enum:type_name -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.VisibilityEnum
	2,  // 3: examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.ahidden_default_enum:type_name -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage.VisibilityEnumHiddenDefault
	6,  // 4: examples.internal.proto.examplepb.VisibilityRuleMessageInPreviewMethod.sub_message:type_name -> examples.internal.proto.examplepb.VisibilityRuleSubMessageInPreviewMethod
	0,  // 5: examples.internal.proto.examplepb.VisibilityRuleMessageInPreviewMethod.enum:type_name -> examples.internal.proto.examplepb.VisibilityRuleEnumInPreviewMethod
	4,  // 6: examples.internal.proto.examplepb.VisibilityRuleEchoService.Echo:input_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	4,  // 7: examples.internal.proto.examplepb.VisibilityRuleEchoService.EchoInternal:input_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	4,  // 8: examples.internal.proto.examplepb.VisibilityRuleEchoService.EchoPreview:input_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	4,  // 9: examples.internal.proto.examplepb.VisibilityRuleEchoService.EchoInternalAndPreview:input_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	4,  // 10: examples.internal.proto.examplepb.VisibilityRuleInternalEchoService.Echo:input_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	4,  // 11: examples.internal.proto.examplepb.VisibilityRuleEchoService.Echo:output_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	4,  // 12: examples.internal.proto.examplepb.VisibilityRuleEchoService.EchoInternal:output_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	5,  // 13: examples.internal.proto.examplepb.VisibilityRuleEchoService.EchoPreview:output_type -> examples.internal.proto.examplepb.VisibilityRuleMessageInPreviewMethod
	4,  // 14: examples.internal.proto.examplepb.VisibilityRuleEchoService.EchoInternalAndPreview:output_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	4,  // 15: examples.internal.proto.examplepb.VisibilityRuleInternalEchoService.Echo:output_type -> examples.internal.proto.examplepb.VisibilityRuleSimpleMessage
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_init() }
func file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_init() {
	if File_examples_internal_proto_examplepb_visibility_rule_echo_service_proto != nil {
		return
	}
	file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[0].OneofWrappers = []any{
		(*VisibilityRuleEmbedded_Progress)(nil),
		(*VisibilityRuleEmbedded_Note)(nil),
		(*VisibilityRuleEmbedded_InternalField)(nil),
		(*VisibilityRuleEmbedded_PreviewField)(nil),
	}
	file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes[1].OneofWrappers = []any{
		(*VisibilityRuleSimpleMessage_LineNum)(nil),
		(*VisibilityRuleSimpleMessage_Lang)(nil),
		(*VisibilityRuleSimpleMessage_En)(nil),
		(*VisibilityRuleSimpleMessage_No)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDesc), len(file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_depIdxs,
		EnumInfos:         file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_enumTypes,
		MessageInfos:      file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_visibility_rule_echo_service_proto = out.File
	file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_goTypes = nil
	file_examples_internal_proto_examplepb_visibility_rule_echo_service_proto_depIdxs = nil
}
