// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: examples/internal/proto/examplepb/wrappers.proto

package examplepb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wrappers struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	StringValue   *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	Int32Value    *wrapperspb.Int32Value  `protobuf:"bytes,2,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Int64Value    *wrapperspb.Int64Value  `protobuf:"bytes,3,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	FloatValue    *wrapperspb.FloatValue  `protobuf:"bytes,4,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	DoubleValue   *wrapperspb.DoubleValue `protobuf:"bytes,5,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	BoolValue     *wrapperspb.BoolValue   `protobuf:"bytes,6,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	Uint32Value   *wrapperspb.UInt32Value `protobuf:"bytes,7,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	Uint64Value   *wrapperspb.UInt64Value `protobuf:"bytes,8,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	BytesValue    *wrapperspb.BytesValue  `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrappers) Reset() {
	*x = Wrappers{}
	mi := &file_examples_internal_proto_examplepb_wrappers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrappers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrappers) ProtoMessage() {}

func (x *Wrappers) ProtoReflect() protoreflect.Message {
	mi := &file_examples_internal_proto_examplepb_wrappers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrappers.ProtoReflect.Descriptor instead.
func (*Wrappers) Descriptor() ([]byte, []int) {
	return file_examples_internal_proto_examplepb_wrappers_proto_rawDescGZIP(), []int{0}
}

func (x *Wrappers) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *Wrappers) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Value
	}
	return nil
}

func (x *Wrappers) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Value
	}
	return nil
}

func (x *Wrappers) GetFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValue
	}
	return nil
}

func (x *Wrappers) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValue
	}
	return nil
}

func (x *Wrappers) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValue
	}
	return nil
}

func (x *Wrappers) GetUint32Value() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Value
	}
	return nil
}

func (x *Wrappers) GetUint64Value() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Value
	}
	return nil
}

func (x *Wrappers) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

var File_examples_internal_proto_examplepb_wrappers_proto protoreflect.FileDescriptor

const file_examples_internal_proto_examplepb_wrappers_proto_rawDesc = "" +
	"\n" +
	"0examples/internal/proto/examplepb/wrappers.proto\x12!examples.internal.proto.examplepb\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc1\x04\n" +
	"\bWrappers\x12?\n" +
	"\fstring_value\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\vstringValue\x12<\n" +
	"\vint32_value\x18\x02 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"int32Value\x12<\n" +
	"\vint64_value\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"int64Value\x12<\n" +
	"\vfloat_value\x18\x04 \x01(\v2\x1b.google.protobuf.FloatValueR\n" +
	"floatValue\x12?\n" +
	"\fdouble_value\x18\x05 \x01(\v2\x1c.google.protobuf.DoubleValueR\vdoubleValue\x129\n" +
	"\n" +
	"bool_value\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\tboolValue\x12?\n" +
	"\fuint32_value\x18\a \x01(\v2\x1c.google.protobuf.UInt32ValueR\vuint32Value\x12?\n" +
	"\fuint64_value\x18\b \x01(\v2\x1c.google.protobuf.UInt64ValueR\vuint64Value\x12<\n" +
	"\vbytes_value\x18\t \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"bytesValue2\xa4\t\n" +
	"\x0fWrappersService\x12\x83\x01\n" +
	"\x06Create\x12+.examples.internal.proto.examplepb.Wrappers\x1a+.examples.internal.proto.examplepb.Wrappers\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/example/wrappers\x12j\n" +
	"\x11CreateStringValue\x12\x1c.google.protobuf.StringValue\x1a\x1c.google.protobuf.StringValue\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/testString\x12f\n" +
	"\x10CreateInt32Value\x12\x1b.google.protobuf.Int32Value\x1a\x1b.google.protobuf.Int32Value\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/testInt32\x12f\n" +
	"\x10CreateInt64Value\x12\x1b.google.protobuf.Int64Value\x1a\x1b.google.protobuf.Int64Value\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/testInt64\x12f\n" +
	"\x10CreateFloatValue\x12\x1b.google.protobuf.FloatValue\x1a\x1b.google.protobuf.FloatValue\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/testFloat\x12j\n" +
	"\x11CreateDoubleValue\x12\x1c.google.protobuf.DoubleValue\x1a\x1c.google.protobuf.DoubleValue\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/testDouble\x12b\n" +
	"\x0fCreateBoolValue\x12\x1a.google.protobuf.BoolValue\x1a\x1a.google.protobuf.BoolValue\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/testBool\x12j\n" +
	"\x11CreateUInt32Value\x12\x1c.google.protobuf.UInt32Value\x1a\x1c.google.protobuf.UInt32Value\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/testUint32\x12j\n" +
	"\x11CreateUInt64Value\x12\x1c.google.protobuf.UInt64Value\x1a\x1c.google.protobuf.UInt64Value\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/testUint64\x12f\n" +
	"\x10CreateBytesValue\x12\x1b.google.protobuf.BytesValue\x1a\x1b.google.protobuf.BytesValue\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/testBytes\x12W\n" +
	"\vCreateEmpty\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/testEmptyBMZKgithub.com/essapp/grpc-gateway-example/v2/examples/internal/proto/examplepbb\x06proto3"

var (
	file_examples_internal_proto_examplepb_wrappers_proto_rawDescOnce sync.Once
	file_examples_internal_proto_examplepb_wrappers_proto_rawDescData []byte
)

func file_examples_internal_proto_examplepb_wrappers_proto_rawDescGZIP() []byte {
	file_examples_internal_proto_examplepb_wrappers_proto_rawDescOnce.Do(func() {
		file_examples_internal_proto_examplepb_wrappers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_wrappers_proto_rawDesc), len(file_examples_internal_proto_examplepb_wrappers_proto_rawDesc)))
	})
	return file_examples_internal_proto_examplepb_wrappers_proto_rawDescData
}

var file_examples_internal_proto_examplepb_wrappers_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_internal_proto_examplepb_wrappers_proto_goTypes = []any{
	(*Wrappers)(nil),               // 0: examples.internal.proto.examplepb.Wrappers
	(*wrapperspb.StringValue)(nil), // 1: google.protobuf.StringValue
	(*wrapperspb.Int32Value)(nil),  // 2: google.protobuf.Int32Value
	(*wrapperspb.Int64Value)(nil),  // 3: google.protobuf.Int64Value
	(*wrapperspb.FloatValue)(nil),  // 4: google.protobuf.FloatValue
	(*wrapperspb.DoubleValue)(nil), // 5: google.protobuf.DoubleValue
	(*wrapperspb.BoolValue)(nil),   // 6: google.protobuf.BoolValue
	(*wrapperspb.UInt32Value)(nil), // 7: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 8: google.protobuf.UInt64Value
	(*wrapperspb.BytesValue)(nil),  // 9: google.protobuf.BytesValue
	(*emptypb.Empty)(nil),          // 10: google.protobuf.Empty
}
var file_examples_internal_proto_examplepb_wrappers_proto_depIdxs = []int32{
	1,  // 0: examples.internal.proto.examplepb.Wrappers.string_value:type_name -> google.protobuf.StringValue
	2,  // 1: examples.internal.proto.examplepb.Wrappers.int32_value:type_name -> google.protobuf.Int32Value
	3,  // 2: examples.internal.proto.examplepb.Wrappers.int64_value:type_name -> google.protobuf.Int64Value
	4,  // 3: examples.internal.proto.examplepb.Wrappers.float_value:type_name -> google.protobuf.FloatValue
	5,  // 4: examples.internal.proto.examplepb.Wrappers.double_value:type_name -> google.protobuf.DoubleValue
	6,  // 5: examples.internal.proto.examplepb.Wrappers.bool_value:type_name -> google.protobuf.BoolValue
	7,  // 6: examples.internal.proto.examplepb.Wrappers.uint32_value:type_name -> google.protobuf.UInt32Value
	8,  // 7: examples.internal.proto.examplepb.Wrappers.uint64_value:type_name -> google.protobuf.UInt64Value
	9,  // 8: examples.internal.proto.examplepb.Wrappers.bytes_value:type_name -> google.protobuf.BytesValue
	0,  // 9: examples.internal.proto.examplepb.WrappersService.Create:input_type -> examples.internal.proto.examplepb.Wrappers
	1,  // 10: examples.internal.proto.examplepb.WrappersService.CreateStringValue:input_type -> google.protobuf.StringValue
	2,  // 11: examples.internal.proto.examplepb.WrappersService.CreateInt32Value:input_type -> google.protobuf.Int32Value
	3,  // 12: examples.internal.proto.examplepb.WrappersService.CreateInt64Value:input_type -> google.protobuf.Int64Value
	4,  // 13: examples.internal.proto.examplepb.WrappersService.CreateFloatValue:input_type -> google.protobuf.FloatValue
	5,  // 14: examples.internal.proto.examplepb.WrappersService.CreateDoubleValue:input_type -> google.protobuf.DoubleValue
	6,  // 15: examples.internal.proto.examplepb.WrappersService.CreateBoolValue:input_type -> google.protobuf.BoolValue
	7,  // 16: examples.internal.proto.examplepb.WrappersService.CreateUInt32Value:input_type -> google.protobuf.UInt32Value
	8,  // 17: examples.internal.proto.examplepb.WrappersService.CreateUInt64Value:input_type -> google.protobuf.UInt64Value
	9,  // 18: examples.internal.proto.examplepb.WrappersService.CreateBytesValue:input_type -> google.protobuf.BytesValue
	10, // 19: examples.internal.proto.examplepb.WrappersService.CreateEmpty:input_type -> google.protobuf.Empty
	0,  // 20: examples.internal.proto.examplepb.WrappersService.Create:output_type -> examples.internal.proto.examplepb.Wrappers
	1,  // 21: examples.internal.proto.examplepb.WrappersService.CreateStringValue:output_type -> google.protobuf.StringValue
	2,  // 22: examples.internal.proto.examplepb.WrappersService.CreateInt32Value:output_type -> google.protobuf.Int32Value
	3,  // 23: examples.internal.proto.examplepb.WrappersService.CreateInt64Value:output_type -> google.protobuf.Int64Value
	4,  // 24: examples.internal.proto.examplepb.WrappersService.CreateFloatValue:output_type -> google.protobuf.FloatValue
	5,  // 25: examples.internal.proto.examplepb.WrappersService.CreateDoubleValue:output_type -> google.protobuf.DoubleValue
	6,  // 26: examples.internal.proto.examplepb.WrappersService.CreateBoolValue:output_type -> google.protobuf.BoolValue
	7,  // 27: examples.internal.proto.examplepb.WrappersService.CreateUInt32Value:output_type -> google.protobuf.UInt32Value
	8,  // 28: examples.internal.proto.examplepb.WrappersService.CreateUInt64Value:output_type -> google.protobuf.UInt64Value
	9,  // 29: examples.internal.proto.examplepb.WrappersService.CreateBytesValue:output_type -> google.protobuf.BytesValue
	10, // 30: examples.internal.proto.examplepb.WrappersService.CreateEmpty:output_type -> google.protobuf.Empty
	20, // [20:31] is the sub-list for method output_type
	9,  // [9:20] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_examples_internal_proto_examplepb_wrappers_proto_init() }
func file_examples_internal_proto_examplepb_wrappers_proto_init() {
	if File_examples_internal_proto_examplepb_wrappers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_internal_proto_examplepb_wrappers_proto_rawDesc), len(file_examples_internal_proto_examplepb_wrappers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_examples_internal_proto_examplepb_wrappers_proto_goTypes,
		DependencyIndexes: file_examples_internal_proto_examplepb_wrappers_proto_depIdxs,
		MessageInfos:      file_examples_internal_proto_examplepb_wrappers_proto_msgTypes,
	}.Build()
	File_examples_internal_proto_examplepb_wrappers_proto = out.File
	file_examples_internal_proto_examplepb_wrappers_proto_goTypes = nil
	file_examples_internal_proto_examplepb_wrappers_proto_depIdxs = nil
}
